{% if showHeader == true %}
<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="http://fas-online.ru"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fas-online.ru" class="mh-mail">info@fas-online.ru</a>
        <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
    </div>
</div>
{% endif %}
<div class="c-ffaq">
    <div class="wrapper">
        <div class="c-ffaq-t">
            <div class="c-cnt-pagename">
                О проекте
            </div>
            «ФАС-ОНЛАЙН» — это сервис,<br>
            призванный помочь Вам стать<br>
            профессионалом госзакупок и защитить<br> права и интересы Вашего бизнеса
        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="c-content">
            <div class="c-about-t">
                Сервис содержит более 400 доводов для жалоб по различным ситуациям, связанным с проведением закупок товаров, работ, услуг для обеспечения государственных или муниципальных нужд по Федеральному закону от 05.04.2013 N 44-ФЗ.
 Процесс формирования и подачи жалобы максимально автоматизирован, что позволяет не думать о соблюдении формальностей и не отвлекаться от сути жалобы. Чтобы пользование сервисом «ФАС-ОНЛАЙН» было полностью комфортным, мы   предусмотрели возможность задать интересующий Вас вопрос нашему юристу, который даст квалифицированный ответ в кратчайшие сроки. А для экономии Вашего времени наш сервис самостоятельно проводит мониторинг статуса жалобы и незамедлительно проинформирует Вас о его смене.             

 «ФАС-ОНЛАЙН»
Наши преимущества - Ваш успех    </div>


        </div>
    </div>
</div>

<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label class="fontNormal" for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
            <span> <a href="#pop-start" class="open_modal" onclick="$('#pop-login').hide()">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a></span>
        </div>
    </form>
    <div class="already-reg already-reg-float">
        <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="#">Просмотреть</a></p>
    </div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>
<script src="/js/login_ajax.js"></script>
