{% if showHeader == true %}
<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="http://fas-online.ru"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fas-online.ru" class="mh-mail">info@fas-online.ru</a>
        <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
    </div>
</div>
{% endif %}
<div class="c-ffaq">
    <div class="wrapper">
        <div class="c-ffaq-t">
            <div class="c-cnt-pagename">
                О проекте
            </div>
            «Теории и практики» — это платформа для<br>
            обмена знаниями. Мы создаем среду для тех,<br>
            кто ищет знания и хочет ими делиться.
        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="c-content">
            <div class="c-about-t">
                &P объединяет людей и институции с помощью образовательных событий. Тысячи организаторов ежедневно добавляют информацию о своих лекциях, мастер-классах, курсах и конференциях во всех областях знаний.<br><br>
                Мы хотим, чтобы у человека была возможность выстраивать свою образовательную траекторию, основанную на потребностях, любопытстве и желании узнать что-то новое. Мы создаем среду, где каждый может научить и научиться, и место, где думать можно и нужно.<br><br>
                Сейчас T&P помогает создавать онлайн-сообщества вокруг вдохновляющих идей, а талантам позволяет находить возможности для самореализации — тем самым развивая экономику знаний.
            </div>


        </div>
    </div>
</div>

<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label class="fontNormal" for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
            <span> <a href="#pop-start" class="open_modal" onclick="$('#pop-login').hide()">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a></span>
        </div>
    </form>
    <div class="already-reg already-reg-float">
        <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="#">Просмотреть</a></p>
    </div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>
<script src="/js/login_ajax.js"></script>