<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <h2 class="c-cnt-pagename helpTitle">Штрафы, предусмотренные КоАП РФ за нарушение законодательства о
                <br>контрактной системе</h2>
            <div class="helpTable">
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf helpTableBox-head">
                    <div class="helpTableBox__item">№№ п/п</div>
                    <div class="helpTableBox__item">Вид нарушения</div>
                    <div class="helpTableBox__item">Статья КоАП</div>
                    <div class="helpTableBox__item">Размер штрафа,
                        руб.</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title">Неправильный выбор способа
                    <br>определения поставщика (подрядчика, исполнителя)</div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">1</div>
                    <div class="helpTableBox__item">Принятие решения о способе определения поставщика (подрядчика, исполнителя) с нарушением требований ФЗ-44</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.29.</div>
                    <div class="helpTableBox__item">30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">2</div>
                    <div class="helpTableBox__item">Принятие решения о проведении конкурса с ограниченным участием, закрытого конкурса с ограниченным участием, двухэтапного конкурса в случаях, не предусмотренных ФЗ-44
                    <br>
                    <br>
                    Нарушение порядка и сроков направления в орган, уполномоченный на осуществление контроля в сфере закупок информации и документов для согласования возможности заключения контракта с единственным поставщиком (подрядчиком, исполнителем)</div>
                    <div class="helpTableBox__item">Часть 2.1 статьи 7.29.</div>
                    <div class="helpTableBox__item">50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title">Нарушение порядка осуществления закупок</div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">4</div>
                    <div class="helpTableBox__item">Включение в план закупок или план-график закупок объекта или объектов закупки, не соответствующих целям осуществления закупок или установленным законодательством РФ требованиям к закупаемым заказчиком товарам, работам, услугам и (или) нормативным затратам, либо включение в план-график закупок начальной (максимальной) цены контракта в отношении которой обоснование отсутствует или не соответствует требованиям</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.29.3</div>
                    <div class="helpTableBox__item">Должностные лица 20 000-50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">5</div>
                    <div class="helpTableBox__item">Несоблюдение порядка или формы обоснования начальной (максимальной) цены контракта, обоснования объекта закупки (за исключением описания объекта закупки)</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.29.3</div>
                    <div class="helpTableBox__item">Должностные лица 10 000</div>
                </div>
            </div>
        </div>
    </div>
</div>