<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <h2 class="c-cnt-pagename helpTitle">Штрафы, предусмотренные КоАП РФ за нарушение законодательства о
                <br>контрактной системе</h2>
            <div class="helpTable">
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf helpTableBox-head">
                    <div class="helpTableBox__item">№№ п/п</div>
                    <div class="helpTableBox__item">Вид нарушения</div>
                    <div class="helpTableBox__item">Статья КоАП</div>
                    <div class="helpTableBox__item">Размер штрафа,
                        руб.</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Неправильный выбор способа
                    <br>определения поставщика (подрядчика, исполнителя)</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">1</div>
                    <div class="helpTableBox__item">Принятие решения о способе определения поставщика (подрядчика, исполнителя) с нарушением требований ФЗ-44</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.29.</div>
                    <div class="helpTableBox__item">30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">2</div>
                    <div class="helpTableBox__item">Выбор иного способа определения поставщика (подрядчика, исполнителя), если определение поставщика (подрядчика, исполнителя) должно осуществляться путем проведения конкурса или аукциона</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.29.</div>
                    <div class="helpTableBox__item">50 000</div>
                </div>		
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">3</div>
                    <div class="helpTableBox__item">Принятие решения о проведении конкурса с ограниченным участием, закрытого конкурса с ограниченным участием, двухэтапного конкурса в случаях, не предусмотренных ФЗ-44
                    <br>
                    <br>
                    Нарушение порядка и сроков направления в орган, уполномоченный на осуществление контроля в сфере закупок информации и документов для согласования возможности заключения контракта с единственным поставщиком (подрядчиком, исполнителем)</div>
                    <div class="helpTableBox__item">Часть 2.1 статьи 7.29.</div>
                    <div class="helpTableBox__item">50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Нарушение порядка осуществления закупок</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">4</div>
                    <div class="helpTableBox__item">Включение в план закупок или план-график закупок объекта или объектов закупки, не соответствующих целям осуществления закупок или установленным законодательством РФ требованиям к закупаемым заказчиком товарам, работам, услугам и (или) нормативным затратам, либо включение в план-график закупок начальной (максимальной) цены контракта в отношении которой обоснование отсутствует или не соответствует требованиям</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.29.3</div>
                    <div class="helpTableBox__item">Должностные лица 20 000-50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">5</div>
                    <div class="helpTableBox__item">Несоблюдение порядка или формы обоснования начальной (максимальной) цены контракта, обоснования объекта закупки (за исключением описания объекта закупки)</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.29.3</div>
                    <div class="helpTableBox__item">Должностные лица 10 000</div>
                </div>
				                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">6</div>
                    <div class="helpTableBox__item">Нарушение порядка или сроков проведения обязательного общественного обсуждения закупок либо непроведение обязательного общественного обсуждения закупок</div>
                    <div class="helpTableBox__item">Часть 3 статьи 7.29.3</div>
                    <div class="helpTableBox__item">Должностные лица 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">7</div>
                    <div class="helpTableBox__item">Нарушение срока утверждения плана закупок, плана-графика закупок (вносимых в эти планы изменений) или срока размещения плана закупок, плана-графика закупок (вносимых в эти планы изменений) в ЕИС</div>
                    <div class="helpTableBox__item">Часть 4 статьи 7.29.3</div>
                    <div class="helpTableBox__item">Должностные лица -5 000-30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">8</div>
                    <div class="helpTableBox__item">Нарушение сроков размещения в единой информационной системе информации и документов, размещение которых предусмотрено ФЗ-44 при проведении конкурса, аукциона, не более чем на два рабочих дня</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица -5 000<br>Юридические лица - 15 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">9</div>
                    <div class="helpTableBox__item">Нарушение сроков размещения в единой информационной системе информации и документов, размещение которых предусмотрено ФЗ-44 при проведении конкурса, аукциона, более чем на два рабочих дня</div>
                    <div class="helpTableBox__item">Часть 1.1 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица - 30 000<br>Юридические лица - 100 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">10</div>
                    <div class="helpTableBox__item">Нарушение сроков размещения в единой информационной системе информации и документов, размещение которых предусмотрено ФЗ-44 при проведении запроса котировок, запроса предложений, осуществлении закупки у единственного поставщика (подрядчика, исполнителя), не более чем на один рабочий день</div>
                    <div class="helpTableBox__item">Часть 1.2 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица - 3 000<br>Юридические лица - 10 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">11</div>
                    <div class="helpTableBox__item">Нарушение сроков размещения в единой информационной системе информации и документов, размещение которых предусмотрено ФЗ-44 при проведении запроса котировок, запроса предложений, осуществлении закупки у единственного поставщика (подрядчика, исполнителя), более чем на один рабочий день</div>
                    <div class="helpTableBox__item">Часть 1.3 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица - 15 000<br>Юридические лица - 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">12</div>
                    <div class="helpTableBox__item">Размещение информации с нарушением требований ФЗ-44<br>Нарушение порядка:
				
					<li>предоставления конкурсной документации или документации об аукционе</li>
					<li>разъяснения положений конкурсной документации или документации об аукционе,</li>
					<li>приема заявок на участие в определении поставщика (подрядчика, исполнителя), окончательных предложений</li></div>
                    <div class="helpTableBox__item">Часть 1.4 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица - 15 000<br>Юридические лица - 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">13</div>
                    <div class="helpTableBox__item">Отклонение по основаниям, не предусмотренным ФЗ-44:<br>
					<li>отклонение заявки на участие в конкурсе,</li>
					<li>отказ в допуске к участию в аукционе,</li>
					<li>признание заявки на участие в закупке не соответствующей требованиям конкурсной документации, документации об аукционе,</li> <li>отстранение участника закупки от участия в конкурсе, аукционе</li>
					<br>
					<br>
					В случае, если участнику, подавшему такую заявку, должно быть отказано в допуске к участию в закупке в соответствии с требованиями ФЗ-44:<br>
					<li>признание заявки на участие в конкурсе надлежащей, соответствующей требованиям конкурсной документации,</li>
					<li>признание заявки на участие в аукционе надлежащей, соответствующей требованиям документации об аукционе,</li>
					<br>
					<br>
					Нарушение порядка:<br>
					<li>вскрытия конвертов с заявками на участие в конкурсе (или) открытия доступа к таким заявкам, поданным в форме электронных документов,</li> 
					<li>рассмотрения и оценки заявок, окончательных предложений участников закупки, установленного конкурсной документацией</li>
					</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.30</div>
                    <div class="helpTableBox__item">1% от начальной (максимальной) цены контракта, но не менее 5 000 и не более 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">14</div>
                    <div class="helpTableBox__item">Нарушение требований к содержанию протокола, составленного в ходе определения поставщика (подрядчика, исполнителя)</div>
                    <div class="helpTableBox__item">Часть 2.1 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 10 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">15</div>
                    <div class="helpTableBox__item">Неразмещение в единой информационной системе в сфере закупок информации и документов, размещение которых предусмотрено в соответствии с ФЗ-44</div>
                    <div class="helpTableBox__item">Часть 3 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица -50 000<br>Юридические лица - 500 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">16</div>
                    <div class="helpTableBox__item">Установление не предусмотренных ФЗ-44:<br>
					<li>порядка рассмотрения и оценки заявок на участие в определении поставщика (подрядчика, исполнителя), окончательных предложений участников закупки,</li>
					<li>требований к участникам закупки,</li>
<li>требований к размеру обеспечения заявок на участие,</li>
<li>требований к размеру и способам обеспечения исполнения контракта,</li>
<li>требования о представлении участниками закупки в составе заявки на участие в определении поставщика (подрядчика, исполнителя) не предусмотренных ФЗ-44 информации и документов</li>					
					</div>
                    <div class="helpTableBox__item">Часть 4 статьи 7.30</div>
                    <div class="helpTableBox__item">1% от начальной (максимальной) цены контракта, но не менее 5 000 и не более 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">17</div>
                    <div class="helpTableBox__item">Включение в описание объекта закупки требований и указаний в отношении товарных знаков, знаков обслуживания, фирменных наименований, патентов, полезных моделей, промышленных образцов, наименования места происхождения товара или наименования производителя, требований к товарам, информации, работам, услугам при условии, если такие требования влекут за собой ограничение количества участников закупки, за исключением случаев, предусмотренных ФЗ-44
					<br>
					<br>
					Включение в состав одного лота, объекта закупки товаров, работ, услуг, технологически и функционально не связанных между собой		</div>
                    <div class="helpTableBox__item">Часть 4.1 статьи 7.30</div>
                    <div class="helpTableBox__item">1% от начальной (максимальной) цены контракта, но не менее 10 000 и не более 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">18</div>
                    <div class="helpTableBox__item">Утверждение конкурсной документации, документации об аукционе, документации о проведении запроса предложений, определение содержания извещения о проведении запроса котировок с нарушением требований, предусмотренных законодательством</div>
                    <div class="helpTableBox__item">Часть 4.2 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 3 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">19</div>
                    <div class="helpTableBox__item">Отклонение заявки на участие в запросе котировок, отказ в допуске к участию в запросе предложений участнику закупки по основаниям, не предусмотренным законодательством
					<br>
					<br>
					Признание заявки на участие в запросе котировок, запросе предложений, окончательного предложения соответствующими требованиям извещения о проведении запроса котировок, документации о проведении запроса предложений в случае, если участнику закупки, подавшему такую заявку, должно быть отказано в допуске к участию в запросе в соответствии с требованиями законодательства
					<br>
					<br>
					Нарушение порядка вскрытия конвертов с заявками на участие в запросе котировок, запросе предложений, с окончательными предложениями и (или) открытия доступа к поданным в форме электронных документов таким заявкам, окончательным предложениям
					<br>
					<br>
					Нарушение порядка рассмотрения и оценки заявок на участие в запросе предложений, окончательных предложений, установленного документацией о проведении запроса предложений</div>
                    <div class="helpTableBox__item">Часть 6 статьи 7.30</div>
                    <div class="helpTableBox__item">5% от начальной (максимальной) цены контракта, но не более 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">20</div>
                    <div class="helpTableBox__item">Признание победителя определения поставщика (подрядчика, исполнителя) с нарушением требований законодательства</div>
                    <div class="helpTableBox__item">Часть 7 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">21</div>
                    <div class="helpTableBox__item">Сокращение сроков подачи заявок в случаях не предусмотренных ФЗ-44
					<br><br>
					Нарушение порядка и сроков отмены определения поставщика (подрядчика, исполнителя)</div>
                    <div class="helpTableBox__item">Часть 8 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">22*</div>
                    <div class="helpTableBox__item">Осуществление закупок у субъектов малого предпринимательства, социально ориентированных некоммерческих организаций в размере менее размера, предусмотренного ФЗ-44
					<br>
					<br>
					Примечания:<br>
					*- Временем совершения административного правонарушения, предусмотренного частью 11 статьи 7.30, является дата окончания календарного года.
					</div>
                    <div class="helpTableBox__item">Часть 11 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">23</div>
                    <div class="helpTableBox__item">Нарушение сроков для подписания протоколов при проведении конкурса, аукциона, запроса котировок, запроса предложений, не более чем на два рабочих дня</div>
                    <div class="helpTableBox__item">Часть 13 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 3 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">24</div>
                    <div class="helpTableBox__item">Нарушение сроков для подписания протоколов при проведении конкурса, аукциона, запроса котировок, запроса предложений, более чем на два рабочих дня</div>
                    <div class="helpTableBox__item">Часть 14 статьи 7.30</div>
                    <div class="helpTableBox__item">Должностные лица 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Нарушение порядка ведения 
                    <br>реестра контрактов, реестра недобросовестных поставщиков</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">25</div>
                    <div class="helpTableBox__item">Включение заведомо недостоверной информации в реестр недобросовестных поставщиков (подрядчиков, исполнителей)</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.31.</div>
                    <div class="helpTableBox__item">Должностные лица –50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">26</div>
                    <div class="helpTableBox__item">Ненаправление, несвоевременное направление в орган, уполномоченный на осуществление контроля в сфере закупок, информации, подлежащей включению в реестр недобросовестных поставщиков (подрядчиков, исполнителей)
					<br><br>
					Непредставление, несвоевременное представление в федеральный орган исполнительной власти, орган исполнительной власти субъекта Российской Федерации, орган местного самоуправления, уполномоченные на ведение реестра контрактов, заключенных заказчиками информации (сведений) и (или) документов, подлежащих включению в такой реестр контрактов, если направление, представление указанных информации (сведений) и (или) документов являются обязательными в соответствии с ФЗ-44
					</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.31.</div>
                    <div class="helpTableBox__item">Должностные лица – 20 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Нарушение сроков возврата обеспечения заявок</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">27</div>
                    <div class="helpTableBox__item">Нарушение порядка и (или) сроков возврата денежных средств, внесенных в качестве обеспечения заявки на участие в определении поставщика (подрядчика, исполнителя), не более чем на три рабочих дня</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.31.1.</div>
                    <div class="helpTableBox__item">Должностные лица - 5 000<br>Юридические лица - 30 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">28</div>
                    <div class="helpTableBox__item">Нарушение порядка и (или) сроков возврата денежных средств, внесенных в качестве обеспечения заявки на участие в определении поставщика (подрядчика, исполнителя), более чем на три рабочих дня</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.31.1.</div>
                    <div class="helpTableBox__item">Должностные лица - 15 000<br>Юридические лица - 90 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Нарушение порядка при заключении, исполнении <br> и изменении контрактов</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">29</div>
                    <div class="helpTableBox__item">Отказ или уклонение поставщика российских вооружения и военной техники, которые не имеют российских аналогов, определенного законодательными актами от заключения государственного контракта по государственному оборонному заказу</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.29.2.</div>
                    <div class="helpTableBox__item">Должностные лица - 30 000 - 50 000<br>Юридические лица - 300 000 - 1000 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">30</div>
                    <div class="helpTableBox__item">Отказ или уклонение поставщика, занимающего в сфере государственного оборонного заказа доминирующее положение, от заключения договора, необходимого для выполнения государственного оборонного заказа, если заключение такого договора является обязательным для указанного лица</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.29.2.</div>
                    <div class="helpTableBox__item">Должностные лица - 30 000 - 50 000<br>Юридические лица - 300 000 - 1000 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">31</div>
                    <div class="helpTableBox__item">Заключение контракта с нарушением объявленных условий определения поставщика (подрядчика, исполнителя) или условий исполнения контракта, предложенных лицом, с которым заключается контракт</div>
                    <div class="helpTableBox__item">Часть 1 статьи 7.32.</div>
                    <div class="helpTableBox__item">Должностные лица - 1% от начальной (максимальной) цены контракта, но не менее 5 000 и не более 30 000<br>Юридические лица - 1% от начальной (максимальной) цены контракта, но не менее 50 000 и не более 300 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">32</div>
                    <div class="helpTableBox__item">Заключение контракта с нарушением объявленных условий определения поставщика (подрядчика, исполнителя) или условий исполнения контракта, предложенных лицом, с которым заключается контракт, если такое нарушение привело к дополнительному расходованию бюджетных средств или уменьшению количества поставляемых товаров, объема выполняемых работ, оказываемых услуг</div>
                    <div class="helpTableBox__item">Часть 2 статьи 7.32.</div>
                    <div class="helpTableBox__item">Двукратный размер дополнительно израсходованных средств или цен товаров, работ, услуг, количество, объем которых уменьшены и которые явились предметом административного правонарушения</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">33</div>
                    <div class="helpTableBox__item">Нарушение сроков заключения контракта или уклонение от заключения контракта</div>
                    <div class="helpTableBox__item">Часть 3 статьи 7.32.</div>
                    <div class="helpTableBox__item">Должностные лица -50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">34</div>
                    <div class="helpTableBox__item">Изменение условий контракта, в том числе увеличение цен товаров, работ, услуг, если возможность изменения условий контракта не предусмотрена ФЗ-44</div>
                    <div class="helpTableBox__item">Часть 4 статьи 7.32.</div>
                    <div class="helpTableBox__item">Должностные лица -20 000<br>Юридические лица - 200 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">35</div>
                    <div class="helpTableBox__item">Изменение условий контракта, в том числе увеличение цен товаров, работ, услуг, если возможность изменения условий контракта не предусмотрена ФЗ-44 и такое изменение привело к дополнительному расходованию бюджетных средств или уменьшению количества поставляемых товаров, объема выполняемых работ, оказываемых услуг</div>
                    <div class="helpTableBox__item">Часть 5 статьи 7.32.</div>
                    <div class="helpTableBox__item">Двукратный размер дополнительно израсходованных средств или цен товаров, работ, услуг, количество, объем которых уменьшены и которые явились предметом административного правонарушения</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">36</div>
                    <div class="helpTableBox__item">Нарушение порядка расторжения контракта в случае одностороннего отказа от исполнения контракта</div>
                    <div class="helpTableBox__item">Часть 6 статьи 7.32.</div>
                    <div class="helpTableBox__item">Должностные лица -50 000<br>Юридические лица - 200 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">37</div>
                    <div class="helpTableBox__item">Несоставление документов о приемке поставленного товара, выполненной работы (ее результатов), оказанной услуги или отдельных этапов поставки товара, выполнения работы, оказания услуги либо ненаправление мотивированного отказа от подписания таких документов в случае отказа от их подписания</div>
                    <div class="helpTableBox__item">Часть 9 статьи 7.32.</div>
                    <div class="helpTableBox__item">Должностные лица -20 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">38</div>
                    <div class="helpTableBox__item">Приемка поставленного товара, выполненной работы (ее результатов), оказанной услуги или отдельного этапа исполнения контракта в случае несоответствия этих товара, работы, услуги либо результатов выполненных работ условиям контракта, если выявленное несоответствие не устранено поставщиком (подрядчиком, исполнителем) и привело к дополнительному расходованию средств соответствующего бюджета бюджетной системы Российской Федерации или уменьшению количества поставляемых товаров, объема выполняемых работ, оказываемых услуг для обеспечения государственных и муниципальных нужд</div>
                    <div class="helpTableBox__item">Часть 10 статьи 7.32.</div>
                    <div class="helpTableBox__item">Должностные лица - 20 000 – 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">39</div>
                    <div class="helpTableBox__item">Нарушение должностным лицом государственного заказчика срока и порядка оплаты товаров (работ, услуг) для государственных нужд по государственному оборонному заказу, в том числе неисполнение обязанности по обеспечению авансирования, предусмотренного государственным контрактом</div>
                    <div class="helpTableBox__item">статья 7.32.1 </div>
                    <div class="helpTableBox__item">Должностные лица - 30 000 – 50 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Нарушения в сфере энергоснабжения и <br>повышения энергетической эффективности</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">40</div>
                    <div class="helpTableBox__item">Осуществление закупок товаров, работ, услуг не соответствующих требованиям их энергетической эффективности</div>
                    <div class="helpTableBox__item">Часть 11 статьи 9.16</div>
                    <div class="helpTableBox__item">Должностное лицо - 30 000<br>Юридические лица - 100 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Невыполнение в срок законного предписания</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">41</div>
                    <div class="helpTableBox__item">Невыполнение в установленный срок законного предписания, требования органа, уполномоченного на осуществление контроля в сфере закупок</div>
                    <div class="helpTableBox__item">Часть 7 статьи 19.15</div>
                    <div class="helpTableBox__item">Должностное лицо заказчика, уполномоченного органа, уполномоченного учреждения, член комиссии
- 50 000<br>Юридические лица - 500 000</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title"><strong>Нарушение порядка и сроков предоставления информации<br>в орган, уполномоченный на осуществление<br> контроля в сфере закупок</strong></div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-shtraf">
                    <div class="helpTableBox__item">42</div>
                    <div class="helpTableBox__item">Непредставление или несвоевременное представление в орган, уполномоченный на осуществление контроля в сфере закупок информации и документов, если представление таких информации и документов является обязательным в соответствии с ФЗ-44, либо представление заведомо недостоверной информации и документов</div>
                    <div class="helpTableBox__item">Cтатьи 19.7.2</div>
                    <div class="helpTableBox__item">Должностные лица - 15 000<br>Юридические лица - 100 000</div>
                </div>
<br><br>
<div>
				<style>
   .text {
    text-align:  center;
   }
  </style>
 </head>
 <body>
  <div class="text">
     <p><b>В соответствии со ст. 2.4 КоАП РФ лица, осуществляющие функции члена комиссии по осуществлению закупок товаров, работ, услуг для обеспечения государственных и муниципальных нужд, контрактные управляющие, работник контрактной службы, совершившие административные правонарушения, предусмотренные статьями 7.29 - 7.32, частями 7, 7.1 статьи 19.5, статьей 19.7.2 настоящего Кодекса, несут административную ответственность как должностные лица </b></p>
  </div>            
			</div>
        </div>
    </div>
</div>