{% if showHeader == true %}
<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="http://{{host}}"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fas-online.ru" class="mh-mail">info@fas-online.ru</a>
        <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
    </div>
</div>
{% endif %}

<div class="content">
    <script type="text/javascript" src="/js/input_mask.js"></script>
    <div class="wrapper">
        <div class="c-content">
            <style>
                .wrap_success{
                    width: 100%;
                    text-align: center;
                    top: 58px;
                    position: absolute;
                }

                .c-m-form input[type="email"] {
                    background: #fff none repeat scroll 0 0;
                    border: 1px solid #d4d7df;
                    border-radius: 2px;
                    float: left;
                    height: 55px;
                    margin: 0 0 30px;
                    padding: 0 10px;
                    width: 100%;
                }
            </style>
            <div class="wrap_success">
                {{ flashSession.output() }}
            </div>

            <div class="c-cnt-pagename">
                Контакты
            </div>

            <div class="c-mapb">
                <script type="text/javascript" charset="utf-8" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=S6PvMetJxzVzDK2kZx6n9rfkbBu45eCR&width=970&height=470&lang=ru_UA&sourceType=constructor"></script>

            </div>            
            <div class="c-m-form">
                <span>Напишите нам</span>
                <form action="/help/sendMailFromContact" method="POST" id="contact-form">
                    <label for="cmf1">Как вас зовут</label>
                    <input type="text" id="cmf1" name="conversion" value="{% if conversion is defined %} {{ conversion }} {% endif %}">
                    <label for="cmf2">Контактный телефон</label>
                    <input type="text" id="cmf2" name="phone" class="phone" value="{% if phone is defined %} {{ phone }} {% endif %}">
                    <label for="cmf3" >E-mail</label>
                    <input type="email" id="cmf3" name="email" value="{% if email is defined %} {{ email }} {% endif %}">
                    <label for="cmf4">Ваше собщение</label>
                    <textarea id="cmf4" name="message"></textarea>
                    <input type="submit" value="Отправить сообщение">
                </form>
            </div>

            <div class="c-m-addr">
                <span>Наш офис</span>
                109097, СанктПетербург, ул. Ильинка, 7<br>
                Skype: Goszakaz<br>
                E-mail: zakupki_uis@roskazna.ru<br>
                Телефон: 7-495-2147529
            </div>


        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $(".phone").mask("+7 (999) 999-9999");
    });
</script>

<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label class="fontNormal" for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
            <span> <a href="#pop-start" class="open_modal" onclick="$('#pop-login').hide()">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a></span>
        </div>
    </form>
    <div class="already-reg already-reg-float">
        <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="#">Просмотреть</a></p>
    </div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>
<script src="/js/login_ajax.js"></script>