<div class="content">
    <div class="wrapper">
        <div class="c-content">
            <div class="c-cnt-pagename">
                Контакты
            </div>

            <div class="c-mapb">
                <script type="text/javascript" charset="utf-8" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=S6PvMetJxzVzDK2kZx6n9rfkbBu45eCR&width=970&height=470&lang=ru_UA&sourceType=constructor"></script>
            </div>

            <div class="c-m-form">
                <span>Напишите нам</span>
                <label for="cmf1">Как вас зовут</label>
                <input type="text" id="cmf1">
                <label for="cmf2">Контактный телефон</label>
                <input type="text" id="cmf2">
                <label for="cmf3">E-mail</label>
                <input type="text" id="cmf3">
                <label for="cmf4">Ваше собщение</label>
                <textarea id="cmf4"></textarea>
                <input type="submit" value="Отправить сообщение">
            </div>

            <div class="c-m-addr">
                <span>Наш офис</span>
                109097, СанктПетербург, ул. Ильинка, 7<br>
                Skype: Goszakaz<br>
                E-mail: zakupki_uis@roskazna.ru<br>
                Телефон: 7-495-2147529
            </div>


        </div>
    </div>
</div>