<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <h2 class="c-cnt-pagename helpTitle">Образцы документов для участника закупки</h2>
            <div class="documents">
                <p class="documents__titleDscr">
                <br></br>
<li><a href="/public/files/шаблон жалобы.docx" target="_blank"  target="_blank" class="helpZakList__link">Шаблон жалобы на закупку по Закону о контрактной системе N 44-ФЗ</a></li>
<li><a href="/public/files/ходатайство о рассмотрении жалобы в отсутствие.docx" target="_blank"  target="_blank" class="helpZakList__link">Ходатайство о рассмотрении жалобы в отсутствие представителя заявителя</a></li>
<li><a href="/public/files/Заявление об отзыве жалобы.docx" target="_blank" class="helpZakList__link">Заявление об отзыве жалобы</a></li>
<li><a href="/public/files/declaraciya.docx" target="_blank" class="helpZakList__link">Декларация о соответсвии участника по ст. 31 ФЗ № 44</a></li>

<p class="pamyatka__titleDscr pamyatka__titleDscr-bottom">Сведения по жалобе и решение по ней Вы можете найти по номеру закупки на официальном сайте ЕИС в данном разделе: <a href="http://www.zakupki.gov.ru/epz/complaint/quicksearch/search.html" target="_blank" class="helpZakList__link">http://www.zakupki.gov.ru/epz/complaint/quicksearch/search.html</p>
        </div>
    </div>
</div>
