<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="#"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fas-online.ru" class="mh-mail">info@fas-online.ru</a>
        <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
    </div>
</div>
<div class="c-fabout">
    <div class="wrapper">
        <div class="c-fabout-t">
            <div class="c-cnt-pagename">
                Инструкция
            </div>
            Для вашего удобства мы создали видео инструкцию, которая подробно<br>
            объясняет принципы работы системы. Спасибо, что вы с нами!
            <div class="faq-macbook">
                <div>video</div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="wrapper">
        <div class="c-content">
            <div class="c-faq-z">
                <span>Пошаговая инструкция</span>
                Если, вдруг, вы не любите видео - специально для вас, у нас есть пошаговая<br>
                инструкция, точно и подробно рассказывающая о нашей системе.
            </div>

            <ul class="c-faq-sp">
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Регистрация и добавление заявителя</span>
                           Зарегистрируйтесь в системе, после чего добавьте заявителя, от которого будет подана жалоба, и выберите его.                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Создайте жалобу</span>
                            Добавьте номер закупки в пустое поле. Система автоматически определит необходимые данные и сформирует шаблон жалобы.
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Добавьте доводы</span>
                            Выберите необходимую категорию в каждом шаге и добавьте довод, касающийся предмета обращения.
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Подпишите и отправьте</span>
                            Подпишите жалобу электронной подписью и нажмите отправить в УФАС. Система гарантированно доставит жалобу в контрольный орган, которому подведомственен Заказчик.
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Отслеживайте статус жалобы</span>
                            Система автоматически отправит Вам уведомление на почту и телефон при изменении статуса Вашей жалобы.
                        </div>
                    </div>
                </li>
            </ul>


        </div>
    </div>
</div>
<!-- popup login -->
<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form action="/login/start" method="post">
        <label for="poplog-inp1">E-mail</label>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label for="poplog-inp2">Пароль</label>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
    </form>
    <div class="modal-close"></div>
</div>
<div id="pop-done" class="modal_div">
    <h2>Начать работу</h2>
    <div class="pop-done-txt">
        На указанную вами электронную почту<br>
        test@test.ru отправлено письмо для завершения<br>
        регистрации
    </div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>