{% if showHeader == true %}
<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="http://fasonline.ru"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fasonline.ru" class="mh-mail">info@fasonline.ru</a>
        <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
    </div>
</div>
<div class="c-fabout">
    <div class="wrapper">
        <div class="c-fabout-t">
            <div class="c-cnt-pagename">
                Инструкция
            </div>
            Для вашего удобства мы создали видео инструкцию, которая подробно<br>
            объясняет принципы работы системы. Спасибо, что вы с нами!
            <div class="faq-macbook">
                <iframe width="715" height="450" src="https://www.youtube.com/embed/n_jg0q-OVZE" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
		 <h2 class="c-cnt-pagename helpTitle">Пошаговая инструкция</h2>
						
            <div class="c-faq-z">
 
                Если, вдруг, вы не любите видео - специально для вас, у нас есть пошаговая<br>
                инструкция, точно и подробно рассказывающая о нашей системе, а также <a href="#ответы">ответы на часто задаваемые вопросы по нашему сервису</a>.     </div>

            <ul class="c-faq-sp">
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                             <b>Регистрация и добавление заявителя</b>
							 <br></br>
                           Зарегистрируйтесь в системе и добавьте одного или нескольких заявителей, от которых планируете подавать жалобы.                </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                             <b>Создайте жалобу</b><br></br>
                            Введите номер закупки, система сама определит необходимые данные и сформирует шаблон жалобы.                       </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                             <b>Добавьте доводы</b><br></br>
                            Воспользуйтесь поиском или мастером подсказок, чтобы найти и добавить доводы, соответствующие предмету вашего обращения.                    </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                             <b>Подпишите и отправьте</b><br></br>
                            Подпишите жалобу электронной подписью прямо в браузере и отправьте ее в УФАС. Система гарантировано доставит ее в надзорный орган.
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                             <b>Отслеживайте статус жалобы</b><br></br>
                           Автоматическое информирование о смене статуса жалобы по email и СМС будет держать в курсе всех событий по вашему обращению.
                        </div>
						 </div>
						 </div>
						<div class="content">
</li>
            </ul>
        <div class="c-content" id="ответы">
            <h2 class="c-cnt-pagename helpTitle">Часто задаваемые вопросы по сервису "ФАС-ОНЛАЙН"</h2>
			<br></br>
            <head>
			<style>  .column {
    -webkit-column-width: 400;
    -moz-column-width: 400;
    column-width: 400;
    -webkit-column-count: 2;
    -moz-column-count: 2;
    column-count: 2;
    -webkit-column-gap: 10px;
    -moz-column-gap: 10px;
    column-gap: 10px;
    font-size: 12pt;
list-style-type: none;
}
          </style>
	    </head>
   <body>
   <div class="column">
	<ul class="helpZakList">
	<li class="pamyatkaList__item"><a href="#1">Как настроить компьютер для пользования системой?</a></li>
						 <li class="pamyatkaList__item""><a href="#2">Как обратиться в службу поддержки?</a></li>
                         <li class="pamyatkaList__item""><a href="#3">Можно ли в кабинете одного пользователя создать нескольких заявителей?</a></li>
                         <li class="pamyatkaList__item""><a href="#4">Как создать жалобу?</a></li>
                         <li class="pamyatkaList__item""><a href="#5">Как найти нужный довод к жалобе?</a></li>
                         <li class="pamyatkaList__item""><a href="#6">Почему система требует добавить довод из определённой категории?</a></li>
                     <li class="pamyatkaList__item"><a href="#7">Почему система предлагает мне направить жалобу в конкретное УФАС?</a></li>
                     <li class="pamyatkaList__item"><a href="#8">Как мне отследить судьбу жалобы?</a></li>
                     <li class="pamyatkaList__item"><a href="#9">Как мне посмотреть жалобы отправленные конкретным заявителем?</a></li>
					 <li class="pamyatkaList__item"><a href="#10">Почему я не могу скопировать несколько жалоб одновременно?</a></li>
					 <li class="pamyatkaList__item"><a href="#11">Как мне отозвать направленную в УФАС жалобу?</a></li>
                     <li class="pamyatkaList__item"><a href="#12">Могу ли я снова подать отозванную жалобу?</a></li>
                     <li class="pamyatkaList__item"><a href="#13">Как задать вопрос юристу сайта?</a></li>
                     <li class="pamyatkaList__item"><a href="#14">Как мне изменить созданную жалобу?</a></li>
                     <li class="pamyatkaList__item"><a href="#15">Как посмотреть поступившие в мой адрес сообщения?</a></li>
                     <li class="pamyatkaList__item"><a href="#16">Как узнать о действующих тарифах по использованию сервиса?</a></li>
                     <li class="pamyatkaList__item"><a href="#17">Если я не буду пользоваться сервисом долгое время сохранится ли мой аккаунт на сервисе и все жалобы?</a></li>
                     <li class="pamyatkaList__item"><a href="#18">Как пользоваться сервисом?</a></li>
					 </ul>
					 </body>
					</div>
					</div>
					
	
			<div class="faqPo__faqQuestionBox faqQuestionBox" id="1">
                    <p class="faqQuestionBox__text">Как настроить компьютер для пользования системой?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text"><li>Для корректной работы используйте браузер <a href="https://www.google.ru/chrome/browser/desktop/">Google Chrome</a> или <a href="https://browser.yandex.ru/desktop/main/">Яндекс браузер</a> либо <a href="https://www.mozilla.org/firefox/new/?scene=2">Mozzila Firefox</a>. Если такой браузер уже установлен, то зайдите в его настройки и убедитесь, что он обновлен до последней версии.</li>
<li>Убедитесь, что плагин <a href="https://www.cryptopro.ru/products/cades/plugin/get_2_0">CryptoPro Extension for CAdES Browser Plug-in</a> добавлен и включен в браузере. Подробная инструкция находится <a href="http://cpdn.cryptopro.ru/content/cades/plugin-installation.html">здесь</a>.</li>
<li>Для добавления заявителя вставьте электронную подпись и нажмите на кнопку <a href="http://fasonline.ru/applicant/add">"Добавить заявителя"</a>. Разрешите требуемую сайтом операцию, нажав на кнопку «Да» и выберите сертификат добавляемого заявителя. Заполните Ваши контактные данные и нажмите на кнопку «Сохранить изменения».</li>
<li>Всё готово, приступайте к <a href="http://fasonline.ru/complaint/add">добавлению жалобы»</a></li></p>
                    </div>
                    
					                <div class="faqPo__faqQuestionBox faqQuestionBox" id="2">
                    <p class="faqQuestionBox__text"> Как обратиться в службу поддержки?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Обратиться в службу поддержки можно следующими способами: 
<li>заполнив соответствующую форму в разделе <a href="http://fasonline.ru/help/contact">«Контакты»</a>.</li>
<li>написать письмо на <a href="mailto:info@fasonline.ru">info@fasonline.ru</a>,</li>
<li>позвонить по номеру: <br><a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a></br></li></p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="3">
                    <p class="faqQuestionBox__text"> Можно ли в кабинете одного пользователя создать нескольких заявителей?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Да, Вы можете создать несколько заявителей разных правовых форм.</p></div>
                    </div>
<div class="faqPo__faqQuestionBox faqQuestionBox" id="4">
                    <p class="faqQuestionBox__text">Как создать жалобу?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
				 <p class="faqDscr__text">После входа в свой аккаунт в верхнем левом углу будет располагаться кнопка <a style="text-decoration:none" href="http://fasonline.ru/complaint/add">«Добавить жалобу»</a>. После чего Вам необходимо выбрать заявителя (если это не было сделано ранее), ввести реестровый номер закупки, выбрать доводы жалобы из предложенных сервисом либо написать довод самостоятельно, прикрепить документы, подтверждающие обоснованность доводов. После совершения данных манипуляций Вы можете, как сохранить жалобу в черновики, так и направить в контрольный орган в сфере закупок.</p></div>
					<div class="faqPo__faqQuestionBox faqQuestionBox" id="5">
                    <p class="faqQuestionBox__text">Как найти нужный довод к жалобе?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">При создании жалобы, после ввода реестрового номера закупки сервис автоматически определит возможные к добавлению категории жалоб, после чего вы сможете осуществить поиск доводов самостоятельно, в зависимости от обстоятельств закупки и оснований жалобы.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="6">
                    <p class="faqQuestionBox__text">Почему система требует добавить довод из определённой категории?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Сервис автоматически определяет этап закупки и характер жалобы в соответствии с требованиями ст. 105 ФЗ-44. Вы должны выбрать один из предлагаемых системой доводов после чего сможете добавлять доводы по своему усмотрению.</p>
                    </div>
					<div class="faqPo__faqQuestionBox faqQuestionBox" id="7">
                    <p class="faqQuestionBox__text">Почему система предлагает мне направить жалобу в конкретное УФАС?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Система автоматически определяет УФАС, в которое направляется жалоба, в зависимости от региона заказчика. Вы вправе самостоятельно изменить орган ФАС на тот, который считаете нужным. Подведомственность регламентируется ч. 17 ст. 105 ФЗ-44, а также ведомственными актами ФАС России.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="8">
                    <p class="faqQuestionBox__text">Как мне отследить судьбу жалобы?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Вы можете отследить судьбу жалобы зайдя в её карточку, а также ориентируясь на статус жалобы, который меняется в зависимости от принятого решения органом ФАС России. Также о смене статуса Вам придет сообщение в личный кабинет, а также на электронную почту и СМС. Если жалоба переведена в архив, то для того чтобы узнать статус данной жалобы ее нужно активировать, нажав на соответствующую кнопку в карточке жалобы.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="9">
                    <p class="faqQuestionBox__text">Как мне посмотреть жалобы отправленные конкретным заявителем?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">На основной странице после входа в систему нажав на вкладку, расположенную сверху «Изменить заявителя» Вы можете выбрать как конкретного одного заявителя, так и нескольких заявителей, чтобы посмотреть список жалоб, направленных ими.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="10">
                    <p class="faqQuestionBox__text">Почему я не могу скопировать несколько жалоб одновременно?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Для целей корректной работы пользователя система позволяет скопировать только одну жалобу.</p>
                    </div>
                   <div class="faqPo__faqQuestionBox faqQuestionBox" id="11">
                    <p class="faqQuestionBox__text">Как мне отозвать направленную в УФАС жалобу?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Для этого Вам необходимо зайти в карточку жалобы и нажать на кнопку «отозвать». При этом отозвать можно только жалобу со статусом «Подана».</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="12">
                    <p class="faqQuestionBox__text">Могу ли я снова подать отозванную жалобу?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Отозванную жалобу нельзя снова направить, но ее можно скопировать и после этого сформировать для отправки. При этом в соответствии с ч. 15 ст. 105 ФЗ-44 лицо, подавшее жалобу, вправе отозвать ее до принятия контрольным органом в сфере закупок решения по существу жалобы, при этом такое лицо не вправе подать жалобу повторно на те же действия (бездействие) тех же лиц.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="13">
                    <p class="faqQuestionBox__text">Как задать вопрос юристу сайта?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Для этого Вам необходимо сформировать жалобу, после чего появится форма для обращения к юристу с вопросом. Когда юрист ответит, Вам придет соответствующее уведомление.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="14">
                    <p class="faqQuestionBox__text">Как мне изменить созданную жалобу?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Для изменения текста жалобы необходимо зайти в ее карточку и нажать на кнопку «редактировать». При этом редактировать возможно только жалобу со статусом «Черновик».</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="15">
                    <p class="faqQuestionBox__text">Как посмотреть поступившие в мой адрес сообщения?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">После входа в свой аккаунт в верхнем правом углу будет располагаться значок в виде конверта, нажав на который Вы увидите непрочитанные сообщения. Если пролистать список сообщений вниз и нажать на кнопку <a style="text-decoration:none" href="http://fasonline.ru/message/index">«Все сообщения»</a> Вы перейдёте в список поступивших сообщений.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="16">
                    <p class="faqQuestionBox__text">Как узнать о действующих тарифах по использованию сервиса?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Перечень действующих тарифов размещён на <a style="text-decoration:none" href="https://fasonline.ru/#₽">главной странице сайта</a>.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="17">
                    <p class="faqQuestionBox__text">Если я не буду пользоваться сервисом долгое время сохранится ли мой аккаунт на сервисе и все жалобы?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text">Доступ в личный кабинет и к созданным жалобам будет сохранен для пользователей вне зависимости от срока, в течение которого не использовался личный кабинет.</p>
                    </div>
                    <div class="faqPo__faqQuestionBox faqQuestionBox" id="18">
                    <p class="faqQuestionBox__text">Как пользоваться сервисом?</p>
                </div>
                <div class="faqPo__faqDscr faqDscr">
                    <p class="faqDscr__text"> В разделе <a style="text-decoration:none" href="http://fasonline.ru/help/faq">«Помощь»</a> размещены материалы по использованию сервиса, а также <a style="text-decoration:none" href="http://fasonline.ru/help/jurisdiction">материалы по вопросам, связанным с контрактной системой</a>.</p>
                    </div>
                   
        </div>
    </div>
</div>

<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label class="fontNormal" for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
              <a href="#pop-start" class="open_modal" onclick="$('#pop-login').hide()">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a> 
        </div>
    </form>
    <div class="already-reg already-reg-float">
        <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="#">Просмотреть</a></p>
    </div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>
<script src="/js/login_ajax.js"></script>

<!-- popup start -->
<div id="pop-start" class="modal_div modal_div-start reg_form">
    <h2>Регистрация</h2>
    <form class="reg-new-user" method="POST">
        <!--        <label for="popstrt-inp1">Ваше имя</label>-->
        <!--        <input type="text" id="popstrt-inp1" required="required" name="name">-->
        <label class="fontNormal" for="popstrt-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="popstrt-inp1" required="required" name="email">
        <!--        <label for="popstrt-inp1">Телефон</label>-->
        <!--        <input type="text" id="popstrt-inp1" required="required" name="phone">-->
        <label class="fontNormal" for="popstrt-inp1">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="password">
        <label class="fontNormal" for="popstrt-inp1">Повторите пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="confpassword">
        <div class="error-reg" style="color:red"></div>
        <div class="g-recaptcha inlineBlock" data-sitekey="6LdzsQkUAAAAABZTg2NJB9EVfnY0VUOPGgm9bhlN"></div>
        <label class="reqReg">
            <input type="checkbox" id="popstrt-inp1" class="reqReg__input" required="required" name="offerta" value="1" checked>
            <a href="http://fasonline.ru/public/files/Пользовательское соглашение без финансовой части.pdf">Принимаю условия оферты</a>
        </label>
        <!--<div class="pop-str1">
            <input type="checkbox" id="popstrt-inp2">
            <label for="popstrt-inp2">Согласен с правилами</label>
           <a href="#">Правила использования сервиса</a>
        </div>-->
        <input class="entryBtn" type="submit" value="Зарегистрироваться">
        <div class="already-reg">
            <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="http://fasonline.ru/public/files/Пользовательское соглашение без финансовой части.pdf">Просмотреть</a></p>
            <p>Уже зарегистрированы – <a href="#pop-login" class="open_modal" onclick="$('#pop-start').hide()">авторизируйтесь</a></p>
        </div>
    </form>

    <div class="modal-close"></div>
</div>

<!-- popup recovery -->
<div id="pop-recovery" class="modal_div modal_div-rec">
    <h2>Восстановление пароля</h2>
    <form class="rec-pass" method="POST">
        <label for="popstrt-inp1">Введите ваш email</label>
        <input type="text" id="popstrt-inp1" required="required" name="email">
        <input type="submit" value="Отправить" style="margin-top: 30px">
    </form>
    <div class="modal-close"></div>
</div>

