{% if showHeader == true %}
<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="http://fas-online.ru"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fas-online.ru" class="mh-mail">info@fas-online.ru</a>
        <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
    </div>
</div>
<div class="c-fabout">
    <div class="wrapper">
        <div class="c-fabout-t">
            <div class="c-cnt-pagename">
                Инструкция
            </div>
            Для вашего удобства мы создали видео инструкцию, которая подробно<br>
            обьясняет принципы работы системы. Спасибо, что вы с нами!
            <div class="faq-macbook">
                <div>video</div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="c-faq-z">
                <span>Пошаговая инструкция</span>
                Если, вдруг, вы не любите видео - специально для вас, у нас есть пошаговая<br>
                инструкция, точно и подробно рассказывающая о нашей системе.
            </div>

            <ul class="c-faq-sp">
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Регистрация</span>
                            Для вашего удобства мы создали видео инструкцию, которая подробно обьясняет принципы работы системы. Спасибо, что вы с нами!
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Добавление заявителя</span>
                            Для вашего удобства мы создали видео инструкцию, которая подробно обьясняет принципы работы системы. Спасибо, что вы с нами!
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Настройка системы</span>
                            Для вашего удобства мы создали видео инструкцию, которая подробно обьясняет принципы работы системы. Спасибо, что вы с нами!
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Добавление жалобы</span>
                            Нажав на кнопку под логотипом вы попадате на страницу добавления жалобы.
                        </div>
                    </div>
                </li>
                <li>
                    <div class="c-faq-sp-t">
                        <div>
                            <span>Введите номер закупки</span>
                            После этого система узнает все данные о закупке и вы сможете продлжить составление жалобы
                        </div>
                    </div>
                </li>
            </ul>


        </div>
    </div>
</div>

<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label class="fontNormal" for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
            <span> <a href="#pop-start" class="open_modal" onclick="$('#pop-login').hide()">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a></span>
        </div>
    </form>
    <div class="already-reg already-reg-float">
        <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="#">Просмотреть</a></p>
    </div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>
<script src="/js/login_ajax.js"></script>

<!-- popup start -->
<div id="pop-start" class="modal_div modal_div-start reg_form">
    <h2>Регистрация</h2>
    <form class="reg-new-user" method="POST">
        <!--        <label for="popstrt-inp1">Ваше имя</label>-->
        <!--        <input type="text" id="popstrt-inp1" required="required" name="name">-->
        <label class="fontNormal" for="popstrt-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="popstrt-inp1" required="required" name="email">
        <!--        <label for="popstrt-inp1">Телефон</label>-->
        <!--        <input type="text" id="popstrt-inp1" required="required" name="phone">-->
        <label class="fontNormal" for="popstrt-inp1">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="password">
        <label class="fontNormal" for="popstrt-inp1">Повторите пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="confpassword">
        <div class="error-reg" style="color:red"></div>
        <div class="g-recaptcha inlineBlock" data-sitekey="6LdzsQkUAAAAABZTg2NJB9EVfnY0VUOPGgm9bhlN"></div>
        <label class="reqReg">
            <input type="checkbox" id="popstrt-inp1" class="reqReg__input" required="required" name="offerta" value="1" checked>
            <a href="#">Принимаю условия оферты</a>
        </label>
        <!--<div class="pop-str1">
            <input type="checkbox" id="popstrt-inp2">
            <label for="popstrt-inp2">Согласен с правилами</label>
           <a href="#">Правила использования сервиса</a>
        </div>-->
        <input class="entryBtn" type="submit" value="Зарегистрироваться">
        <div class="already-reg">
            <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="#">Просмотреть</a></p>
            <p>Уже зарегистрированы – <a href="#pop-login" class="open_modal" onclick="$('#pop-start').hide()">авторизируйтесь</a></p>
        </div>
    </form>

    <div class="modal-close"></div>
</div>

<!-- popup recovery -->
<div id="pop-recovery" class="modal_div modal_div-rec">
    <h2>Восстановление пароля</h2>
    <form class="rec-pass" method="POST">
        <label for="popstrt-inp1">Введите ваш email</label>
        <input type="text" id="popstrt-inp1" required="required" name="email">
        <input type="submit" value="Отправить" style="margin-top: 30px">
    </form>
    <div class="modal-close"></div>
</div>