<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <h2 class="c-cnt-pagename helpTitle">Сроки по процедурам закупок в соответствии с Законом о
                <br>контрактной системе</h2>
            <div class="pamyatka">
                <p class="pamyatka__titleDscr">В действующей редакции Закона о контрактной системе применяются различные формулировки  сроков по процедурам проведения закупок.</p>
                <p class="pamyatka__titleDscr">Поскольку Закон о контрактной системе является частью гражданского законодательства, то к отношениям, которые регламентирует вышеуказанный закон, применяются также положения Гражданского кодекса Российской Федерации (далее – ГК РФ) и соответствующие федеральные законы.</p>
                <div class="pamyatka__pamyatkaDscrBox pamyatkaDscrBox">
                    <p class="pamyatkaDscrBox__pamyatkaListTile">Так, в отношении сроков Закона о контрактной системе применимы следующие положения:</p>
                    <ul class="pamyatkaDscrBox__pamyatkaList pamyatkaList">
                        <li class="pamyatkaList__item">в соответствии со ст. 190 ГК РФ установленный законом, иными правовыми актами, сделкой или назначаемый судом срок определяется календарной датой или истечением периода времени, который исчисляется годами, месяцами, неделями, днями или часами. Срок может определяться также указанием на событие, которое должно неизбежно наступить.</li>
                        <li class="pamyatkaList__item">согласно ст. 191 ГК РФ течение срока, определенного периодом времени, начинается на следующий день после календарной даты или наступления события, которыми определено его начало.</li>
                        <li class="pamyatkaList__item">согласно ст. 193 ГК РФ, если последний день срока приходится на нерабочий день, днем окончания срока считается ближайший следующий за ним рабочий день.</li>
                        <li class="pamyatkaList__item">пунктом 1 статьи 194 ГК РФ, если срок установлен для совершения какого-либо действия, оно может быть выполнено до двадцати четырех часов последнего дня срока. Однако если это действие должно быть совершено в организации, то срок истекает в тот час, когда в этой организации по установленным правилам прекращаются соответствующие операции.</li>
                        <li class="pamyatkaList__item">частью 3 статьи 4 Федерального закона от 03.06.2011 № 107-ФЗ «Об исчислении времени» время календарного дня исчисляется часами, минутами и секундами. За начало календарного дня принимается момент времени, соответствующий 00 часам 00 минутам 00 секундам. За окончание календарного дня принимается момент времени, соответствующий 24 часам 00 минутам 00 секундам.</li>
                    </ul>
                </div>
            </div>
            <div class="helpTable helpTable-minMg">
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-sroki helpTableBox-head">
                    <div class="helpTableBox__item">№№ п/п</div>
                    <div class="helpTableBox__item">Документ</div>
                    <div class="helpTableBox__item">Процедура</div>
                    <div class="helpTableBox__item">Срок по Закону о контрактной системе</div>
                    <div class="helpTableBox__item">Толкование</div>
                    <div class="helpTableBox__item">Статья закона</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title">Открытый конкурс</div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-sroki">
                    <div class="helpTableBox__item">1.1.</div>
                    <div class="helpTableBox__item">Извещение о проведении конкурса. Одновременно с извещением размещается конкурсная документация</div>
                    <div class="helpTableBox__item">Размещение в ЕИС. Дополнительно в любых СМИ.</div>
                    <div class="helpTableBox__item">Не менее чем за 20 дней до даты вскрытия конвертов с заявками на участие в открытом конкурсе или открытия доступа к поданным в форме электронных документов заявкам на участие в открытом конкурсе</div>
                    <div class="helpTableBox__item">Дата размещения извещения и дата вскрытия конвертов в составе 20 дней не считаются. Участники могут подавать заявки до момента вскрытия первого конверта.</div>
                    <div class="helpTableBox__item">Ст. 49, ч.1</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-sroki">
                    <div class="helpTableBox__item">1.2.</div>
                    <div class="helpTableBox__item">Извещение о внесении изменений в извещение о проведении конкурса</div>
                    <div class="helpTableBox__item">Размещение в ЕИС. Дополнительно в любых СМИ.</div>
                    <div class="helpTableBox__item">Не позднее, чем за пять дней до даты окончания срока подачи заявок на участие в открытом конкурсе (не позднее 15-го дня). Срок продлевается так, чтобы с даты размещения изменений до даты окончания срока подачи заявок (или по конкретному лоту) этот срок составлял не менее чем десять рабочих дней.</div>
                    <div class="helpTableBox__item">Если с даты размещения извещения о внесении изменений до даты окончания срока подачи заявок на участие в открытом конкурсе осталось 10 рабочих дней, то продлевать срок подачи заявок</div>
                    <div class="helpTableBox__item">Ст. 49, ч.4</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-sroki">
                    <div class="helpTableBox__item">1.3.</div>
                    <div class="helpTableBox__item">Предоставление конкурсной документации</div>
                    <div class="helpTableBox__item"></div>
                    <div class="helpTableBox__item">В течение двух рабочих дней с даты получения соответствующего заявления в письменном виде (в письменном виде после оплаты, если оплата установлена) или в форме электронного документа).</div>
                    <div class="helpTableBox__item">В течение двух рабочих дней после дня получения запроса</div>
                    <div class="helpTableBox__item">Ст. 50, ч.4</div>
                </div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-title">Конкурс с ограниченным участием</div>
                <div class="helpTable__helpTableBox helpTableBox helpTableBox-sroki">
                    <div class="helpTableBox__item">1.15.</div>
                    <div class="helpTableBox__item">Протокол заседания комиссии по предквалифика- ционному отбору</div>
                    <div class="helpTableBox__item">Проведение заседания комиссии по предквалифи- кационному отбору</div>
                    <div class="helpTableBox__item">В течение не более чем десяти рабочих дней с даты вскрытия конвертов (открытия доступа к поданным в форме электронных документов заявкам). Протокол предквалификационного отбора, размещается в ЕИС в течение трёх рабочих дней с даты подведения результатов предквалифика- ционного отбора.</div>
                    <div class="helpTableBox__item">Дата вскрытия конвертов состав 10 рабочих дней не входит.</div>
                    <div class="helpTableBox__item">Ст. 56, ч.7,8.</div>
                </div>
            </div>
        </div>
    </div>
</div>