<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <h2 class="c-cnt-pagename helpTitle">Законодательство в  
сфере закупок</h2>
            <ul class="helpZakList">
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102164547&intelsearch=44+%F4%E7" target="_blank" class="helpZakList__link">Федеральный закон от 5 апреля 2013 г. N 44-ФЗ "О контрактной системе в сфере  
закупок товаров, работ, услуг для обеспечения государственных и муниципальных нужд"</a>
                </li>
                <li class="helpZakList__item">
                
     <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102149420&intelsearch=223-%D4%C7+%22%CE+%E7%E0%EA%F3%EF%EA%E0%F5+%F2%EE%E2%E0%F0%EE%E2%2C+%F0%E0%E1%EE%F2%2C+%F3%F1%EB%F3%E3+%EE%F2%E4%E5%EB%FC%ED%FB%EC%E8+%E2%E8%E4%E0%EC%E8+%FE%F0%E8%E4%E8%F7%E5%F1%EA%E8%F5+%EB%E8%F6%22" target="_blank"  target="_blank" class="helpZakList__link">Федеральный закон от 18 июля 2011 г. N 223-ФЗ "О закупках товаров, работ, услуг отдельными видами юридических лиц"</a>
         
        </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102108256&intelsearch=%CE+%E7%E0%F9%E8%F2%E5+%EA%EE%ED%EA%F3%F0%E5%ED%F6%E8%E8" target="_blank" class="helpZakList__link">Федеральный закон от 26 июля 2006 г. N 135-ФЗ "О  защите конкуренции"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102146610&intelsearch=%CE%E1+%FD%EB%E5%EA%F2%F0%EE%ED%ED%EE%E9+%EF%EE%E4%EF%E8%F1%E8" target="_blank"   class="helpZakList__link">Федеральный закон от  
6 апреля 2011 г. N 63-ФЗ "Об электронной подписи"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102115928&intelsearch=%CE+%F0%E0%E7%E2%E8%F2%E8%E8+%EC%E0%EB%EE%E3%EE+%E8+%F1%F0%E5%E4%ED%E5%E3%EE+%EF%F0%E5%E4%EF%F0%E8%ED%E8%EC%E0%F2%E5%EB%FC%F1%F2%E2%E0+%E2+%D0%EE%F1%F1%E8%E9%F1%EA%EE%E9+%D4%E5%E4%E5%F0%E0%F6%E8%E8" target="_blank"   target="_blank"   
class="helpZakList__link">Федеральный закон от 24 июля 2007 г. N 209-ФЗ "О развитии малого и среднего предпринимательства в Российской Федерации"</a>
                 
</li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102162473&intelsearch=%CE+%E3%EE%F1%F3%E4%E0%F0%F1%F2%E2%E5%ED%ED%EE%EC+%EE%E1%EE%F0%EE%ED%ED%EE%EC+%E7%E0%EA%E0%E7%E5"   target="_blank"  class="helpZakList__link">Федеральный закон от 29 декабря 2012 г. N 275-ФЗ "О  
государственном оборонном заказе"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102074277&intelsearch=%EA%EE%E4%E5%EA%F1+%EE%E1+%E0%E4%EC%E8%ED%E8%F1%F2%F0%E0%F2%E8%E2%ED%FB%F5" target="_blank"    class="helpZakList__link">Кодекс  
Российской Федерации об административных правонарушениях от 30 декабря 2001 г. N 195-ФЗ</a>
                </li>
                <li class="helpZakList__item">
            
         <a href="http://pravo.gov.ru/proxy/ips/?docbody=&prevDoc=102397804&backlink=1&&nd=102393147"  target="_blank"  class="helpZakList__link">Распоряжение Правительства РФ от 21 марта 2016 г. N 471-р
                    (перечень товаров, работ, услуг, в случае  
осуществления закупок которых заказчик обязан проводить аукцион в электронной форме)
   </a>             </li>
                <li class="helpZakList__item">
               
      <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102386144&intelsearch=%CF%EE%F1%F2%E0%ED%EE%E2%EB%E5%ED%E8%E5+%CF%F0%E0%E2%E8%F2%E5%EB%FC%F1%F2%E2%E0+%D0%D4+%EE%F2+29+%E4%E5%EA%E0%E1%F0%FF+2015+%E3.+N+1457" target="_blank"   class="helpZakList__link">Постановление Правительства РФ от 29 декабря 2015 г. N 1457 "О перечне отдельных видов работ (услуг), выполнение (оказание)  
которых на территории Российской Федерации организациями, находящимися под юрисдикцией Турецкой Республики, а также организациями, контролируемыми гражданами Турецкой  
Республики и (или) организациями, находящимися под юрисдикцией Турецкой Республики, запрещено"</a>
                </li>
                <li class="helpZakList__item">
     
                <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102383215&intelsearch=%CF%EE%F1%F2%E0%ED%EE%E2%EB%E5%ED%E8%E5+%CF%F0%E0%E2%E8%F2%E5%EB%FC%F1%F2%E2%E0+%D0%D4+%EE%F2+30+%ED%EE%FF%E1%F0%FF+2015+%E3.+N+1289+" target="_blank"   class="helpZakList__link">Постановление Правительства РФ от 30 ноября 2015 г. N 1289 "Об ограничениях и условиях допуска происходящих из  
иностранных государств лекарственных препаратов, включенных в перечень жизненно необходимых и важнейших лекарственных препаратов, для целей осуществления закупок для  
обеспечения государственных и муниципальных нужд"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102382688&intelsearch=+%EE%F2+16+%ED%EE%FF%E1%F0%FF+2015+%E3.+N+1236"   target="_blank"  class="helpZakList__link">Постановление Правительства РФ от 16 ноября 2015 г. N 1236 "Об установлении запрета на допуск программного обеспечения, происходящего из  
иностранных государств, для целей осуществления закупок для обеспечения государственных и муниципальных нужд"</a>
                </li>
                <li  
class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102378115&intelsearch=%EE%F2+2+%F1%E5%ED%F2%FF%E1%F0%FF+2015+%E3.+N+927" target="_blank"  class="helpZakList__link">Постановление Правительства РФ от 2 сентября 2015 г. N 927 "Об определении  
требований к закупаемым федеральными государственными органами, органами управления государственными внебюджетными фондами Российской Федерации, их территориальными  
органами и подведомственными им казенными и бюджетными учреждениями отдельным видам товаров, работ, услуг (в том числе предельных цен товаров, работ, услуг)"</a>
         
        </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102378111&intelsearch=%EE%F2+2+%F1%E5%ED%F2%FF%E1%F0%FF+2015+%E3.+N+926" target="_blank"  class="helpZakList__link">Постановление Правительства РФ от 2 сентября 2015  
г. N 926 "Об утверждении Общих правил определения требований к</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102371597&intelsearch=%CF%EE%F1%F2%E0%ED%EE%E2%EB%E5%ED%E8%E5+%CF%F0%E0%E2%E8%F2%E5%EB%FC%F1%F2%E2%E0+%D0%D4+%EE%F2+28+%E0%EF%F0%E5%EB%FF+2015+%E3.+N+407+" target="_blank"   
class="helpZakList__link">Постановление Правительства РФ от 28 апреля 2015 г. N 407 "О порядке определения начальной (максимальной) цены государственного контракта, а  
также цены государственного контракта, заключаемого с единственным поставщиком (подрядчиком, исполнителем), при осуществлении закупок товаров, работ, услуг по  
государственному оборонному заказу"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102367173&intelsearch=%CF%EE%F1%F2%E0%ED%EE%E2%EB%E5%ED%E8%E5+%CF%F0%E0%E2%E8%F2%E5%EB%FC%F1%F2%E2%E0+%D0%D4+%EE%F2+5+%F4%E5%E2%F0%E0%EB%FF+2015+%E3.+N+102" target="_blank"   
class="helpZakList__link">Постановление Правительства РФ от 5 февраля 2015 г. N 102 "Об ограничениях и условиях допуска отдельных видов медицинских изделий,  
происходящих из иностранных государств, для целей осуществления закупок для обеспечения государственных и муниципальных нужд"</a>
                </li>
                 
<li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102367183&intelsearch=%EE%F2+4+%F4%E5%E2%F0%E0%EB%FF+2015+%E3.+N+99" target="_blank"  class="helpZakList__link">Постановление Правительства РФ от 4 февраля 2015 г. N 99 "Об установлении  
дополнительных требований к участникам закупки отдельных видов товаров, работ, услуг, случаев отнесения товаров, работ, услуг к товарам, работам, услугам, которые по  
причине их технической и (или) технологической сложности, инновационного, высокотехнологичного или специализированного характера способны поставить, выполнить, оказать  
только поставщики (подрядчики, исполнители), имеющие необходимый уровень квалификации, а также документов, подтверждающих соответствие участников закупки указанным  
дополнительным требованиям"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102363323&intelsearch=%EE%F2+11+%E4%E5%EA%E0%E1%F0%FF+2014+%E3.+N+1352+" target="_blank"   
class="helpZakList__link">Постановление Правительства РФ от 11 декабря 2014 г. N 1352 "Об особенностях участия субъектов малого и среднего предпринимательства в  
закупках товаров, работ, услуг отдельными видами юридических лиц"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102357331&intelsearch=%CF%EE%F1%F2%E0%ED%EE%E2%EB%E5%ED%E8%E5+%CF%F0%E0%E2%E8%F2%E5%EB%FC%F1%F2%E2%E0+%D0%D4+%EE%F2+11+%E0%E2%E3%F3%F1%F2%E0+2014+%E3.+N+791" target="_blank"   
class="helpZakList__link">Постановление Правительства РФ от 11 августа 2014 г. N 791 "Об установлении запрета на допуск товаров легкой промышленности, происходящих из  
иностранных государств, и (или) услуг по прокату таких товаров в целях осуществления закупок для обеспечения федеральных нужд, нужд субъектов Российской Федерации и  
муниципальных нужд"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102355485&intelsearch=%EE%F2+14+%E8%FE%EB%FF+2014+%E3.+N+649" target="_blank"  class="helpZakList__link">Постановление  
Правительства РФ от 14 июля 2014 г. N 649 "О порядке предоставления учреждениям и предприятиям уголовно-исполнительной системы преимуществ в отношении предлагаемой ими  
цены контракта"</a>
                </li>
                <li class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102169429&intelsearch=%EE%F2+28+%ED%EE%FF%E1%F0%FF+2013+%E3.+N+1088" target="_blank"  class="helpZakList__link">Постановление  
Правительства РФ от 28 ноября 2013 г. N 1088 "Об утверждении Правил проведения совместных конкурсов и аукционов"</a>
                </li>
                <li  
class="helpZakList__item">
                    <a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102168930&intelsearch=%EE%F2+8+%ED%EE%FF%E1%F0%FF+2013+%E3.+N+1005" target="_blank"  class="helpZakList__link">Постановление Правительства РФ от 8 ноября 2013 г. N 1005 "О банковских гарантиях,  
используемых для целей Федерального закона "О контрактной системе в сфере закупок товаров, работ, услуг для обеспечения государственных и муниципальных нужд"</a>
         
        </li>
            </ul>
        </div>
    </div>
</div>
