<div class="cfooter">
    <div class="wrapper {% if user is defined %}wrap-with-menuPanel{% endif %}">
        <div class="cflogo">
            <a href="/complaint/index"></a>
        </div>
        <div class="cf-str">
            &copy; ФАС-Онлайн, 2016, при поддержке «Госпартнер»
            <a href="/help/contact">Контакты</a>
            <a href="/help/faq">Помощь</a>
            <a href="/help/about">О проекте</a>
        </div>
    </div>
</div>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter41558219 = new Ya.Metrika({
                    id:41558219,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/41558219" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->