<div class="cfooter">
    <div class="wrapper {% if user is defined %}wrap-with-menuPanel{% endif %}">
        <div class="cflogo">
            <a href="/complaint/index"></a>
        </div>
        <div class="cf-str">
            &copy; ФАС-Онлайн, 2016, при поддержке «Госпартнер»
            <a href="/help/contact">Контакты</a>
            <a href="/help/faq">Помощь</a>
            <a href="/help/about">О проекте</a>
        </div>
    </div>
</div>