<div id="sidr">
    <div class="lm-logo"></div>
    <div class="lm-btn">
        <a href="/complaint/add">добавить жалобу</a>
    </div>
    <ul class="lm-nav">
        <li>
            <a href="#">
                ВСЕ
                <span>34</span>
            </a>
        </li>
        <li>
            <a href="#">
                Черновики
            </a>
        </li>
        <li>
            <a href="#">
                Поданные
                <span>1</span>
            </a>
        </li>
        <li>
            <a href="#">
                На рассмотрении
            </a>
        </li>
        <li>
            <a href="#">
                Обоснованные
                <span>2</span>
            </a>
        </li>
        <li>
            <a href="#">
                Необоснованные
            </a>
        </li>
        <li>
            <a href="#">
                Отозванные
                <span>1</span>
            </a>
        </li>
        <li>
            <a href="#">
                Архив
            </a>
        </li>
    </ul>
    <div class="lm-cont">
        <div class="lm-c-b1">8 (800) 100-93-86</div>
        <div class="lm-c-b2">info@fas-online.ru</div>
    </div>
    <div class="lm-gospart"></div>
</div>
<a id="leftmenu" href="#sidr" class="lm-callbtn">МЕНЮ</a>

<div class="c-header">
    <div class="wrapper">
        <div class="ch-left">
            <b class="applicant-name-container"></b>
            <span>Изменить Заявителя</span>
        </div>

        <div class="ch-l-dd">
            <div  class="ch-left-cl">
                <b class="applicant-name-container"></b>
                <span>Закрыть и сохранить</span>
            </div>
            <div class="ch-l-info">
                <div class="ch-l-i-btn">
                    <a href="/applicant/add">добавить заявителя</a>
                </div>
                <ul>
                   {% for applicant in applicants  %}
                    {% if loop.first %}
                    <script>
                        var applicantFirstId = {{ applicant.id}};
                    </script>
                    {% endif %}
                    <li>
                        <input id="cl{{ applicant.id}}" type="checkbox" name="cl{{ applicant.id}}" hidden>
                        <label class="select_applicant" id="name_applicant_{{applicant.id}}" value="{{ applicant.id}}" for="cl{{ applicant.id}}">{{ applicant.name_short}}</label>
                        <div class="ch-l-i-edit">
                            <a href="/applicant/edit/{{ applicant.id}}">редактировать</a>
                            <a href="/applicant/delete/{{ applicant.id}}">удалить</a>
                        </div>
                    </li>

                   {% endfor %}
                 <!--   <li>
                        <input id="cl2" type="checkbox" name="cl2" hidden>
                        <label for="cl2">Степашин С.В.</label>
                        <div class="ch-l-i-edit">
                            <a href="#">редактировать</a>
                            <a href="#">удалить</a>
                        </div>
                    </li>
                    <li>
                        <input id="cl3" type="checkbox" name="cl3" checked hidden>
                        <label for="cl3">ООО «Проектирование автоматизированных регулируемых управляющих систем»</label>
                        <div class="ch-l-i-edit">
                            <a href="#">редактировать</a>
                            <a href="#">удалить</a>
                        </div>
                    </li>
                    -->
                </ul>
            </div>
        </div>

        <div class="ch-right">
            <div class="ch-r-name">
                Vladimir.leonov@gmail.com
            </div>
            <div class="ch-r-mail">
                <span>5</span>
            </div>
            <div class="ch-r-sett"></div>
            <div class="ch-r-logout"></div>

            <!-- Ниже всплывающее окно сообщений (закомментировано) -->

            <!--<div class="ch-r-notif-dd">
                <div class="ch-r-notif-dd-t">
                    Статус вашей жалобы на заявку № 16473856438 изменен на «Обоснована»
                </div>
                <div class="ch-r-notif-dd-all">
                    <a href="#">Все сообщения</a>
                </div>
            </div>-->

            <div class="ch-r-sett-dd">
                <div class="ch-r-sett-dd-z">
                    НАстройки пользователя
                </div>
                <div class="ch-r-s-inf">
                    <div class="ch-r-s-i-usr">
                        Добро пожаловать<br>
                        Vladimir.leonov@gmail.com
                    </div>
                    <div class="ch-r-s-i-mail">
                        <input id="cr1" type="checkbox" name="cr1" hidden>
                        <label for="cr1">Получать уведомления на e-mail</label>
                    </div>
                    <div class="ch-r-s-inf-f">
                        <span>Сменить пароль</span>
                        <label for="usri1">Старый пароль</label>
                        <input type="text" id="usri1">
                        <label for="usri2">Новый пароль</label>
                        <input type="text" id="usri2">
                        <label for="usri3">Новый пароль еще раз</label>
                        <input type="text" id="usri3">
                        <input type="submit" value="Сменить пароль">
                    </div>
                </div>
            </div>

            <div class="ch-r-mail-dd">
                <div class="ch-r-mail-dd-z">
                    Сообщения
                    <span>5</span>
                </div>
                <div class="ch-r-m-text mCustomScrollbar">
                    <ul class="ch-r-m-list">
                        <li class="done">
                            Статус вашей жалобы на заявку №16473856438 изменен на «Обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="notdone">
                            Статус вашей жалобы на заявку №23872046237 изменен на «Не обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="rassmotr">
                            Статус вашей жалобы на заявку №16473856438 изменен на «Обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="system">
                            Системное сообщение, об изменнии порядка добавления жалобы в УФАС. Срочно! Прочитайте внимательно!
                            <a href="#">Перейти</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="done">
                            Статус вашей жалобы на заявку №16473856438 изменен на «Обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->getContent(); ?>