<div class="left-menu-block">
    <div class="left-menu-holder">
        <div class="lm-opcl-btnb">
            <div class="lm-opcl-btn1"></div>
            <div class="lm-opcl-btn2"></div>
        </div>
        <div class="lm-logo"></div>
        <div class="lm-btn">
            <a href="/complaint/add">добавить жалобу</a>
        </div>
        <ul class="lm-nav">
            <li>
                <a class="{% if menu_status == 'all' %} lm-link-active {% endif %}"  href="/complaint/index">
                    ВСЕ
                    <span>{{ total }}</span>
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'draft' %} lm-link-active {% endif %}" href="/complaint/index?status=draft">
                    Черновики
                    {% if complaints_num['draft'] is defined %}
                    <span>{{ complaints_num['draft'] }}</span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'submitted' %} lm-link-active {% endif %}" href="/complaint/index?status=submitted">
                    Поданные
                    {% if complaints_num['submitted'] is defined %}
                    <span>{{ complaints_num['submitted'] }}</span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'under_consideration' %} lm-link-active {% endif %}" href="/complaint/index?status=under_consideration">
                    На рассмотрении
                    {% if complaints_num['under_consideration'] is defined %}
                    <span>{{ complaints_num['under_consideration'] }}</span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'justified' %} lm-link-active {% endif %}" href="/complaint/index?status=justified">
                    Обоснованные
                    {% if complaints_num['justified'] is defined %}
                    <span>{{ complaints_num['justified'] }}</span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'unfounded' %} lm-link-active {% endif %}" href="/complaint/index?status=unfounded">
                    Необоснованные
                    {% if complaints_num['unfounded'] is defined %}
                    <span>{{ complaints_num['unfounded'] }}</span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'recalled' %} lm-link-active {% endif %}" href="/complaint/index?status=recalled">
                    Отозванные
                    {% if complaints_num['recalled'] is defined %}
                    <span>{{ complaints_num['recalled'] }}</span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a class="{% if menu_status == 'archive' %} lm-link-active {% endif %}" href="/complaint/index?status=archive">
                    Архив
                    {% if complaints_num['archive'] is defined %}
                    <span>{{ complaints_num['archive'] }}</span>
                    {% endif %}
                </a>
            </li>
        </ul>
        <div class="lm-cont">
            <div class="lm-c-b1">8 (800) 100-93-86</div>
            <div class="lm-c-b2">info@fas-online.ru</div>
        </div>
        <div class="lm-gospart"></div>
    </div>
</div>


<div class="c-header">
    <div class="wrapper">
        <div class="ch-left">
            <b class="applicant-name-container"></b>
            <span>Изменить Заявителя</span>
        </div>

        <div class="ch-l-dd">
            <div  class="ch-left-cl">
                <b class="applicant-name-container"></b>
                <span>Закрыть и сохранить</span>
            </div>
            <div class="ch-l-info">
                <div class="ch-l-i-btn">
                    <a href="/applicant/add">добавить заявителя</a>
                </div>
                <ul class="mCustomScrollbar">
                   {% for applicant in applicants  %}
                    {% if loop.first %}
                    <script>
                        {% if selected_applicant_id is defined %}
                         var applicantSelectedId = '{{selected_applicant_id}}';
                        {% else %}
                          var applicantFirstId = {{ applicant.id}};
                        {% endif %}
                    </script>
                     {% if index_action is defined %}
                        <input id="clAll" type="checkbox" name="clAll" hidden>
                        <label class="select_applicant" id="name_applicant_All" value="All" for="clAll">Все</label>
                     {% endif %}
                    {% endif %}
                    <li>
                        <input id="cl{{ applicant.id}}" type="checkbox" name="cl{{ applicant.id}}" hidden>
                        <label class="select_applicant" id="name_applicant_{{applicant.id}}" value="{{ applicant.id}}" for="cl{{ applicant.id}}">
                           {% if applicant.type == 'urlico' %}
                            {{ applicant.name_short}}
                           {% endif %}
                            {% if applicant.type == 'ip' %}
                            {{ applicant.name_full}}
                            {% endif %}
                            {% if applicant.type == 'fizlico' %}
                            {{ applicant.fio_applicant}}
                            {% endif %}
                        </label>
                        <div class="ch-l-i-edit">
                            <a href="/applicant/edit/{{ applicant.id}}">редактировать</a>
                            <a href="/applicant/delete/{{ applicant.id}}">удалить</a>
                        </div>
                    </li>

                   {% endfor %}

                </ul>
            </div>
        </div>

        <div class="ch-right">
            <div class="ch-r-name">
                {{ user.email }}
            </div>
            <div class="ch-r-mail">
                <span>5</span>
            </div>
            <div class="ch-r-sett"></div>
            <div class="ch-r-logout"></div>

            <!-- Ниже всплывающее окно сообщений (закомментировано) -->

            <!--<div class="ch-r-notif-dd">
                <div class="ch-r-notif-dd-t">
                    Статус вашей жалобы на заявку № 16473856438 изменен на «Обоснована»
                </div>
                <div class="ch-r-notif-dd-all">
                    <a href="#">Все сообщения</a>
                </div>
            </div>-->

            <div class="ch-r-sett-dd">
                <div class="ch-r-sett-dd-z">
                    Настройки пользователя
                </div>
                <div class="ch-r-s-inf">
                    <div class="ch-r-s-i-usr">
                        Добро пожаловать<br>
                        Vladimir.leonov@gmail.com
                    </div>
                    <div class="ch-r-s-i-mail">
                        <input id="cr1" type="checkbox" name="cr1" hidden>
                        <label for="cr1">Получать уведомления на e-mail</label>
                    </div>
                    <div class="ch-r-s-inf-f">
                        <span>Сменить пароль</span>
                        <label for="usri1">Старый пароль</label>
                        <input type="text" id="usri1">
                        <label for="usri2">Новый пароль</label>
                        <input type="text" id="usri2">
                        <label for="usri3">Новый пароль еще раз</label>
                        <input type="text" id="usri3">
                        <input type="submit" value="Сменить пароль">
                    </div>
                </div>
            </div>

            <div class="ch-r-mail-dd">
                <div class="ch-r-mail-dd-z">
                    Сообщения
                    <span>5</span>
                </div>
                <div class="ch-r-m-text mCustomScrollbar">
                    <ul class="ch-r-m-list">
                        <li class="done">
                            Статус вашей жалобы на заявку №16473856438 изменен на «Обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="notdone">
                            Статус вашей жалобы на заявку №23872046237 изменен на «Не обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="rassmotr">
                            Статус вашей жалобы на заявку №16473856438 изменен на «Обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="system">
                            Системное сообщение, об изменнии порядка добавления жалобы в УФАС. Срочно! Прочитайте внимательно!
                            <a href="#">Перейти</a>
                            <span>6 января 2016</span>
                        </li>
                        <li class="done">
                            Статус вашей жалобы на заявку №16473856438 изменен на «Обоснована»
                            <a href="#">Перейти к жалобе</a>
                            <span>6 января 2016</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->getContent(); ?>