<div class="left-menu-block">
    <div class="left-menu-holder scroll-pane">
        <div class="lm-opcl-btnb">
            <div class="lm-opcl-btn1"></div>
            <div class="lm-opcl-btn2"></div>
        </div>
        <a href="/complaint/index" style="display: block"><div class="lm-logo"></div></a>
        <div class="lm-btn">
            <a href="/complaint/add">добавить жалобу</a>
        </div>
        <ul class="lm-nav">
            {% if help is defined %}
                {% for name, link in sidebarMenu %}
                    <li>
                        <a class="help_link"  href="{{ link }}">
                            {{ name }}
                        </a>
                    </li>
                {% endfor %}
            {% else %}
                <li>
                    <a class="{% if menu_status == 'all' %} lm-link-active {% endif %} "  href="/complaint/index">
                        ВСЕ
                        <span class="menu-status-all">{{ total }}</span>
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'draft' %} lm-link-active {% endif %} " href="/complaint/index?status=draft">
                        Черновики
                        {% if complaints_num['draft'] is defined %}
                        <span class="menu-status-draft">{{ complaints_num['draft'] }}</span>
                        {% endif %}
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'submitted' %} lm-link-active {% endif %}" href="/complaint/index?status=submitted">
                        Поданные
                        {% if complaints_num['submitted'] is defined %}
                        <span>{{ complaints_num['submitted'] }}</span>
                        {% endif %}
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'under_consideration' %} lm-link-active {% endif %}" href="/complaint/index?status=under_consideration">
                        На рассмотрении
                        {% if complaints_num['under_consideration'] is defined %}
                        <span>{{ complaints_num['under_consideration'] }}</span>
                        {% endif %}
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'justified' %} lm-link-active {% endif %}" href="/complaint/index?status=justified">
                        Обоснованные
                        {% if complaints_num['justified'] is defined %}
                        <span>{{ complaints_num['justified'] }}</span>
                        {% endif %}
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'unfounded' %} lm-link-active {% endif %}" href="/complaint/index?status=unfounded">
                        Необоснованные
                        {% if complaints_num['unfounded'] is defined %}
                        <span>{{ complaints_num['unfounded'] }}</span>
                        {% endif %}
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'recalled' %} lm-link-active {% endif %}" href="/complaint/index?status=recalled">
                        Отозванные
                        {% if complaints_num['recalled'] is defined %}
                        <span>{{ complaints_num['recalled'] }}</span>
                        {% endif %}
                    </a>
                </li>
                <li>
                    <a class="{% if menu_status == 'archive' %} lm-link-active {% endif %}" href="/complaint/index?status=archive">
                        Архив
                        {% if complaints_num['archive'] is defined %}
                        <span>{{ complaints_num['archive'] }}</span>
                        {% endif %}
                    </a>
                </li>
            {% endif %}
        </ul>
        <div class="lm-search-title">
            <p>Поиск по выбранному</p>
        </div>
        <div class="lm-search-box search-complaint">
            {% if searchurl is defined %}
            <form action="{{searchurl}}" method="GET">
                <input type="text" id="lm-search-field" class="searc_val" name="search">
                <input type="submit" id="lm-search-btn"  class="searc_comp" value="">
            </form>
            {% endif %}
        </div>
        <div class="lm-cont">
            <div class="lm-c-b1"><a href="tel:8 (800) 100-93-86" style="color:white">8 (800) 100-93-86</a></div>
            <div class="lm-c-b2"><a href="mailto:info@fas-online.ru" style="color:white">info@fas-online.ru</a></div>
        </div>
        <div class="lm-gospart"></div>
    </div>
</div>
<script>
    //  if ($(window).height() <= 860) {
    // $('.left-menu-holder').addClass('scroll-pane');
    $('.scroll-pane').jScrollPane();
    // }
</script>
<div class="opacity-layer"></div>

<div class="c-header">
    <div class="wrapper marginLeftWrapper">
        <div class="ch-left">
            <b class="applicant-name-container"></b>
            <span>Изменить Заявителя</span>
        </div>
        <div class="session_message">
            {{flashSession.output()}}
        </div>
        <div class="ch-l-dd">
            <div  class="ch-left-cl">
                <b class="applicant-name-container"></b>
                <span>Закрыть и сохранить</span>
            </div>
            <div class="ch-l-info">
                <div class="ch-l-i-btn">
                    <a href="/applicant/add">добавить заявителя</a>
                </div>
                <ul class="mCustomScrollbar">
                    {% for applicant in applicants  %}
                    {% if loop.first %}
                    <script>
                        {% if applicant_session is defined %}
                        var applicantSelectedId = '{{applicant_session}}';
                        {% endif %}
                    </script>
                    {% endif %}
                    <li>
                        <input id="cl{{ applicant.id}}" type="checkbox" name="cl{{ applicant.id}}" hidden>
                        <label class="select_applicant" id="name_applicant_{{applicant.id}}" value="{{ applicant.id}}" for="cl{{ applicant.id}}">
                            {% if applicant.type == 'urlico' %}
                            {{ applicant.name_short}}
                            {% endif %}
                            {% if applicant.type == 'ip' %}
                            {{ applicant.name_full}}
                            {% endif %}
                            {% if applicant.type == 'fizlico' %}
                            {{ applicant.fio_applicant}}
                            {% endif %}
                        </label>
                        <div class="ch-l-i-edit">
                            <a href="/applicant/edit/{{ applicant.id}}">редактировать</a>
                            <!--<a href="/applicant/delete/{{ applicant.id}}">удалить</a>-->
                            <a href="#pop-confirm-delete-applicant-front" applicant-id="{{ applicant.id}}" class="open_modal2">удалить</a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id="pop-confirm-delete-applicant-front" class="modal_div">
            <h2>Удаление заявителя</h2>
            <div class="pop-done-txt">
                Вы действительно хотите удалить заявителя</br>
                <div id="applicant-name"></div>
                <div class="action-buttons">
                    <div class="popup-button cnc popup-close">Отменить</div>
                    <a class="delete-applicant" href=""><div class="popup-button apr">Удалить</div></a>
                    <div style="clear: both;"></div>
                </div>
            </div>
            <div class="modal-close"></div>
        </div>

        <div class="ch-right">
            <div class="ch-r-name">
                {{ user.email }}
            </div>
            <div class="ch-r-mail">
                <span>{% if count_unread %} {{count_unread}} {% else %} 0 {% endif %}</span>
            </div>
            <div class="ch-r-sett"></div>
            <a href="/login/logout" class="ch-r-logout"></a>

            <!-- Ниже всплывающее окно сообщений (закомментировано) -->

            <!--<div class="ch-r-notif-dd">
                <div class="ch-r-notif-dd-t">
                    Статус вашей жалобы на заявку № 16473856438 изменен на «Обоснована»
                </div>
                <div class="ch-r-notif-dd-all">
                    <a href="#">Все сообщения</a>
                </div>
            </div>-->

            <div class="ch-r-sett-dd">
                <div class="ch-r-sett-dd-z">
                    Настройки пользователя
                </div>
                <div class="ch-r-s-inf">
                    <form method="POST" id="edit-user">
                        <div class="ch-r-s-i-usr">
                            Добро пожаловать<br>
                            {{ user.email }}
                        </div>
                        <div class="ch-r-s-i-mail">
                            <input id="cr1" type="checkbox" name="notifications" hidden  {% if user.notifications == 1%} checked  {% endif %}  value="1"  >
                            <label for="cr1">Получать уведомления на e-mail</label>
                        </div>
                        <div class="ch-r-s-inf-f userData" style="font-weight: normal">
                            <p>Личные данные</p>
<!--                            <label for="adm-set-name" class="set-same-lable">-->
<!--                                <p>Имя</p>-->
<!--                                <div class="c-inp-err-t c-inp-err-t-minMrgTop"></div>-->
<!--                                <input type="text" id="usri1" name="firstname" required value="{{user.firstname}}">-->
<!--                            </label>-->
<!--                            <label for="adm-set-name" class="set-same-lable" >-->
<!--                                <p>Фамилия</p>-->
<!--                                <div class="c-inp-err-t c-inp-err-t-minMrgTop"></div>-->
<!--                                <input type="text" id="usri1" name="lastname" required value="{{user.lastname}}">-->
<!--                            </label>-->
<!--                            <label for="adm-set-name" class="set-same-lable">-->
<!--                                <p>Отчество</p>-->
<!--                                <div class="c-inp-err-t c-inp-err-t-minMrgTop"></div>-->
<!--                                <input type="text" id="usri1" name="patronymic" required value="{{user.patronymic}}">-->
<!--                            </label>-->
                            <label for="adm-set-name" class="set-same-lable">
                                <p>Как к вам обращаться?</p>
                                <div class="c-inp-err-t c-inp-err-t-minMrgTop"></div>
                                <input type="text" id="usri1" name="conversion" required value="{{user.conversion}}">
                            </label>
                            <label for="adm-set-name" class="set-same-lable">
                                <p>Телефон</p>
                                <div class="c-inp-err-t c-inp-err-t-minMrgTop"></div>
                                <input type="text" id="usri1" name="phone" required value="{{user.phone}}">
                            </label>
                            <label for="adm-set-name" class="set-same-lable">
                                <p>Мобильный телефон</p>
                                <div class="c-inp-err-t c-inp-err-t-minMrgTop"></div>
                                <input type="text" id="usri1" name="mobile_phone" required value="{{user.mobile_phone}}">
                            </label>
                        </div>
                        <div class="ch-r-s-inf-f userData" >
                            <span>Сменить пароль</span>
                            <label for="usri1">Старый пароль</label>
                            <input type="password" id="usri1" name="old_password">
                            <label for="usri2">Новый пароль</label>
                            <input type="password" id="usri2" name="new_password">
                            <label for="usri3">Новый пароль еще раз</label>
                            <input type="password" id="usri3" name="new_password_confirm">
                            <input type="submit" value="Сохранить">
                            <input type="hidden" id="current_path" name="current_path" value="">
                        </div>
                    </form>
                </div>
            </div>

            <div class="ch-r-mail-dd">
                <div class="ch-r-mail-dd-z">
                    Сообщения
                    <span>{% if count_unread %} {{count_unread}} {% else %} 0 {% endif %}</span>
                </div>
                <div class="ch-r-m-text">
                    <ul class="ch-r-m-list">
                    {% for message in messages %}
                        {% if(message['status_change'] == true) %}
                        {% if message['complaint_id'] is defined %}<a href="/complaint/edit/{{message['complaint_id']}}">{% endif %}
                            <li class="{{ message['color'] }}">
                                Статус вашей жалобы {% if message['auction_id'] is defined %}на заявку №{{message['auction_id']}} {% endif %}изменен на «{{message['status']}}»
                                <span>{{ date('d F Y', message['time']) }}</span>
                            </li>
                        {% if message['complaint_id'] is defined %}</a>{% endif %}
                        {% else %}
                        <a href="/complaint/edit/{{message['comp_id']}}">
                            <li class=" box-status-black ">
                                {{ message['body'] }}
                                <span>{{ date('d F Y', message['time']) }}</span>
                            </li>
                        </a>
                        {% endif %}
                    {% endfor %}
                        <li class="all-message-link" onclick="window.location.href='/message/index';">
                            Все сообщения
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<div class="modal fade modal-message-detail" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">-->
<!--<div class="modal-dialog modal-lg redesignBootstrapPopup">-->
<!--<div class="modal-content">-->
<!--<div class="modal-header">-->
<!--<h4 class="modal-title">Просмотр сообщения</h4>-->
<!--</div>-->
<!--<div class="modal-body">-->
<!--<form>-->
<!--<div class="form-group">-->
<!--<textarea disabled="disabled" style="min-height: 220px;" class="form-control" id="message-text" value=""></textarea>-->
<!--</div>-->
<!--</form>-->
<!--</div>-->
<!--<div class="modal-footer">-->
<!--<button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<div id="overlay"></div>

<article class="admin-popup-wrap showDopMessPopup">
    <div class="admin-popup-bg"></div>
    <div class="admin-popup-content">
        <div class="admin-popup-close"></div>
        <h6>Просмотр сообщения</h6>
        <p id="message-textNew"></p>
        <div class="wrap-button">
            <a class="btn-div show-complaint" href="">Перейти к жалобе</a>
            <div class="closeBtnMessage btn-div">Закрыть</div>
        </div>
    </div>
</article>
<style>
    .wrap-button{
        display: inline-block;
        float: right;
        margin: 30px 40px 30px 0;
    }
    .wrap-button div {
        margin-left: 20px;
    }
    .show-complaint{
        display: inline-block;
        color: #fff;
        text-decoration: none;
    }
    .show-complaint:hover{
        text-decoration: none;
        color: #fff;
        font-size: 16px;
        line-height: 50px;
        font-weight: 600;
    }
    .closeBtnMessage{
        margin: 0px;
    }
    .lm-search-title {
        font-size: 1px;
        padding: 1px 0 16px 22px;
    }
    .lm-search-title p{
        color: #222427;
    }
</style>
<script type="text/javascript">
    $(document).ready(function(){
        $("#current_path").val(window.location.pathname);
        $('#adminMessagePopup').click(function() {
//            $('#message-text').val($(this).parent().find('#message_body').val())
            $('#message-textNew').text($(this).parent().find('#message_body').val());
//            $('.modal-message-detail').modal('show');
            $('.showDopMessPopup').fadeIn(400).css('display', 'flex');
            setMessageRed($(this).parent().find('#message_id').val());
            $(this).parent().remove();
            var cnt_m1 = +($('.ch-r-mail-dd-z span').text());
            cnt_m1 -= 1;
            $('.ch-r-mail-dd-z span').text(' ' + cnt_m1 + ' ');
            $('.ch-r-mail span').text(' ' + cnt_m1 + ' ');
            return false;
        });
    });
</script>

<?php echo $this->getContent(); ?>