{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАНИЕ ЗАЯВИТЕЛЯ{% endblock %}
{% block body %}
<div class="admin-main-wrap ufas-details">
    <div class="bread-crumbs-holder">
        <a href="/admin/ufas/index">Вернуться на страницу со списком</a>
    </div>
    {{flashSession.output()}}
    <h1>Добавить данные УФАС</h1>
    <div class="form-wrap">
        <form action="/admin/ufas/create" method="POST" enctype="multipart/form-data" id="ufas-form">
            <label for="name">
                <div>Наименование территориального органа</div>
                {{text_field("name", "value":"", "id":"name", "style": "width: 810px;")}}
            </label>
            <label for="number">
                <div>Налоговый номер</div>
                {{text_field("number", "value":"", "id":"number", "style": "width: 200px;")}}
            </label>
            <label for="address">
                <div>Адрес</div>
                {{text_field('address', 'value':"", "id":"address", "style": "width: 810px;")}}
            </label>
            <label for="phone">
                <div>Телефон/факс</div>
                {{text_field('phone', 'value':"", "id":"phone", "style": "width: 480px;")}}
            </label>
            <label for="email">
                <div>E-mail</div>
                {{text_field('email', 'value':"", "id":"email", "style": "width: 480px;")}}
            </label>
            <button class="save-btn">Сохранить изменения</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    $("head").append("<script type=\"text\/javascript\" src=\"\/js\/ufas.js\"><\/script>");
</script>
{% endblock %}