{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<script type="text/javascript" src="/js/ckeditor_n/ckeditor.js"></script>
<div class="admin-main-wrap creating-reasons">
    <div class="bread-crumbs-holder">
        <a href="/admin/arguments/index">Вернуться на страницу пользователя</a>
    </div>
    <h1>Создание довода</h1>
    <div class="reason-container">
        <form action="/admin/arguments/add" method="POST">
            <div class="select-holder">
                <select name="arguments[category_id]" class="hidden-select">
                    {% for category in ArgumentsCategory %}
                    <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                </select>
                <div class="title-info-box">Категория довода</div>
                <div class="custom_select">
                    <div class="current-option" data-value="">
                        <span>Выберите категорию</span>
                    </div>
                    <ul class="custom-options">
                        {% for category in ArgumentsCategory %}
                        <li data-value="{{category.id}}">{{category.name}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <label for="titleReason">
                <p>Заголовок довода</p>
                <input name="arguments[name]" type="text" id="titleReason">
            </label>
            <div class="editreason-title">Текст довода</div>
            <div class="editreason-contant">
                <img src="images/zaglushka2.png" alt="">
            </div>
            <div class="complaints-main " style="padding-left: 0;">
                <textarea name="arguments[text]" id="#arguments[text]" style="resize: vertical;" class="mCustomScrollbar" cols="130" rows="20"></textarea>
            <script>
                CKEDITOR.replace('arguments[text]');
            </script>
            </div>
            <button type="submit">Создать довод</button>
        </form>
    </div>
</div>

{% endblock %}