{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<div class="admin-main-wrap list-arguments">
    <h1>Доводы</h1>
    <a href="#" class="admin-add add-arg">Добавить довод</a>
    <div class="admin-lt-holder lt-arg">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Скрыть</div>
                <div>Удалить</div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li><span>Название довода</span></li>
                <li><span>Категория довода</span></li>
                <li><span>Добавлен</span></li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    Многократное повторение товаров
                </li>
                <li>Многократное повторение товаров</li>
                <li>22.01.2016</li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    Цифры прописью
                </li>
                <li>Цифры прописью</li>
                <li>20.01.2016</li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    Установление требований к сопутствующим материалам (ацетилен...
                </li>
                <li>Установление требований</li>
                <li>16.01.2016</li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    Корявая инструкция или её отсутствие
                </li>
                <li>Корявая инструкция или её отсутствие</li>
                <li>01.01.2016</li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    Запрос меняет суть
                </li>
                <li>Запрос меняет суть</li>
                <li>27.12.2015</li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    Не совпадает с планом-графиком
                </li>
                <li>Не совпадает с планом-графиком</li>
                <li>20.12.2015</li>
            </ul>
        </div>
    </div>
    <h1 class="second-lt-h1">Категории доводов</h1>
    <div class="admin-lt-holder lt-arg-second">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Создать</div>
                <div>Удалить</div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    <p>Многократное повторение товаров</p>
                    <input type="text">
                    <span>Сохранить</span>
                </li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    <p>Цифры прописью</p>
                    <input type="text">
                    <span>Сохранить</span>
                </li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    <p>Установление требований</p>
                    <input type="text">
                    <span>Сохранить</span>
                </li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    <p>Корявая инструкция или её отсутствие</p>
                    <input type="text">
                    <span>Сохранить</span>
                </li>
            </ul>
            <ul class="lt-content-main">
                <li>
                    <div class="lt-psevdo-check"></div>
                    <p>Запрос меняет суть</p>
                    <input type="text">
                    <span>Сохранить</span>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}
