{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<div class="admin-main-wrap edit-aplicant">
    <div class="bread-crumbs-holder">
        <a href="/admin/applicants/index">Вернуться к списку заявителей</a>
    </div>
    <h1>Редактировать заявителя</h1>
    <div class="tabs-block">
        <div class="aplicant-tabs-label">
            <div data-tabsLabel="legal-entity" class="active-tabs-label">Юридическое лицо</div>
            <div data-tabsLabel="individual-entrepreneur">Индивидуальный предприниматель</div>
            <div data-tabsLabel="physical-face">Физическое лицо</div>
        </div>
        <div data-tabs="legal-entity" class="tabs-content active-tabs-content">
            <form action="/admin/applicants/create" enctype="multipart/form-data" method="POST">
                {{hidden_field('type', 'value':'urlico')}}
                {{hidden_field('for_user_id', 'value':for_user_id)}}
                <label for="entity-textarea">
                    <div>Полное наименование</div>
                    <textarea name="full-name" id="entity-textarea"></textarea>
                </label>
                <label for="entity-short">
                    <div>Краткое наименование</div>
                    <input type="text" name="kratkoe-name" id="entity-short">
                </label>
                <label for="entity-inn">
                    <div>ИНН</div>
                    <input type="number" name="inn" id="entity-inn">
                </label>
                <label for="entity-kpp">
                    <div>КПП</div>
                    <input type="number" name="kpp" id="entity-kpp">
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    <input type="text" name="address" id="entity-address">
                </label>
                <label for="entity-position">
                    <div>Должность заявителя</div>
                    <input type="text" name="position-fio" id="entity-position">
                </label>
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    <input type="text" name="fio" id="entity-fio-z">
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    <input type="text" name="fio-kontakt-face" id="entity-fio-k">
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    <input type="text" name="phone" id="entity-phone">
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    <input type="text" name="email" id="entity-email">
                </label>
                <div class="file-attachment tab1">
                    <div class="file-wrapper">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" type="file" multiple name="upload-files[]">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('.tab1 #upload-files').change(function(){
                                var cnt = jQuery('.tab1 #upload-files')[0].files.length;
                                var i = 0;
                                var html = '';
                                for (i = 0; i < cnt; i++) {
                                    html = html + '<p>' + jQuery('.tab1 #upload-files')[0].files[i]['name'] + '</p>';
                                }
                                jQuery('.tab1 .file-names').html(html);
                            });
                        });
                    </script>
                </div>
                <button class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
        <div data-tabs="individual-entrepreneur" class="tabs-content">
            <form action="/admin/applicants/create" enctype="multipart/form-data" method="POST">
                {{hidden_field('type', 'value':'indlico')}}
                {{hidden_field('for_user_id', 'value':for_user_id)}}
                <label for="entity-textarea">
                    <div>Полное наименование</div>
                    <textarea name="full-name" id="entity-textarea"></textarea>
                </label>
                <div class="file-attachment tab2">
                    <div class="file-wrapper">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" type="file" multiple name="upload-files[]">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            //$('.tab2 #upload-files').fileupload({
                                //dataType: 'json',
                                /*add: function (e, data) {
                                    data.context = $('<button/>').text('Upload')
                                        .appendTo('.tab2 .file-names')
                                        .click(function () {
                                            data.context = $('<p/>').text('Uploading...').replaceAll($(this));
                                            data.submit();
                                        });
                                },
                                done: function (e, data) {
                                    data.context.text('Upload finished.');
                                }*/
                                /*done: function (e, data) {
                                    $.each(data.result.files, function (index, file) {
                                        $('<p/>').text(file.name).appendTo('.tab2 .file-names');
                                    });
                                }*/
                            //});
                            jQuery('.tab2 #upload-files').change(function(){
                                var cnt = jQuery('.tab2 #upload-files')[0].files.length;
                                var i = 0;
                                var html = '';
                                for (i = 0; i < cnt; i++) {
                                    html = html + '<p>' + jQuery('.tab2 #upload-files')[0].files[i]['name'] + '</p>';
                                }
                                jQuery('.tab2 .file-names').html(html);
                            });
                        });
                    </script>
                </div>
                <button class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
        <div data-tabs="physical-face" class="tabs-content">
            <form action="/admin/applicants/create" enctype="multipart/form-data" method="POST">
                {{hidden_field('type', 'value':'fizlico')}}
                {{hidden_field('for_user_id', 'value':for_user_id)}}
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    <input type="text" name="fio" id="entity-fio-z">
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    <input type="text" name="fio-kontakt-face" id="entity-fio-k">
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    <input type="text" name="phone" id="entity-phone">
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    <input type="text" name="email" id="entity-email">
                </label>
                <div class="file-attachment tab3">
                    <div class="file-wrapper">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" type="file" multiple name="upload-files[]">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('.tab3 #upload-files').change(function(){
                                var cnt = jQuery('.tab3 #upload-files')[0].files.length;
                                var i = 0;
                                var html = '';
                                for (i = 0; i < cnt; i++) {
                                    html = html + '<p>' + jQuery('.tab3 #upload-files')[0].files[i]['name'] + '</p>';
                                }
                                jQuery('.tab3 .file-names').html(html);
                            });
                        });
                    </script>
                </div>
                <button class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
