{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<div class="admin-main-wrap edit-aplicant">
    <div class="bread-crumbs-holder">
        <a href="/admin/applicants/index">Вернуться к списку заявителей</a>
    </div>
    <h1>Редактировать заявителя</h1>
    <div class="tabs-block">
        <div class="aplicant-tabs-label">
            <div data-tabsLabel="legal-entity" class="active-tabs-label">Юридическое лицо</div>
            <div data-tabsLabel="individual-entrepreneur">Индивидуальный предприниматель</div>
            <div data-tabsLabel="physical-face">Физическое лицо</div>
        </div>
        <div data-tabs="legal-entity" class="tabs-content active-tabs-content">
            <form action="/admin/applicants/create" enctype="multipart/form-data" method="POST">
                {{hidden_field('type', 'value':'urlico')}}
                {{hidden_field('for_user_id', 'value':for_user_id)}}
                <label for="entity-textarea">
                    <div>Полное наименование</div>
                    <textarea name="full-name" id="entity-textarea" style="width: 815px;"></textarea>
                </label>
                <label for="entity-short">
                    <div>Краткое наименование</div>
                    <input type="text" name="kratkoe-name" id="entity-short" style="width: 480px;">
                </label>
                <label for="entity-inn">
                    <div>ИНН</div>
                    <input type="number" name="inn" id="entity-inn" style="width: 260px;">
                </label>
                <label for="entity-kpp">
                    <div>КПП</div>
                    <input type="number" name="kpp" id="entity-kpp" style="width: 260px;">
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    <input type="text" name="address" id="entity-address" style="width: 810px;">
                </label>
                <label for="entity-position">
                    <div>Должность заявителя</div>
                    <input type="text" name="position-fio" id="entity-position" style="width: 480px;">
                </label>
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    <input type="text" name="fio" id="entity-fio-z" style="width: 480px;">
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    <input type="text" name="fio-kontakt-face" id="entity-fio-k" style="width: 480px;">
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    <input type="text" name="phone" id="entity-phone" style="width: 260px;">
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    <input type="text" name="email" id="entity-email" style="width: 480px;">
                </label>
                <div class="file-attachment tab1">
                    <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" class="upload_f" type="file" multiple name="upload-files[]" style="width:100%; height 100%">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('body').on('change','.tab1 .upload_f', function(){
                                debugger;
                                var cnt = jQuery(this)[0].files.length;
                                if(cnt > 0){
                                    var count = jQuery('.tab1 .upload_f').length + 1;
                                    jQuery(".tab1 .file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                    jQuery(this).off('change');
                                }
                                var html = '';
                                var upload_file = jQuery(this);
                                for(var i = 0; i < upload_file.length; i++){
                                    for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                        var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                        var html = html + '<p>' + jQuery(upload_file[i])[0].files[j]['name'] + '</p>';
                                    }
                                }
                                jQuery('.tab1 .file-names').append(html);
                            });
                        });
                    </script>
                </div>
                <button class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
        <div data-tabs="individual-entrepreneur" class="tabs-content">
            <form action="/admin/applicants/create" enctype="multipart/form-data" method="POST">
                {{hidden_field('type', 'value':'indlico')}}
                {{hidden_field('for_user_id', 'value':for_user_id)}}
                <label for="entity-textarea">
                    <div>Полное наименование</div>
                    <textarea name="full-name" id="entity-textarea" style="width: 815px;"></textarea>
                </label>
                <label for="entity-inn">
                    <div>ИНН</div>
                    <input type="number" name="inn" id="entity-inn" style="width: 260px;">
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    <input type="text" name="address" id="entity-address" style="width: 810px;">
                </label>
                <label for="entity-position">
                    <div>Должность заявителя</div>
                    <input type="text" name="position-fio" id="entity-position" style="width: 480px;">
                </label>
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    <input type="text" name="fio" id="entity-fio-z" style="width: 480px;">
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    <input type="text" name="phone" id="entity-phone" style="width: 260px;">
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    <input type="text" name="email" id="entity-email" style="width: 480px;">
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    <input type="text" name="fio-kontakt-face" id="entity-fio-k" style="width: 480px;">
                </label>
                <div class="file-attachment tab2">
                    <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" class="upload_f" type="file" multiple name="upload-files[]" style="width:100%; height 100%">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('body').on('change','.tab2 .upload_f', function(){
                                console.log(this);
                                var cnt = jQuery('.tab2 .upload_f')[0].files.length;
                                if(cnt > 0){
                                    var count = jQuery('.tab2 .upload_f').length + 1;
                                    jQuery(".tab1 .file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                    jQuery(this).off('change');
                                }
                                var html = '';
                                var upload_file = jQuery('.tab2 .upload_f');
                                debugger;
                                for(var i = 0; i < upload_file.length; i++){
                                    for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                        var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                        var html = html + '<div id="attached-file-' + i + '" class="attached-file-row"><div class="file-icon ' + get_class_by_file_type(file_type) + '"></div><div class="file-link">' + jQuery(upload_file[i])[0].files[j]['name'] + ' (' + file_size.toFixed(2) + ' Кб)</div><div style="display: none;" class="delete-file" title="Удалить файл"></div><div style="clear:both;"></div></div>';
                                    }
                                }
                                jQuery('.tab2 .file-names .attached-files').html(html);
                            });
                        });
                    </script>
                </div>
                <button class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
        <div data-tabs="physical-face" class="tabs-content">
            <form action="/admin/applicants/create" enctype="multipart/form-data" method="POST">
                {{hidden_field('type', 'value':'fizlico')}}
                {{hidden_field('for_user_id', 'value':for_user_id)}}
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    <input type="text" name="fio" id="entity-fio-z" style="width: 480px;">
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    <input type="text" name="address" id="entity-address" style="width: 810px;">
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    <input type="text" name="phone" id="entity-phone" style="width: 260px;">
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    <input type="text" name="email" id="entity-email" style="width: 480px;">
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    <input type="text" name="fio-kontakt-face" id="entity-fio-k" style="width: 480px;">
                </label>
                <div class="file-attachment tab3">
                    <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" class="upload_f" type="file" multiple name="upload-files[]" style="width:100%; height 100%">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('body').on('change','.tab3 .upload_f', function(){
                                console.log(this);
                                var cnt = jQuery('.tab3 .upload_f')[0].files.length;
                                if(cnt > 0){
                                    var count = jQuery('.tab3 .upload_f').length + 1;
                                    jQuery(".tab3 .file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                    jQuery(this).off('change');
                                }
                                var html = '';
                                var upload_file = jQuery('.tab3 .upload_f');
                                debugger;
                                for(var i = 0; i < upload_file.length; i++){
                                    for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                        var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                        var html = html + '<div id="attached-file-' + i + '" class="attached-file-row"><div class="file-icon ' + get_class_by_file_type(file_type) + '"></div><div class="file-link">' + jQuery(upload_file[i])[0].files[j]['name'] + ' (' + file_size.toFixed(2) + ' Кб)</div><div style="display: none;" class="delete-file" title="Удалить файл"></div><div style="clear:both;"></div></div>';
                                    }
                                }
                                jQuery('.tab3 .file-names .attached-files').html(html);
                            });
                        });
                    </script>
                </div>
                <button class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
