{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАНИЕ ЗАЯВИТЕЛЯ{% endblock %}
{% block body %}
<div class="admin-main-wrap edit-aplicant">
    <div class="bread-crumbs-holder">
        <a href="/admin/applicants/info/{{applicant.id}}">Вернуться на страницу заявителя</a>
    </div>
    {{flashSession.output()}}
    <h1>Редактировать заявителя</h1>
    <div class="tabs-block">
        {{hidden_field('applicant-current-type', 'value':applicant.type)}}
        <div class="aplicant-tabs-label">
            <div data-tabsLabel="legal-entity" {%if applicant.type=="urlico" %}class="active-tabs-label"{%endif%}>Юридическое лицо</div>
            <div data-tabsLabel="individual-entrepreneur" {%if applicant.type=="ip" %}class="active-tabs-label"{%endif%}>Индивидуальный предприниматель</div>
            <div data-tabsLabel="physical-face"  {%if applicant.type=="fizlico" %}class="active-tabs-label"{%endif%}>Физическое лицо</div>
        </div>
        <div data-tabs="legal-entity" class="tabs-content {%if applicant.type=="urlico" %}active-tabs-content{%endif%}">
            <form action="/admin/applicants/save" method="POST" enctype="multipart/form-data" id="urlico">
                {{hidden_field('id', 'value':applicant.id)}}
                {{hidden_field('type', 'value':'urlico')}}
                <label for="entity-textarea">
                    <div>Полное наименование</div>
                    {{text_area('name_full', 'value':applicant.name_full, 'id':'entity-textarea')}}
                </label>
                <label for="entity-short">
                    <div>Краткое наименование</div>
                    {{text_field("name_short", "value":applicant.name_short, "data-name":"kratkoe-name", "class":"upper-text",  "id":"entity-short")}}
                </label>
                <label for="entity-inn">
                    <div>ИНН</div>
                    {{numeric_field('inn', 'value':applicant.inn, "id":"entity-inn", "data-name":"number")}}
                </label>
                <label for="entity-kpp">
                    <div>КПП</div>
                    {{numeric_field('kpp', 'value':applicant.kpp, "id":"entity-kpp")}}
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    {{text_field('address', 'value':applicant.address, "id":"entity-address", "data-name":"address")}}
                </label>
                <label for="entity-position">
                    <div>Должность заявителя</div>
                    {{text_field('position', 'value':applicant.position, "id":"entity-position", "data-name":"position-fio")}}
                </label>
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    {{text_field('fio_applicant', 'value':applicant.fio_applicant, "id":"entity-fio-z", "data-name":"position-fio")}}
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    {{text_field('fio_contact_person', 'value':applicant.fio_contact_person, "id":"entity-fio-k", "data-name":"position-fio")}}
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    {{numeric_field('telefone', 'value':applicant.telefone, "id":"entity-phone",  "data-name":"number")}}
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    {{text_field('email', 'value':applicant.email, "id":"entity-email", "data-name":"position-fio" )}}
                </label>
                <style>
                    .upload_f{
                        width: 100% !important;
                        height: 100%;
                    }
                </style>
                <div class="file-attachment tab1">
                    <div class="file-wrapper" style="margin-bottom: 20px; height: 30px;">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('body').on('change','.upload_f', function(){
                                var cnt = jQuery(this)[0].files.length;
                                if(cnt > 0){
                                    var count = jQuery('.file-attachment .upload_f').length + 1;
                                    jQuery(".file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                    jQuery(this).off('change');
                                }
                                var html = '';
                                var upload_file = jQuery(this);
                                for(var i = 0; i < upload_file.length; i++){
                                    for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                        var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                        var html = html + '<p>' + jQuery(upload_file[i])[0].files[j]['name'] + '</p>';
                                    }
                                }
//                                                for (i = 0; i < cnt; i++) {
//                                                    var file_data = jQuery('#upload-files')[0].files[i]['name'].split('.');
//                                                    var file_type = file_data[file_data.length - 1];
//                                                    var file_size = jQuery('#upload-files')[0].files[i]['size'] / 1024;
//                                                    var html = html + '<div id="attached-file-' + i + '" class="attached-file-row"><div class="file-icon ' + get_class_by_file_type(file_type) + '"></div><div class="file-link">' + jQuery('#upload-files')[0].files[i]['name'] + ' (' + file_size.toFixed(2) + ' Кб)</div><div style="display: none;" class="delete-file" title="Удалить файл"></div><div style="clear:both;"></div></div>';
//                                                }
                                jQuery('.tab1 .file-names').append(html);
                            });
                        });
//                        jQuery(document).ready(function(){
//                            jQuery('.tab1 #upload-files').change(function(){
//                                var cnt = jQuery('.tab1 #upload-files')[0].files.length;
//                                var i = 0;
//                                var html = '';
//                                for (i = 0; i < cnt; i++) {
//                                    html = html + '<p>' + jQuery('.tab1 #upload-files')[0].files[i]['name'] + '</p>';
//                                }
//                                jQuery('.tab1 .file-names').html(html);
//                            });
//                        });
                    </script>
                    <div class="attached-files">
                        {% if attached_files|count > 0 %}
                            {% for file in attached_files %}
                                {{ file }}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <button onclick="confirm_change_applicant_type(jQuery('#applicant-current-type').val(), 'urlico');return false;" class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
        <div data-tabs="individual-entrepreneur" class="tabs-content {%if applicant.type=="ip" %}active-tabs-content{%endif%}">
            <form action="/admin/applicants/save" method="POST" enctype="multipart/form-data" id="ip">
                {{hidden_field('id', 'value':applicant.id)}}
                {{hidden_field('type', 'value':'ip')}}
                <label for="entity-textarea">
                    <div>Полное наименование</div>
                    {{text_area('name_full', 'value':applicant.name_full, 'id':'entity-textarea')}}
                </label>
                <label for="entity-inn">
                    <div>ИНН</div>
                    {{numeric_field('inn', 'value':applicant.inn, "id":"entity-inn", "data-name":"number")}}
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    {{text_field('address', 'value':applicant.address, "id":"entity-address", "data-name":"address")}}
                </label>
                <label for="entity-position">
                    <div>Должность заявителя</div>
                    {{text_field('position', 'value':applicant.position, "id":"entity-position", "data-name":"position-fio")}}
                </label>
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    {{text_field('fio_applicant', 'value':applicant.fio_applicant, "id":"entity-fio-z", "data-name":"position-fio")}}
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    {{numeric_field('telefone', 'value':applicant.telefone, "id":"entity-phone",  "data-name":"number")}}
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    {{text_field('email', 'value':applicant.email, "id":"entity-email", "data-name":"position-fio" )}}
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    {{text_field('fio_contact_person', 'value':applicant.fio_contact_person, "id":"entity-fio-k", "data-name":"position-fio")}}
                </label>
                <div class="file-attachment tab2">
                    <div class="file-wrapper">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" type="file" multiple name="upload-files[]">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('.tab2 #upload-files').change(function(){
                                var cnt = jQuery('.tab2 #upload-files')[0].files.length;
                                var i = 0;
                                var html = '';
                                for (i = 0; i < cnt; i++) {
                                    html = html + '<p>' + jQuery('.tab2 #upload-files')[0].files[i]['name'] + '</p>';
                                }
                                jQuery('.tab2 .file-names').html(html);
                            });
                        });
                    </script>
                    <div class="attached-files">
                        {% if attached_files|count > 0 %}
                            {% for file in attached_files %}
                                {{ file }}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <button onclick="confirm_change_applicant_type(jQuery('#applicant-current-type').val(), 'ip');return false;"  class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
        <div data-tabs="physical-face" class="tabs-content {%if applicant.type=="fizlico" %}active-tabs-content{%endif%}">
            <form action="/admin/applicants/save" method="POST" enctype="multipart/form-data" id="fizlico">
                {{hidden_field('id', 'value':applicant.id)}}
                {{hidden_field('type', 'value':'fizlico')}}
                <label for="entity-fio-z">
                    <div>ФИО заявителя</div>
                    {{text_field('fio_applicant', 'value':applicant.fio_applicant, "id":"entity-fio-z", "data-name":"position-fio")}}
                </label>
                <label for="entity-address">
                    <div>Адрес местонахождения</div>
                    {{text_field('address', 'value':applicant.address, "id":"entity-address", "data-name":"position-fio" )}}
                </label>
                <label for="entity-phone">
                    <div>Контактный факс, телефон</div>
                    {{numeric_field('telefone', 'value':applicant.telefone, "id":"entity-phone",  "data-name":"number")}}
                </label>
                <label for="entity-email">
                    <div>E-mail</div>
                    {{text_field('email', 'value':applicant.email, "id":"entity-email", "data-name":"position-fio" )}}
                </label>
                <label for="entity-position-k">
                    <div>ФИО контактного лица</div>
                    {{text_field('fio_contact_person', 'value':applicant.fio_contact_person, "id":"entity-fio-k", "data-name":"position-fio")}}
                </label>
                <div class="file-attachment tab3">
                    <div class="file-wrapper">
                        <div class="text-above">Прикрепить файлы</div>
                        <input id="upload-files" type="file" multiple name="upload-files[]">
                    </div>
                    <div class="file-names"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            jQuery('.tab3 #upload-files').change(function(){
                                var cnt = jQuery('.tab3 #upload-files')[0].files.length;
                                var i = 0;
                                var html = '';
                                for (i = 0; i < cnt; i++) {
                                    html = html + '<p>' + jQuery('.tab3 #upload-files')[0].files[i]['name'] + '</p>';
                                }
                                jQuery('.tab3 .file-names').html(html);
                            });
                        });
                    </script>
                    <div class="attached-files">
                        {% if attached_files|count > 0 %}
                            {% for file in attached_files %}
                                {{ file }}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <button onclick="confirm_change_applicant_type(jQuery('#applicant-current-type').val(), 'fizlico');return false;" class="save-tab-form">Сохранить изменения</button>
            </form>
        </div>
    </div>
    {{hidden_field('delete-file-id', 'value':'')}}
    {{hidden_field('delete-applicant-id', 'value':applicant.id)}}
    <div class="modal fade modal-confirm-change-applicant-type" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">При смене правовой формы будут удалены ранее введённые данные, присущие текущему статусу заявителя, продолжить?</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" applicant-type="" onclick="jQuery('form#' + jQuery(this).attr('applicant-type')).submit();" class="btn btn-primary">Да</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade confirm-deletion-file-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Удалить файл?</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="jQuery('#delete-file-id').val('');">Отмена</button>
            <button type="button" onclick="delete_applicant_file()" class="btn btn-primary">Удалить</button>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}
