{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<div class="admin-main-wrap applicant-list">
    <h1>Список заявителей</h1>
    <a href="/admin/applicants/add" class="admin-add userAdd">Добавить заявителя</a>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div class="disabled-btn block-applicant" onclick="block_unblock_applicant(1)">Заблокировать</div>
                <div class="disabled-btn unblock-applicant" onclick="block_unblock_applicant(0)">Разблокировать</div>
                <div id="delete-button" class="disabled-btn">Удалить</div>
            </div>
            <div class="modal fade confirm-deletion-applicant-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удалить заявителя?</h4>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" onclick="delete_applicants()" class="btn btn-primary">Удалить</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div class="admin-lt-content" id="sort-table">
            <ul class="lt-content-top">
                <li sort-field="sort-name"><span class="sortable">Краткое наименование</span></li>
                <li sort-field="sort-phone"><span class="sortable">Телефон</span></li>
                <li sort-field="sort-email"><span class="sortable">Имейл</span></li>
                <li sort-field="sort-complaints"><span class="sortable">Жалобы</span></li>
            </ul>
            {% for applicant in page.items %}
                {% if applicant.type == 'ip' %}
                    <ul class="lt-content-main {% if applicant.is_blocked == 0 %} hidden-arg {% endif %}" sort-name="{{applicant.name_short}}" sort-phone="" sort-email="" sort-complaints="{{applicant.getCountComplaints(applicant.id)}}" detail-url="{{url('admin/applicants/info/' ~ applicant.id)}}">
                        <li><div class="lt-psevdo-check">{{hidden_field('applicant-id', 'value':applicant.id)}}</div>
							{% if applicant.name_short %}
								{{applicant.name_short}}
							{% else %}
								{{applicant.fio_applicant}}
							{% endif  %}
						</li>
                        <li>{{applicant.telefone}}</li>
                        <li>{{applicant.email}}</li>
                        <li>{{applicant.getCountComplaints(applicant.id)}}</li>
                    </ul>
                {% elseif applicant.type == 'fizlico' %}
                    <ul class="lt-content-main {% if applicant.is_blocked == 0 %} hidden-arg {% endif %}" sort-name="{{applicant.fio_applicant}}" sort-phone="" sort-email="" sort-complaints="{{applicant.getCountComplaints(applicant.id)}}" detail-url="{{url('admin/applicants/info/' ~ applicant.id)}}">
                        <li><div class="lt-psevdo-check">{{hidden_field('applicant-id', 'value':applicant.id)}}</div>{{applicant.fio_applicant}}</li>
                        <li>{{applicant.telefone}}</li>
                        <li>{{applicant.email}}</li>
                        <li>{{applicant.getCountComplaints(applicant.id)}}</li>
                    </ul>
                {% else %}
                    <ul class="lt-content-main {% if applicant.is_blocked == 0 %} hidden-arg {% endif %}" sort-name="{{applicant.name_short}}" sort-phone="{{applicant.telefone}}" sort-email="{{applicant.email}}" sort-complaints="{{applicant.getCountComplaints(applicant.id)}}" detail-url="{{url('admin/applicants/info/' ~ applicant.id)}}">
                        <li><div class="lt-psevdo-check">{{hidden_field('applicant-id', 'value':applicant.id)}}</div>{{applicant.name_short}}</li>
                        <li>{{applicant.telefone}}</li>
                        <li>{{applicant.email}}</li>
                        <li>{{applicant.getCountComplaints(applicant.id)}}</li>
                    </ul>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {% if page.total_items > item_per_page %}
        <div class="admin-table-footer">
            {% if page.current * item_per_page < page.total_items %}
                {% set cnt = page.total_items - (page.current * item_per_page) %}
                <a href="#" onclick="$('#next_items').submit()">Еще <span>{{ cnt > item_per_page ? 20 : cnt}} заявителей</span></a><!--todo: -->
                {% else %}
                    <div></div>
            {% endif %}
            <a href="/admin/applicants/index?all-portions-items=all_items">Показать всех заявителей (<span>{{page.total_items}}</span>)</a><!--todo: -->
        </div>
        <form id="next_items" method="post">
            {{hidden_field('next-portions-items', 'value':20)}}
        </form>
    {% endif %}
    <div class="admin-pagination-box">
        {% if page.current>1 %}{{ link_to("admin/applicants/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("admin/applicants/index?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}{{ link_to("admin/applicants/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
    </div>
    {% if scroll_to_down %}
        <script type="text/javascript">
            $("html, body").animate({ scrollTop: $(document).height() - 310 }, 1)
        </script>
    {% endif %}
</div>
{% endblock %}