{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<div class="admin-main-wrap user-list">
    <h1>Список пользователей</h1>
    <a href="/admin/user/add" class="admin-add userAdd">Добавить пользователя</a>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Отправить сообщение</div>
                <div>Заблокировать</div>
                <div>Удалить</div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li><span>ФИО</span></li>
                <li><span>Телефон</span></li>
                <li><span>Заявители</span></li>
                <li><span>Жалобы</span></li>
                <li><span>Подписка до</span></li>
                <li><span>Тариф</span></li>
            </ul>
            {% for user in page.items %}
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li>{{user.name_full}}</li>
                <li>{{user.name_short}}</li>
                <li>{{user.inn}}</li>
                <li>{{user.fio_applicant}}</li>
                <li></li>
            </ul>
            {% endfor %}
        </div>
    </div>
    <div class="admin-table-footer">
        <a href="#">Еще <span>20 заявителей</span></a><!--todo: -->
        <a href="#">Показать всех пользователей (<span>{{page.total_items}}</span>)</a><!--todo: -->

    </div>
    <div class="admin-pagination-box">
        {% if page.current>1 %}{{ link_to("admin/applicants/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("admin/applicants/index?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}{{ link_to("admin/applicants/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
    </div>
</div>
{% endblock %}
