{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Доводы{% endblock %}
{% block body %}
<div class="admin-main-wrap applicant-list">
    <h1>Список заявителей</h1>
    <a href="/admin/applicants/add" class="admin-add userAdd">Добавить заявителя</a>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <a href="#"><div data-toggle="modal" data-target=".confirm-deletion-applicant-lg">Удалить</div></a>
            </div>
            <div class="modal fade confirm-deletion-applicant-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удалить заявителя?</h4>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" onclick="delete_applicants()" class="btn btn-primary">Удалить</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li><span>Краткое наименование</span></li>
                <li><span>Телефон</span></li>
                <li><span>Имейл</span></li>
                <li><span>Жалобы</span></li>
                <li></li>
            </ul>
            {% for applicant in page.items %}
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check">{{hidden_field('applicant-id', 'value':applicant.id)}}</div>{{applicant.name_short}}</li>
                <li>{{applicant.telefone}}</li>
                <li>{{applicant.email}}</li>
                <li>{{applicant.getCountComplaints(applicant.id)}}</li>
                <li>{{ link_to("admin/applicants/info/" ~ applicant.id, 'Просмотр') }}</li>
            </ul>
            {% endfor %}
        </div>
    </div>
    <div class="admin-table-footer">
        <a href="#">Еще <span>20 заявителей</span></a><!--todo: -->
        <a href="#">Показать всех заявителей (<span>{{page.total_items}}</span>)</a><!--todo: -->

    </div>
    <div class="admin-pagination-box">
        {% if page.current>1 %}{{ link_to("admin/applicants/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("admin/applicants/index?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}{{ link_to("admin/applicants/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
    </div>
</div>
{% endblock %}
