{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Заявитель{% endblock %}
{% block body %}
<div class="admin-main-wrap appllicant-page-detail">
    <div class="bread-crumbs-holder">
        <a href="#" onclick="history.back();return false;">Вернуться на страницу заявителей</a>
    </div>
    <h1>{{applicant.name_full}}</h1>
    <div class="del-oredit-appll">
        <div data-toggle="modal" data-target=".confirm-deletion-applicant-lg">Удалить заявителя</div>
        <a href="/admin/applicants/edit/{{applicant.id}}">Редактировать</a>
    </div>
    <div class="modal fade confirm-deletion-applicant-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Удалить заявителя?</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" onclick="delete_applicant({{applicant.id}})" class="btn btn-primary">Удалить</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade modal-cant-delete-applicant" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Невозможно удалить заявителя у которого есть жалобы</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
          </div>
        </div>
      </div>
    </div>
    <h2>Жалобы заявителя</h2>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div data-toggle="modal" onclick="complaints_to_archive()">В архив</div>
                <div data-toggle="modal" data-target=".confirm-deletion-complaints-lg">Удалить</div>
            </div>
            <div class="modal fade confirm-deletion-complaints-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удалить жалобы заявителя?</h4>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" onclick="delete_all_complaints()" class="btn btn-primary">Удалить</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li><span>Имя жалобы</span></li>
                <li><span>Номер закупки</span></li>
                <li><span>Дата подачи</span></li>
                <li><span>Статус</span></li>
            </ul>
            {% for complaint in page.items %}
            <ul class="lt-content-main {{applicant.getComplaintColor(complaint['status'])}}" detail-url="{{url('admin/complaints/preview/' ~ complaint['id'])}}">
                <li>
                    <div class="lt-psevdo-check">{{hidden_field('complaint-id', 'value':complaint['id'])}}</div>
                    {{complaint['complaint_name']}}
                </li>
                <li>{{complaint['auction_id']}}</li>
                <li>{{date('d.m.Y', complaint['date']|strtotime)}}</li>
                <li class='with-dropdown'>
                    <div class="dropdown">
                      <div id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{applicant.getComplaintStatus(complaint['status'], TRUE)}}
                      </div>
                      <ul class="dropdown-menu" aria-labelledby="dLabel">
                        <li class="header-dropdown">Сменить статус<span class="caret"></span></li>
                        <li>{{applicant.getAllStatuses(0)}}</li>
                        <li>{{applicant.getAllStatuses(1)}}</li>
                        <li>{{applicant.getAllStatuses(2)}}</li>
                        <li>{{applicant.getAllStatuses(3)}}</li>
                        <li>{{applicant.getAllStatuses(4)}}</li>
                        <li>{{applicant.getAllStatuses(5)}}</li>
                        <li>{{applicant.getAllStatuses(6)}}</li>
                      </ul>
                    </div>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
    {% if page.total_items > item_per_page %}
        <div class="admin-table-footer">
            {% if page.current * item_per_page < page.total_items %}
                {% set cnt = page.total_items - (page.current * item_per_page) %}
                <a href="#" onclick="$('#next_items').submit()">Еще <span>{{ cnt > item_per_page ? 20 : cnt}} жалоб</span></a><!--todo: -->
                {% else %}
                    <div></div>
            {% endif %}
            <a href="/admin/applicants/info/{{applicant.id}}?all-portions-items=all_items">Показать все жалобы (<span>{{page.total_items}}</span>)</a><!--todo: -->
        </div>
        <form id="next_items" method="post">
            {{hidden_field('next-portions-items', 'value':20)}}
        </form>
    {% endif %}
    <div class="admin-pagination-box">
        {% if page.current>1 %}
        {{ link_to("/admin/applicants/info/"~applicant.id~"?page=" ~ page.before, 'Предыдущая', 'id' : 'admin-pag-prev') }}
        {% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("/admin/applicants/info/"~applicant.id~"?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}
        {{ link_to("/admin/applicants/info/"~applicant.id~"?page=" ~ page.next, 'Следующая', 'id' : 'admin-pag-next') }}
        {% endif %}
    </div>
</div>
<div id="pop-confirm-change-complaint-status" class="modal_div">
    <h2></h2>
    <div class="pop-done-txt">
        <div class="popup-content"></div>
        <div class="action-buttons">
            <div class="popup-button cnc popup-close">Отменить</div>
            <div class="popup-button apr">Да</div>
            <div style="clear: both;"></div>
        </div>
    </div>
    <div class="modal-close"></div>
</div>
{% endblock %}