{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Заявитель{% endblock %}
{% block body %}
<div class="admin-main-wrap appllicant-page">
    <div class="bread-crumbs-holder">
        <a href="#">Вернуться на страницу пользователя</a>
    </div>
    <h1>{{applicant.name_full}}</h1>
    <div class="del-oredit-appll">
        <a href="#">Удалить заявителя</a>
        <a href="/admin/applicants/edit/{{applicant.id}}">Редактировать</a>
    </div>
    <h2>Жалобы заявителя</h2>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Копировать</div>
                <div>Создать</div>
                <div>В архив</div>
                <div>Удалить</div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li><span>Имя жалобы</span></li>
                <li><span>Номер закупки</span></li>
                <li><span>Дата подачи</span></li>
                <li><span>Статус</span></li>
            </ul>
            {% for complaint in page.items %}
            <ul class="lt-content-main {%if comliant['status'] =='submitted' %}top-bd-blue{%elseif comliant['status'] == 'unfounded'%}top-bd-red{%elseif comliant['status'] == 'justified'%}top-bd-green{%endif%}">
                <li>
                    <div class="lt-psevdo-check"></div>
                    {{complaint['complaint_name']}}
                </li>
                <li>{{complaint['auction_id']}}</li>
                <li>{{date('Y.m.d', complaint['date']|strtotime)}}</li>
                <li>
                    {% if complaint['status'] == 'draft' %}
                    <span class="jl-status jl-chernov">Черновик</span>
                    {% endif %}
                    {% if complaint['status'] == 'justified' %}
                    <span class="jl-status jl-done">Обоснована</span>
                    {% endif %}
                    {% if complaint['status'] == 'unfounded' %}
                    <span class="jl-status jl-notdone">Необоснована</span>
                    {% endif %}
                    {% if complaint['status'] == 'under_consideration' %}
                    <span class="jl-status jl-rassmotr">На рассмотрении</span>
                    {% endif %}
                    {% if complaint['status'] == 'submitted' %}
                    <span class="jl-status jl-podana">Подана</span>
                    {% endif %}
                    {% if complaint['status'] == 'recalled' %}
                    <span class="jl-status jl-fail">Отозвана</span>
                    {% endif %}
                    {% if complaint['status'] == 'archive' %}
                    <span class="jl-status jl-archive">Архив</span>
                    {% endif %}
                    <!--div class="appll-status-icon"></div-->
                    <div class="close-status-list">Сменить статус</div>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
    <div class="admin-table-footer">
        <a href="#">Еще <span>20 жалоб</span></a>
        <a href="#">Показать все жалобы (<span>{{page.total_items}}</span>)</a>
    </div>
    <div class="admin-pagination-box">
        {% if page.current>1 %}
        {{ link_to("/admin/applicants/info/"~applicant.id~"?page=" ~ page.before, 'Предыдущая', 'id' : 'admin-pag-prev') }}
        {% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("complaint/index"~applicant.id~"?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}
        {{ link_to("/admin/applicants/info/"~applicant.id~"?page=" ~ page.next, 'Следующая', 'id' : 'admin-pag-next') }}
        {% endif %}
    </div>
</div>
{% endblock %}