<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <title>!DOCTYPE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=cyrillic,cyrillic-ext" rel="stylesheet">
</head>
<body style="background-color:#f7f8fa;">
<table border="0" cellpadding="0" cellspacing="0" style="margin:50px auto 50px auto;padding:16px 0 0 0;width:612px;background-color:#ffffff;">
    <thead align="center">
    <tr>
        <td>
            <img src="http://{{ host }}/public/emails/logo.jpg" width="579" height="141" alt="fas-online" style="margin:0;padding:0;display:block;">
        </td>
    </tr>
    </thead>
    <tbody style="font-family:'Open Sans',sans-serif;display:block;padding:30px 50px">
    <tr style="color:#00aeef;font-size:34px;line-height:34px;font-weight:700;">
        <td style="padding-bottom:10px;">Подтверждение</td>
    </tr>
    <tr style="color:#00aeef;font-size:34px;line-height:34px;font-weight:300;">
        <td style="padding-bottom:20px;">регистрации</td>
    </tr>
    <tr style="color:#34383e;font-size:20px;line-height:30px;font-weight:300;">
        <td style="padding-bottom:25px;">Уважаемый пользователь, поздравляем!
            Ваш доступ к интеллектуальному сервису подачи жалоб «ФАС-Онлайн» готов!</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Для входа в систему пройдите по <a href="http://{{ host }}/login" style="color:#00aeef;" target="_blank">ссылке</a>. </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Ваш логин {{ login }}. </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Ваш пароль нам неизвестен, но если вы его забыли, восстановить его можно <a href="#" style="color:#00aeef;">здесь</a>.</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Для работы в системе вам понадобится электронная подпись (ЭП). Если у Вас еще нет ЭП, мы поможем выпустить ее за один день. Заказать ЭП.</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Данное сообщение создано автоматически и не требует ответа. При возникновении вопросов по работе сервиса «ФАС-Онлайн» просьба обращаться в <a href="#" style="color:#00aeef;">техническую поддержку.</a> Рекомендуем ознакомиться с разделом <a href="#" style="color:#00aeef;">помощи клиентам.</a> Остались вопросы – пишите нам на почту <a href="#" style="color:#00aeef;">info@fas-online.ru</a> или звоните по бесплатному номеру 8-800-100-93-86.</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:30px;font-weight:400;">
        <td style="padding-bottom:15px;">С уважением, интеллектуальный сервис <a href="fas-online.ru" style="color:#00aeef;">"ФАС-ОНЛАЙН"</a></td>
    </tr>
    </tbody>
</table>
</body>
</html>