<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <title>!DOCTYPE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=cyrillic,cyrillic-ext" rel="stylesheet">
</head>
<body style="background-color:#f7f8fa;">
<table border="0" cellpadding="0" cellspacing="0" style="margin:50px auto 50px auto;padding:16px 0 0 0;width:612px;background-color:#ffffff;">
    <thead align="center">
    <tr>
        <td>
            <img src="http://{{ host }}/public/emails/logo.jpg" width="579" height="141" alt="fas-online" style="margin:0;padding:0;display:block;">
        </td>
    </tr>
    </thead>
    <tbody style="font-family:'Open Sans',sans-serif;display:block;padding:30px 50px">
    <tr style="color:#00aeef;font-size:34px;line-height:34px;font-weight:700;">
        <td style="padding-bottom:10px;">Форма обратной связи</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Имя: {{ name }}. </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Email: {{ email }}. </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Телефон: {{ phone }}. </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">Сообщение: {{ message }}. </td>
    </tr>
    </tbody>
</table>
</body>
</html>