<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <title>!DOCTYPE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=cyrillic,cyrillic-ext" rel="stylesheet">
</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" style="margin:50px auto 50px auto;padding:16px 0 0 0;width:612px;background-color:#ffffff;">
    <thead align="center">
    <tr>
        <td>
            <img src="http://{{ host }}/public/emails/logo.jpg" width="579" height="141" alt="fasonline" style="margin:0;padding:0;display:block;">
        </td>
    </tr>
    </thead>
    <tbody style="font-family:'Open Sans',sans-serif;display:block;padding:30px 50px">
    <tr style="color:#00aeef;font-size:34px;line-height:34px;font-weight:700;">
        <td style="padding-bottom:10px;">Новый заказ</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">
            <strong>ФИО:</strong> {{ order.firstname }} <br/>
            <strong>Ссылка на пользователя:</strong>  <a href="http://{{host}}/admin/user/edit/{{order.user_id}}">http://{{host}}/admin/user/edit/{{order.user_id}}</a>
        </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;"><strong>Email:</strong> {{ order.email }}</td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;"><strong>Телефон:</strong> {{ order.phone }}</td>
    </tr>

    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;">
            <strong>Номер извещения:</strong> {{ order.auction_id }} <br/>
            <strong>Ссылка на извещение:</strong> <a href="http://zakupki.gov.ru/epz/order/notice/ea44/view/common-info.html?regNumber={{ order.auction_id }}">http://zakupki.gov.ru/epz/order/notice/ea44/view/common-info.html?regNumber={{ order.auction_id }}</a>
        </td>
    </tr>
    <tr style="color:#34383e;font-size:14px;line-height:14px;font-weight:400;">
        <td style="padding-bottom:10px;"><strong>Дата создания заказа:</strong> {{ order.date }}</td>
    </tr>
    </tbody>
</table>
</body>
</html>