<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="#"></a>
        </div>
		<a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
		<a href="mailto:info@fasonline.ru" class="mh-mail">info@fasonline.ru</a>
		             {% if is_logged_in %}
            <a href="/complaint/index" class="already-logged-in">Вход в систему</a>
        {% else %}
            <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
            <a href="#" class="wantReg">Регистрация</a>
        {% endif %}
    </div>
</div>

<div class="mstripe-1">
    <div class="wrapper" style="text-align: center;">
    {{flashSession.output()}}
        <h1>
            Подай жалобу в ФАС легко!<br>
            <span>Интеллектуальный сервис с базой доводов для подачи жалоб в УФАС на закупки по 44-ФЗ</span><br>
					      							</h1>
															
        <div class="ms1-str">
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-1.png" alt="">
                </div>
                Полная<br>
				автоматизация
            </div>
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-2.png" alt="">
                </div>
                Готовые<br>
                доводы
            </div>
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-3.png" alt="">
                </div>
                Подписание<br>
				в браузере
            </div>
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-4.png" alt="">
                </div>
                Мониторинг<br>
                статуса
            </div>
				  </div>
</div>

<div class="mstripe-2">
    <div class="wrapper">
        <h2>
            Подготовить и подать жалобу —<br>
            считанные минуты
        </h2>
        <div class="ms2-str">
            <a href="#pop-start" class="ms2-s-btn open_modal">Начать работу</a><br>
            Для работы с системой используйте вашу ЭП для ЭТП.<br>
            Нет ЭП? Выпустим всего за 3500 руб. <a href="http://gos-partner.ru/tendernoe_obsluzhivanie/poluchenie_ep/">Купить</a>
        </div>
    </div>
</div>

<div class="mstripe-3">
    <div class="wrapper">
        <div class="ms3-macbook">
            <iframe width="715" height="450" src="https://www.youtube.com/embed/n_jg0q-OVZE" frameborder="0" allowfullscreen></iframe>
        </div>
        <h2>
            ФАС-Онлайн — уникальная система
            <span>
                Применение богатого практического опыта обращений в органы ФАС, в совокупности с современными технологиями, сделали систему<br>
                ФАС-Онлайн мощным рабочим инструментом для участников госзакупок
            </span>
        </h2>
        <div class="ms4-str">
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-1.png" alt="">
                </div>
                Средняя скорость<br>
                подготовки жалобы<br>
                6,5 минут
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-2.png" alt="">
                </div>
                Данные заполняются<br>
                автоматически
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-3.png" alt="">
                </div>
                Огромный выбор<br>
                шаблонов жалоб, на<br>
                каждый случай жизни
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-4.png" alt="">
                </div>
                Гарантия корректного<br>
                подписания жалобы и<br>
                отправки ее в УФАС (ФАС)
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-5.png" alt="">
                </div>
                Мониторинг<br>
                статуса жалобы
            </div>
            <div class="ms4-s-b ms4-s-b-smallHeight">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-6.png" alt="">
                </div>
                Все действия онлайн,<br>
                личный кабинет<br>
                доступен 24/7
            </div>
            <div class="ms4-s-b ms4-s-b-smallHeight">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-7.png" alt="">
                </div>
                Онлайн помощь<br>
                юриста в любых<br>
                вопросах
            </div>
            <div class="ms4-s-b ms4-s-b-smallHeight">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-8.png" alt="">
                </div>
                Неограниченное<br>
                количество<br>
                заявителей
            </div>
            <div class="ms4-s-b ms4-s-b-smallHeight">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-9.png" alt="">
                </div>
                Возможность подать<br>
                жалобу от физ. лица,<br>
                ИП  или юр. лица
            </div>
            <div class="ms4-s-b ms4-s-b-smallHeight">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-10.png" alt="">
                </div>
                Автоматическое<br>
                информирование<br>
                при смене статуса
            </div>
        </div>
    </div>
	</div>

<!--<div class="mstripe-4">-->
<!--    <div class="ms4-btm-tar"></div>-->
<!--    <div class="ms4-btm-shd"></div>-->
<!--    <div class="wrapper">-->
<!--    </div>-->
<!--</div>-->

<div class="mstripe-4">
    <div class="ms4-btm-shd"></div>
    <div class="wrapper">

				<h2 id="₽">
						        Условия и тарифы для любых потребностей 
            <span>
                Попробуйте, первая жалоба бесплатно 
            </span><br>
				<a href="#pop-callback" class="open_modal">Заказать звонок</a>
			                  </h2>


                <div class="tariffs_box">
                    <div class="tariffs_item t-i-b">
                        <div class="problem_frequency">— Не жалуюсь, но хочу попробовать</div>
                        <h3>Ябеда</h3>
                        <div class="tariff_price_box">
                            <div class="tariff_price">Бесплатно</div>
                        </div>
                        <ul>
                            <li>1 жалоба</li>
                            <li>1 заявитель</li>
                            <li>помощь юриста</li>
                            <li>постоянная техподдержка</li>
                            <li>база доводов</li>
                        </ul>
                    </div>


                    <div class="tariffs_item t-i-g">
                        <div class="problem_frequency">— Жалуюсь часто, но не регулярно</div>
                        <h3>Участник</h3>
                        <div class="tariff_price_box">
                            <div class="tariff_price " id="tariff_price2">2 500 <span class="rub">i</span></div>
                            <div id="t-price-2"> <div class="sl_label">жалоб</div></div>
                            <div id="t-summ-2" class="t-summ" data-price="500">500 <span class="rub">i</span> / 1 жалоба</div>
                        </div>
                        <ul>
                            <li>оплата за каждую жалобу</li>
                            <li>3 заявителя</li>
                            <li>помощь юриста</li>
                            <li>постоянная техподдержка</li>
                            <li>база доводов</li>
                        </ul>
                    </div>


                    <div class="tariffs_item t-i-r">
                        <div class="problem_frequency">— Жалуюсь всегда и на всех</div>
                        <h3>Жалобщик</h3>
                        <div class="tariff_price_box">
                            <div class="tariff_price" id="tariff_price3">12 000 <span class="rub">i</span></div>
                            <div id="t-price-3"><div class="sl_label">месяцев</div></div>
                            <div id="t-summ-3" class="t-summ" data-price="2000">2 000 <span class="rub">i</span> / месяц</div>
                        </div>
                        <ul>
                            <li>оплата помесячно</li>
                            <li>5 заявителей</li>
                            <li>жалобы без ограничений</li>
                            <li>помощь юриста</li>
                            <li>постоянная техподдержка</li>
                            <li>база доводов</li>
                            <li>практика УФАС</li>
                        </ul>
                    </div>

                </div>



    </div>
</div>

<div class="mstripe-5">
    <div class="wrapper">
        <h2>
            Кто мы и почему нам можно доверять?<br>
            <a href="http://gos-partner.ru" target="_blank">Перейти на сайт</a>
        </h2>
        <div class="ms5-text">
            <span>Госпартнер — специализированная организация, оказывающая всестороннюю помощь участникам государственного заказа и Государственным заказчикам.</span>
            В т.ч. подбор закупок, анализ аукционной и конкурсной документации, подготовку первых и вторых частей заявок, выдачу ЭП, оказываем юридическое сопровождение и предоставляем интересы в органах надзора, а также содействуем в финансовом обеспечении на всех этапах.
        </div>
    </div>
</div>





<!-- popups -->

<!-- popup login -->
<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form action="/login/start" method="post">
        <label class="fontNormal" for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label class="fontNormal" for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
            <span> <a href="/?register" class="" onclick="return true;">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a></span>
        </div>
    </form>
    <div class="modal-close"></div>
</div>

<!-- popup callback -->
<div id="pop-callback" class="modal_div">
    <h2>Заказать звонок</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">Телефон</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="phone">
        <input type="submit" value="Отправить">
    </form>
    <div class="modal-close"></div>
</div>

<!-- popup start -->
 <div id="pop-start" class="modal_div" {% if register %}style="display:block;"{% endif %}>
    <h2>Регистрация</h2>
    <form class="reg-new-user" method="POST">
<!--        <label for="popstrt-inp1">Ваше имя</label>-->
<!--        <input type="text" id="popstrt-inp1" required="required" name="name">-->
        <label class="fontNormal" for="popstrt-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="popstrt-inp1" required="required" name="email">
<!--        <label for="popstrt-inp1">Телефон</label>-->
<!--        <input type="text" id="popstrt-inp1" required="required" name="phone">
        <label class="fontNormal" for="popstrt-inp1">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="password">
        <label class="fontNormal" for="popstrt-inp1">Повторите пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="confpassword">
        <div class="error-reg" style="color:red"></div>-->
        <div class="g-recaptcha inlineBlock" data-sitekey="6LdzsQkUAAAAABZTg2NJB9EVfnY0VUOPGgm9bhlN"></div>
        <label class="reqReg">
            <input type="checkbox" id="popstrt-inp1" class="reqReg__input" required="required" name="offerta" value="1" checked>
            <a href="http://fasonline.ru/public/files/Пользовательское соглашение без финансовой части.pdf">Принимаю условия оферты</a>
        </label>
        <!--<div class="pop-str1">
            <input type="checkbox" id="popstrt-inp2">
            <label for="popstrt-inp2">Согласен с правилами</label>
           <a href="#">Правила использования сервиса</a>
        </div>-->
        <input class="entryBtn" type="submit" value="Зарегистрироваться">
        <div class="already-reg">
            <p>Регистрация в системе подтверждает Ваше согласие с условиями пользовательского соглашения сервиса «ФАС-Онлайн». <a href="http://fasonline.ru/public/files/Пользовательское соглашение без финансовой части.pdf">Просмотреть</a></p>
            <p>Уже зарегистрированы – <a href="#pop-login" class="open_modal" onclick="$('#pop-start').hide()">авторизируйтесь</a></p>
        </div>
    </form>

    <div class="modal-close"></div>
</div>

<!-- popup start -->
<div id="pop-done" class="modal_div modal_div-done">
    <h2>Начать работу</h2>
    <div class="pop-done-txt">
        На указанную вами электронную почту<br>
        test@test.ru отправлено письмо <br>
        для завершения регистрации
    </div>
    <div class="modal-close"></div>
</div>

<style>
    #pop-done,#pop-login {
        padding-right: 0px !important;
    }
</style>

<!-- popup recovery -->
<div id="pop-recovery" class="modal_div modal_div-rec">
    <h2>Восстановление пароля</h2>
    <form class="rec-pass" method="POST">
        <label for="popstrt-inp1">Введите ваш email</label>
        <input type="text" id="popstrt-inp1" required="required" name="email">
        <input type="submit" value="Отправить" style="margin-top: 30px">
    </form>
    <div class="modal-close"></div>
</div>

<div id="pop-rec" class="modal_div modal_div-fin">
    <h2>Восстановление</h2>
    <div class="pop-done-txt">
        На ваш email выслан новый пароль
        <a class="pop-done-txt__link" href="#">Войти</a>
    </div>
    <div class="modal-close"></div>
</div>

<div id="overlay"></div>
<script src="/js/registration_ajax.js"></script>
<script src="/js/login_ajax.js"></script>
<script src="/js/rec_pass.js"></script>
<script src="/js/callback_ajax.js"></script>
<script src="/js/registration_ajax.js"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="js/pips/jquery-ui-slider-pips.min.js"></script>
<script type="text/javascript" src="js/scripts.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter41558219 = new Ya.Metrika({
                    id:41558219,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/41558219" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<!-- BEGIN JIVOSITE CODE {literal} -->
<script type='text/javascript'>
    (function(){ var widget_id = '4B0gHdtFwy';var d=document;var w=window;function l(){
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script>
<!-- {/literal} END JIVOSITE CODE -->
