<div class="mheader">
    <div class="wrapper">
        <div class="mhlogo">
            <a href="#"></a>
        </div>
        <a href="tel:+88001009386" class="mh-phone">8 (800) 100-93-86</a>
        <a href="mailto:info@fas-online.ru" class="mh-mail">info@fas-online.ru</a>
        {% if is_logged_in %}
            <a href="/complaint/index" class="already-logged-in">Вход в систему</a>
        {% else %}
            <a href="#pop-login" class="mh-login open_modal">Вход в систему</a>
        {% endif %}
    </div>
</div>

<div class="mstripe-1">
    <div class="wrapper" style="text-align: center;">
    {{flashSession.output()}}
        <h1>
            Подай жалобу в ФАС легко!<br>
            <span>Единственный в РФ сервис для подачи жалоб в УФАС!</span>
        </h1>
        <div class="ms1-str">
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-1.png" alt="">
                </div>
                Регистриция
            </div>
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-2.png" alt="">
                </div>
                Подготовка<br>
                жалобы
            </div>
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-3.png" alt="">
                </div>
                ЭП в броузере
            </div>
            <div class="ms1-s-b">
                <div class="ms1-s-b-i">
                    <img src="images/icon-ms1-4.png" alt="">
                </div>
                Мониторинг<br>
                статуса
            </div>
        </div>
    </div>
</div>

<div class="mstripe-2">
    <div class="wrapper">
        <h2>
            Подготовить и подать жалобу —<br>
            считанные минуты
        </h2>
        <div class="ms2-str">
            <a href="#pop-start" class="ms2-s-btn open_modal">Начать работу</a><br>
            Для работы с системой используйте вашу ЭП для ЭТП.<br>
            Нет ЭП? Выпустим всего за 7300 руб. <a href="#">Купить</a>
        </div>
    </div>
</div>

<div class="mstripe-3">
    <div class="wrapper">
        <div class="ms3-macbook">
            <div>сюда вставка видео через тег video</div>
        </div>
        <h2>Просто. Профессионально. Уникально.</h2>
        <ul class="ms3-list">
            <li>
                <div class="ms3-l-text">
                    <span>
                        Указываем номер закупки и получаем данные
                    </span>
                    Необходимая информация о закупке и<br>
                    заказчике (организации размещающей заказ)<br>
                    формируется автоматически на основании<br>
                    реестрового номера закупки
                </div>
            </li>
            <li>
                <div class="ms3-l-text">
                    <span>
                        Готовые доводы<br>
                        на любой предмет
                    </span>
                    Более 50 готовых к применению и<br>
                    многократно проверенных доводов на<br>
                    типичные нарушения с возможностью<br>
                    редактирования и дополнения
                </div>
            </li>
            <li>
                <div class="ms3-l-text">
                    <span>
                        Подписывай жалобу<br>
                        в один клик
                    </span>
                    Сформированную жалобу Вашей ЭП прямо<br>
                    в браузере и отправляйте в УФАС. Система<br>
                    автоматически определит<br>
                    подведомственность и отправит<br>
                    корректно подписанную жалобу с<br>
                    гарантией получения ее УФАС
                </div>
            </li>
            <li>
                <div class="ms3-l-text">
                    <span>
                        Следите за судьбой<br>
                        жалоб в личном<br>
                        кабинете
                    </span>
                    Автоматическое информирование при<br>
                    смене статуса. Система сама следит за<br>
                    процессуальными сроками и докладывает<br>
                    Вам о всех событиях.
                </div>
            </li>
            <li>
                <div class="ms3-l-text">
                    <span>
                        Бесплатная<br>
                        юридическая поддержка
                    </span>
                    Сомневаетесь в применяемых нормах<br>
                    Закона, получите бесплатную<br>
                    профессиональную помощь юриста<br>
                    онлайн. Сервис на связи 24 часа в сутки,<br>
                    7 дней в неделю, независимо от<br>
                    профилактических работ на zakupki.gov.ru
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="mstripe-4">
    <div class="ms4-btm-tar"></div>
    <div class="ms4-btm-shd"></div>
    <div class="wrapper">
        <h2>
            ФАС-Онлайн — уникальная система
            <span>
                Применение богатого практического опыта обращений в органы ФАС в совокупности с современными технологиями сделали систему<br>
                ФАС-Онлайн мощным рабочим инструментом для участников госзакупок
            </span>
        </h2>
        <div class="ms4-str">
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-1.png" alt="">
                </div>
                Средняя скорость<br>
                подготовки жалобы<br>
                6,5 минут
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-2.png" alt="">
                </div>
                Данные заполняются<br>
                автоматически
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-3.png" alt="">
                </div>
                Огромный выбор<br>
                шаблонов жалоб, на<br>
                каждый случай жизни
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-4.png" alt="">
                </div>
                Гарантия корректного<br>
                подписания жалобы и<br>
                отправки ее в УФАС (ФАС)
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-5.png" alt="">
                </div>
                Мониторинг<br>
                статуса жалобы
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-6.png" alt="">
                </div>
                Все действия онлайн,<br>
                личный кабинет<br>
                доступен 24/7
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-7.png" alt="">
                </div>
                Онлайн помощь<br>
                юриста в любых<br>
                вопросах
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-8.png" alt="">
                </div>
                Неограниченное<br>
                количество<br>
                заявителей
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-9.png" alt="">
                </div>
                Возможность подать<br>
                жалобу от физ. лица,<br>
                ИП  или юр. лица
            </div>
            <div class="ms4-s-b">
                <div class="ms4-s-b-i">
                    <img src="images/icon-ms4-10.png" alt="">
                </div>
                Автоматическое<br>
                информирование<br>
                при смене статуса
            </div>
        </div>
        <h2>
            Бесплатное тестирование до 1 июня 2016
            <span>
                Пока мы делаем самую лучшую в РФ систему ведения жалоб, наслаждаесь бета версией
            </span><br>
            <a href="#pop-callback" class="open_modal">Заказать звонок</a>
        </h2>
    </div>
</div>

<div class="mstripe-5">
    <div class="wrapper">
        <h2>
            Кто мы и почему нам можно доверять?<br>
            <a href="http://gos-partner.ru" target="_blank">Перейти на сайт</a>
        </h2>
        <div class="ms5-text">
            <span>Госпартнер — специализированная организация, оказывающая всестороннюю помощь участникам государственного заказа и Государственным заказчикам.</span>
            В т.ч. выдачу ЭП, подбор закупок, анализ аукционной и конкурсной документации, подготовку первых и вторых частей заявок, оказываем юридическое сопровождение и предоставляем интересы в органах надзора, а также содействуем в финансовом обеспечении на всех этапах.
        </div>
    </div>
</div>





<!-- popups -->

<!-- popup login -->
<div id="pop-login" class="modal_div">
    <h2>Вход в систему</h2>
    <form action="/login/start" method="post">
        <label for="poplog-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="email">
        <label for="poplog-inp2">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="poplog-inp2" required="required" name="password">
        <input type="submit" value="Войти">
        <div class="link-login">
            <span> <a href="#pop-start" class="open_modal" onclick="$('#pop-login').hide()">Регистрация нового пользователя</a><a href="#pop-recovery" class="open_modal" onclick="$('#pop-login').hide()">Забыли пароль?</a></span>
        </div>
    </form>

    <div class="modal-close"></div>
</div>

<!-- popup callback -->
<div id="pop-callback" class="modal_div">
    <h2>Заказать звонок</h2>
    <form action="/register/callback" method="post">
        <label for="poplog-inp1">Телефон</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="poplog-inp1" required="required" name="phone">
        <input type="submit" value="Отправить">
    </form>
    <div class="modal-close"></div>
</div>

<!-- popup start -->
 <div id="pop-start" class="modal_div">
    <h2>Регистрация</h2>
    <form class="reg-new-user" method="POST">
<!--        <label for="popstrt-inp1">Ваше имя</label>-->
<!--        <input type="text" id="popstrt-inp1" required="required" name="name">-->
        <label class="fontNormal" for="popstrt-inp1">E-mail</label>
        <div class="c-inp-err-t"></div>
        <input type="text" id="popstrt-inp1" required="required" name="email">
<!--        <label for="popstrt-inp1">Телефон</label>-->
<!--        <input type="text" id="popstrt-inp1" required="required" name="phone">-->
        <label class="fontNormal" for="popstrt-inp1">Пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="password">
        <label class="fontNormal" for="popstrt-inp1">Повторите пароль</label>
        <div class="c-inp-err-t"></div>
        <input type="password" id="popstrt-inp1" required="required" name="confpassword">
        <div class="error-reg" style="color:red"></div>
        <div class="g-recaptcha inlineBlock" data-sitekey="6LdzsQkUAAAAABZTg2NJB9EVfnY0VUOPGgm9bhlN"></div>
        <label class="reqReg">
            <input type="checkbox" id="popstrt-inp1" class="reqReg__input" required="required" name="offerta" value="1" checked>
            Принимаю условия оферты
        </label>
        <!--<div class="pop-str1">
            <input type="checkbox" id="popstrt-inp2">
            <label for="popstrt-inp2">Согласен с правилами</label>
           <a href="#">Правила использования сервиса</a>
        </div>-->
        <input class="entryBtn" type="submit" value="Зарегистрироваться">
        <div class="already-reg">
            <p>Уже зарегистрированы – <a href="#pop-login" class="open_modal" onclick="$('#pop-start').hide()">авторизируйтесь</a></p>
        </div>
    </form>

    <div class="modal-close"></div>
</div>

<!-- popup start -->
<div id="pop-done" class="modal_div">
    <h2>Начать работу</h2>
    <div class="pop-done-txt">
        На указанную вами электронную почту<br>
        test@test.ru отправлено письмо для завершения<br>
        регистрации
    </div>
    <div class="modal-close"></div>
</div>

<style>
    #pop-done,#pop-login {
        padding-right: 0px !important;
    }
</style>

<!-- popup recovery -->
<div id="pop-recovery" class="modal_div">
    <h2>Восстановление пароля</h2>
    <form class="rec-pass" method="POST">
        <label for="popstrt-inp1">Введите ваш email</label>
        <input type="text" id="popstrt-inp1" required="required" name="email">
        <input type="submit" value="Отправить" style="margin-top: 30px">
    </form>
    <div class="modal-close"></div>
</div>

<div id="pop-rec" class="modal_div">
    <h2>Восстановление</h2>
    <div class="pop-done-txt">
        На ваш email выслан новый пароль
    </div>
    <div class="modal-close"></div>
</div>

<div id="overlay"></div>
<script src="/js/registration_ajax.js"></script>
<script src="/js/login_ajax.js"></script>
<script src="/js/rec_pass.js"></script>
