{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - АДМИНИСТРАТОРЫ{% endblock %}
{% block body %}
<div class="admin-main-wrap list-logs">
<h1>Логи</h1>
<div class="filter">
    <!--<form id="filter_form" action="/admin/log/index" method="post">
        <div class="left-side">
            <div>Роль</div>
            <div>
                <select id="au" name="au">
                    <option value="all" {% if postdata['au'] == "all" %} selected {% endif %} >Все</option>
                    <option value="администратор" {% if postdata['au'] == "администратор" %} selected {% endif %} >Администратор</option>
                    <option value="пользователь" {% if postdata['au'] == "пользователь" %} selected {% endif %} >Пользователь</option>
                </select>
            </div>
            <div>Дата от</div>
            <div>
                <input type="text" name="datefrom" id="datepicker1" value="{{ postdata['datefrom'] }}">
            </div>
            <input class="submit-button" type="submit" value="Поиск">
        </div>
        <div class="right-side">
            <div>Тип</div>
            <div>
                <select id="type" name="type">
                    <option value="all" {% if postdata['type'] == "all" %} selected {% endif %} >Все</option>
                    {% for type in typelist %}
                    <option value="{{ type['type'] }}" {% if postdata['type'] == type['type'] %} selected {% endif %}>{{ type['type'] }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>До</div>
            <div>
                <input type="text" name="dateto" id="datepicker2" value="{{ postdata['dateto'] }}">
            </div>
        </div>
        <div style="clear: both;"></div>-->
        <!--админ\пользователь
           <select id="au" name="au">
                <option value="all" {% if postdata['au'] == "all" %} selected {% endif %} >Все</option>
                <option value="администратор" {% if postdata['au'] == "администратор" %} selected {% endif %} >Администратор</option>
                <option value="пользователь" {% if postdata['au'] == "пользователь" %} selected {% endif %} >Пользователь</option>
            </select>
        тип
        <select id="type" name="type">
            <option value="all" {% if postdata['type'] == "all" %} selected {% endif %} >Все</option>
            {% for type in typelist %}
            <option value="{{ type['type'] }}" {% if postdata['type'] == type['type'] %} selected {% endif %}>{{ type['type'] }}</option>
            {% endfor %}
        </select>
        дополнительно(номер жалобы)
        <input type="text" name="additionally" id="additionally" value="{{ postdata['additionally'] }}">
        поиск по тексту
        <input type="text" name="textsearch" id="textsearch" value="{{ postdata['textsearch'] }}">
        <br>
        дата от
        <input type="text" name="datefrom" id="datepicker1" value="{{ postdata['datefrom'] }}">
        до
        <input type="text" name="dateto" id="datepicker2" value="{{ postdata['dateto'] }}">-->

        
    <!--</form>-->
    <script>
        $( document ).ready(function() {

            var picker1 = new Pikaday({ field: document.getElementById('datepicker1'),  format: 'YYYY-MM-DD' });

            var picker2 = new Pikaday({ field: document.getElementById('datepicker2'),  format: 'YYYY-MM-DD' });

            $('#au').change(function(){
                $('#filter_form').submit();
            });
            $('#type').change(function(){
                $('#filter_form').submit();
            });
            $('#additionally').change(function(){
                $('#filter_form').submit();
            });
            $('#textsearch').change(function(){
                $('#filter_form').submit();
            });
        });

    </script>
</div>


<div class="admin-lt-content">
    <ul class="lt-content-top">
        <li><span>Роль</span></li>
        <li><span>Тип</span></li>
        <li><span>Сообщение</span></li>
        <li><span>Дата</span></li>
    </ul>
    {% for log in page.items %}
    <ul class="lt-content-main">
        <li>{{ log.au }}</li>
        <li>{{ log.type }}</li>
        <li>{{ log.text }}</li>
        <li>{{ log.date }}</li>
    </ul>
    {% endfor %}
</div>

<div class="admin-table-footer">
    <a href="#">Еще <span>20 логов</span></a>
    <a href="#">Показать все логов (<span>{{page.total_items}}</span>)</a>
</div>
<div class="admin-pagination-box">
    {% if page.current>1 %}{{ link_to("admin/log/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
    <ul>
        {% for page_item in paginator_builder %}
        <li>
            {% if page_item['type'] == 'page' %}
            {{ link_to("admin/log/index?page=" ~ page_item['num'], page_item['num']) }}
            {% elseif page_item['type'] == 'delimer' %}
            <span>...</span>
            {% elseif page_item['type'] == 'current' %}
            <span class="active-pag-page">{{page_item['num']}}</span>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% if page.total_pages > page.current %}{{ link_to("admin/log/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
</div>
</div>
{% endblock %}