<html>
<head>
<title>{% block title %}ФАС ОНЛАЙН{% endblock %}</title>
{% block styles %}
<link rel="stylesheet" href="/css/style.css" />
{% endblock %}
{% block script %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
{% endblock %}
</head>
<body id="backend-login">
<div class="backend-login-wrap">
    <div class="backend-login">
        <h2>Вход в систему</h2>
        <form action="/admin/login/start" method="post">
            <div>
                <label for="email">Логин/Email</label>
                <div>
                    {{ text_field('email') }}
                </div>
            </div>
            <div>
                <label for="password">Пароль</label>
                <div>
                    {{ password_field('password') }}
                </div>
            </div>
            <div>
                {{ submit_button('Войти') }}
            </div>
            <div class="error">
                {{flashSession.output()}}
            </div>
        </form>

    </div>
</div>
</body>
</html>
<style>
    .error{
        color: red;
        margin-top: 327px;
        text-align: center;
    }
</style>