{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - ЛОГИН{% endblock %}
{% block body %}
<form action="/admin/login/start" method="post"><fieldset>
<fieldset>
    <div>
        <label for="email">Логин/Email</label>
        <div>
            {{ text_field('email') }}
        </div>
    </div>
    <div>
        <label for="password">Пароль</label>
        <div>
            {{ password_field('password') }}
        </div>
    </div>
    <div>
        {{ submit_button('Войти') }}
    </div>
</fieldset>
</form>
{% endblock %}
{% block sidemenu %}
{% endblock %}
{% block menu %}
{% endblock %}