<?php
namespace Multiple\Backend\Controllers;

use Phalcon\Mvc\Controller;
use Phalcon\Mvc\Model\Criteria;
use Phalcon\Paginator\Adapter\Model as Paginator;
use Multiple\Backend\Models\User;
use Multiple\Backend\Form\UserForm;
use Multiple\Backend\Models\Applicant;
use Multiple\Backend\Form\ApplicantForm;

class UserprofileController extends ControllerBase
{

    public function indexAction()
    {

    }

    


}