{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Вопросы юристу{% endblock %}
{% block body %}
<div class="admin-main-wrap lawyer-wrap">
    <h1>Вопросы юристу</h1>
    <div class="admin-table">
        <div class="admin-table-head">
            <div class="table-head-left">
                <label for="table-head-new" class="lebel-checkbox">
                    <input type="checkbox" id="table-head-new">
                </label>
                <span>Показывать только новые</span>
            </div>
        </div>
        <div class="admin-table-box">
            <ul class="admin-table-title">
                <li><span>Жалоба</span></li>
                <li><span>Добавлен</span></li>
                <li><span>Вопрос</span></li>
            </ul>
            <ul class="admin-table-body question-list">
                {% for compliant in page.items %}
                <li>
                    <p>{{compliant.complaint_name}}Нарушения по ГОСТ</p>
                    {% set questions = compliant.getComplaintQuestion() %}
                    {% for question in questions %}
                    <ul>
                        <li>{{date('d.m.Y', question.date|strtotime)}}</li>
                        <li><a href="#">{{question.text}}</a></li>
                    </ul>
                    {% endfor %}
                </li>
                {% endfor %}
            </ul>
            {% if page.total_items > item_per_page %}
                <div class="admin-table-footer">
                    {% if page.current * item_per_page < page.total_items %}
                        {% set cnt = page.total_items - (page.current * item_per_page) %}
                        <a href="#" onclick="$('#next_items').submit()">Еще <span>{{ cnt > item_per_page ? 5 : cnt}} вопросов</span></a><!--todo: -->
                        {% else %}
                            <div></div>
                    {% endif %}
                    <a href="#">Показать все вопросы (<span>{{page.total_items}}</span>)</a><!--todo: -->
                </div>
                <form id="next_items" method="post">
                    {{hidden_field('next-portions-items', 'value':5)}}
                </form>
            {% endif %}
        </div>
        <div class="admin-pagination-box">
            {% if page.current>1 %}{{ link_to("admin/lawyer/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
            <ul>
                {% for page_item in paginator_builder %}
                <li>
                    {% if page_item['type'] == 'page' %}
                    {{ link_to("admin/lawyer/index?page=" ~ page_item['num'], page_item['num']) }}
                    {% elseif page_item['type'] == 'delimer' %}
                    <span>...</span>
                    {% elseif page_item['type'] == 'current' %}
                    <span class="active-pag-page">{{page_item['num']}}</span>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% if page.total_pages > page.current %}{{ link_to("admin/lawyer/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
        </div>
    </div>
</div>
{% endblock %}