<!doctype html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>тайтл</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <link href="/css/sidr.css" rel="stylesheet" type="text/css">
    <link href="/css/jquery.mCustomScrollbar.css" rel="stylesheet" type="text/css">
    <link href="/fonts/fonts.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="/js/sidetogglemenu.js"></script>
    <script type="text/javascript" src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript" src="/js/init.js"></script>
    <script type="text/javascript" src="/js/validator.js"></script>
</head>
<body>


<?php echo $this->getContent(); ?>

</body>
</html>