<!doctype html> 
<head>
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <title>тайтл</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/css/phalcon.css" />
    <link rel="stylesheet" href="/css/bootstrap.min.css" />

    <link href="/css/jquery.mCustomScrollbar.css" rel="stylesheet" type="text/css">
    <link href="/fonts/fonts.css" rel="stylesheet" type="text/css">

    <link href="/css/dragula.css" rel="stylesheet" type="text/css">

    <link href="/css/jquery.jscrollpane.css" rel="stylesheet" type="text/css">

    <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <script type="text/javascript" src="/js/jquery.jscrollpane.min.js"></script>

    <script type="text/javascript" src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript" src="/js/dragula.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/js/init.js"></script>
    <script type="text/javascript" src="/js/validator.js"></script>
    <script type="text/javascript" src="/js/complaint.js"></script>
    <script type="text/javascript" src="/js/type_select.js"></script>
    <script type="text/javascript" src="/js/applicant.js"></script>
    <script type="text/javascript" src="/js/index_complaint.js"></script>
    <script type="text/javascript" src="/js/consultation.js"></script>
    <script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
    <script type="application/javascript" src="/js/complaint_edit.js"></script>
    <script type="application/javascript" src="/js/main_script.js"></script>







</head>
<body>


<?php echo $this->getContent();
$this->partial('layouts/footer');?>
<div class="alert-wrap">
    <div class="alert-substrate"></div>
    <div class="alert-box"></div>
</div>
</body>
</html>