<header id="admin-header">
    <div class="admin-name">
        <div><img src="/files/avatars/{{curuser.avatar}}" alt="avatar admin"></div>
        <span>{{curuser.email}}</span>
    </div>
    <div style="text-align: center; float: left; width: 50%;">
        {{flashSession.output()}}
    </div>
    <div class="admin-settings-logout">
        <div class="admin-settings"></div>
        <a href="/admin/login/logout" id="admin-logout"></a>
    </div>
    <article class="admin-settings-modal">
        <div class="admin-set-bg"></div>
        <div class="admin-set-top">
            <p>Настройки администратора</p>
        </div>
        <div class="admin-set-cont">
            <form action="#" method="POST">
                <p>Личные данные</p>
                <label for="download-avatar">
                    <img id="cur-avatar" src="/files/avatars/{{curuser.avatar}}" alt="">
                    <p>Изменить аватар</p>
                    <input type="file" id="download-avatar" onchange="readAvatarURL(this, '#cur-avatar')">
                </label>
                <label for="adm-set-email" class="set-same-lable">
                    <span>E-mail</span>
                    <input type="email" id="adm-set-email" value="{{curuser.email}}">
                </label>
                <label for="adm-set-surname" class="set-same-lable">
                    <p>Фамилия</p>
                    {{text_field('surname', 'value':curuser.surname, 'id':'adm-set-surname')}}
                </label>
                <label for="adm-set-name" class="set-same-lable">
                    <p>Имя</p>
                    {{text_field('name', 'value':curuser.name, 'id':'adm-set-name')}}
                </label>
                <label for="adm-set-patronymic" class="set-same-lable">
                    <p>Отчество</p>
                    {{text_field('patronymic', 'value':curuser.patronymic, 'id':'adm-set-patronymic')}}
                </label>
                <p>Сменить пароль</p>
                <label for="set-oldPas" class="set-same-lable">
                    <span>Старый пароль</span>
                    <input type="password" id="set-oldPass">
                </label>
                <label for="set-newPass" class="set-same-lable">
                    <span>Новый пароль</span>
                    <input type="password" id="set-newPass">
                </label>
                <label for="set-newPass-agane" class="set-same-lable">
                    <span>Новый пароль еще раз</span>
                    <input type="password" id="set-newPass-agane">
                </label>
                <button id="j-profile-save">Сохранить</button>
            </form>
        </div>
    </article>
</header>
<div id="styled-popup-container" class="modal_div">
    <h2></h2>
    <div class="pop-done-txt"></div>
    <div class="modal-close"></div>
</div>
<div id="overlay"></div>
<script type="text/javascript">
    $(".modal-close").click(function(){
        var obj = $(this);
        $('#overlay').fadeOut(400,
            function(){
                $(obj).parent().css('display', 'none');
            });
    });
</script>