{% set cur_controller = dispatcher.getControllerName() %}
{% set cur_action = dispatcher.getActionName() %}
<article class="admin-lm-wrap">
    <a href="/admin/login/start" style="display: block">
        <div class="lm-logo">
            <span>Административная консоль</span>
            <div class="lm-burger">
                <div class="lm-burger-open"></div>
                <div class="lm-burger-close"></div>
            </div>
        </div>
    </a>
    <script>
        $(document).ready(function() {
            $(".form_search").submit(function () {
                var text = $(".searc_val").val();
                text = text.replace(/[^a-zA-ZА-Яа-я0-9-\s]/g, '');
                $(".searc_val").val(text);
            });
        })
    </script>
    <form action="/admin/complaints/index" method="GET" class="form_search">
        <ul class="lm-menu">
            <li{% if cur_controller == 'user' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-user"><input type="checkbox" id="lm-user"></label>
                <a href="/admin/user/index">Пользователи<span>{{menuItemsCount['User']}}</span></a>
            </li>
            <li{% if cur_controller == 'complaints' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-complaints"><input type="checkbox" id="lm-complaints"></label>
                <a href="/admin/complaints/index">Жалобы<span>{{menuItemsCount['Complaint']}}</span></a>
            </li>
            <li{% if cur_controller == 'arguments' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-arguments"><input type="checkbox" id="lm-arguments"></label>
                <a href="/admin/arguments/index">Доводы<span>{{menuItemsCount['Arguments']}}</span></a>
            </li>
            <li{% if cur_controller == 'applicants' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-applicants"><input type="checkbox" id="lm-applicants"></label>
                <a href="/admin/applicants/index">Заявители<span>{{menuItemsCount['Applicant']}}</span></a>
            </li>
            <li{% if cur_controller == 'lawyer' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-ask-lawyer"><input type="checkbox" id="lm-ask-lawyer"></label>
                <a href="/admin/lawyer/index">Вопросы юристу<span>{{menuItemsCount['Question']}}</span></a>
            </li>
            <li{% if cur_controller == 'admins' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-administrators"><input type="checkbox" id="lm-administrators"></label>
                <a href="/admin/admins/index">Администраторы<span>{{menuItemsCount['Admin']}}</span></a>
            </li>
            <li{% if cur_controller == 'log' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-logs"><input type="checkbox" id="lm-logs"></label>
                <a href="/admin/log/index">Логи<span>{{menuItemsCount['Log']}}</span></a>
            </li>
            <li{% if cur_controller == 'ufas' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-ufas"><input type="checkbox" id="lm-ufas"></label>
                <a href="/admin/ufas/index">Данные УФАС<span>{{menuItemsCount['Ufas']}}</span></a>
            </li>
			<li{% if cur_controller == 'tarif' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <a href="/admin/tarif/index">Тарифы<span></span></a>
            </li>
			<li{% if cur_controller == 'order' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <a href="/admin/order/index">Счета<span></span></a>
            </li>
        </ul>
        <div class="lm-search-title" style="font-size: 0px;">
            <p style="color:#222427;">Поиск по выбранному</p>
            <span style="color:#222427;">Выберите категории выше и ищите</span>
        </div>
        <div class="lm-search-box">
            <input type="text" id="lm-search-field" class="searc_val" name="search">
            <input type="submit" id="lm-search-btn"  class="searc_comp" value="">
        </div>
    </form>
</article>