<article class="admin-lm-wrap">
    <div class="lm-logo">
        <span>Административная консоль</span>
        <div class="lm-burger">
            <div class="lm-burger-open"></div>
            <div class="lm-burger-close"></div>
        </div>
    </div>
    <form action="#" method="POST">
        <ul class="lm-menu">
            <li>
                <label for="lm-user"><input type="checkbox" id="lm-user"></label>
                <a href="/admin/user/index">Пользователи</a>
            </li>
            <li>
                <label for="lm-complaints"><input type="checkbox" id="lm-complaints"></label>
                <a href="#">Жалобы</a>
            </li>
            <li>
                <label for="lm-arguments"><input type="checkbox" id="lm-arguments"></label>
                <a href="#">Доводы</a>
            </li>
            <li>
                <label for="lm-applicants"><input type="checkbox" id="lm-applicants"></label>
                <a href="#">Заявители</a>
            </li>
            <li class="lm-menu-active">
                <label for="lm-ask-lawyer"><input type="checkbox" id="lm-ask-lawyer"></label>
                <a href="#">Вопросы юристу<span>34</span></a>
            </li>
            <li>
                <label for="lm-administrators"><input type="checkbox" id="lm-administrators"></label>
                <a href="/admin/admins/index">Администраторы</a>
            </li>
            <li>
                <label for="lm-logs"><input type="checkbox" id="lm-logs"></label>
                <a href="/admin/log/index">Логи</a>
            </li>
        </ul>
        <div class="lm-search-title">
            <p>Поиск по выбранному</p>
            <span>Выберите категории выше и ищите</span>
        </div>
        <div class="lm-search-box">
            <input type="text" id="lm-search-field">
            <input type="submit" id="lm-search-btn" value="">
        </div>
    </form>
</article>