{% set cur_controller = dispatcher.getControllerName() %}
{% set cur_action = dispatcher.getActionName() %}
<article class="admin-lm-wrap">
    <div class="lm-logo">
        <span>Административная консоль</span>
        <div class="lm-burger">
            <div class="lm-burger-open"></div>
            <div class="lm-burger-close"></div>
        </div>
    </div>
    <form action="#" method="POST">
        <ul class="lm-menu">
            <li{% if cur_controller == 'user' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-user"><input type="checkbox" id="lm-user"></label>
                <a href="/admin/user/index">Пользователи</a>
            </li>
            <li{% if cur_controller == 'complaints' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-complaints"><input type="checkbox" id="lm-complaints"></label>
                <a href="/admin/complaints/index">Жалобы</a>
            </li>
            <li{% if cur_controller == 'arguments' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-arguments"><input type="checkbox" id="lm-arguments"></label>
                <a href="/admin/arguments/index">Доводы</a>
            </li>
            <li{% if cur_controller == 'applicants' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-applicants"><input type="checkbox" id="lm-applicants"></label>
                <a href="/admin/applicants/index">Заявители</a>
            </li>
            <li{% if cur_controller == 'lawyer' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-ask-lawyer"><input type="checkbox" id="lm-ask-lawyer"></label>
                <a href="/admin/lawyer/index">Вопросы юристу<span>34</span></a>
            </li>
            <li{% if cur_controller == 'admins' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-administrators"><input type="checkbox" id="lm-administrators"></label>
                <a href="/admin/admins/index">Администраторы</a>
            </li>
            <li{% if cur_controller == 'log' and cur_action == 'index' %} class="lm-menu-active"{% endif %}>
                <label for="lm-logs"><input type="checkbox" id="lm-logs"></label>
                <a href="/admin/log/index">Логи</a>
            </li>
        </ul>
        <div class="lm-search-title">
            <p>Поиск по выбранному</p>
            <span>Выберите категории выше и ищите</span>
        </div>
        <div class="lm-search-box">
            <input type="text" id="lm-search-field">
            <input type="submit" id="lm-search-btn" value="">
        </div>
    </form>
</article>