<article class="admin-popup-wrap" style="display:none;">
    <div class="admin-popup-bg"></div>
    <div class="admin-popup-content">
        <div class="admin-popup-close"></div>
        <h6>Изменить доступ</h6>
        <form action="/admin/admins/permisions/save" id="admin_permissions" method="POST">
            <ul>
                <li>
                    <label for="editUser">Редактирование пользователей
                        <div{%if(permisions['user']['pa']!==false and permisions['user']['pa']['edit']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['user']['pa']!==false and permisions['user']['pa']['edit']==1)%} checked="checked"{%endif%} id="editUser" name="perm['user']['edit']" value='1'>
                    </label>
                </li>
                <li>
                    <label for="usersReading">Чтение пользователей
                        <div{%if(permisions['user']['pa']!==false and permisions['user']['pa']['read']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['user']['pa']!==false and permisions['user']['pa']['read']==1)%} checked="checked"{%endif%} id="usersReading" name="perm['user']['read']">
                    </label>
                </li>
                <li>
                    <label for="editingComplaints">Редактирование жалоб
                        <div{%if(permisions['complaints']['pa']!==false and permisions['complaints']['pa']['edit']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['complaints']['pa']!==false and permisions['complaints']['pa']['edit']==1)%} checked="checked"{%endif%} id="editingComplaints" name="perm['complaints']['edit']">
                    </label>
                </li>
                <li>
                    <label for="readingComplaints">Чтение жалоб
                        <div{%if(permisions['complaints']['pa']!==false and permisions['complaints']['pa']['read']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['complaints']['pa']!==false and permisions['complaints']['pa']['read']==1)%} checked="checked"{%endif%} id="readingComplaints" name="perm['complaints']['read']">
                    </label>
                </li>
                <li>
                    <label for="popupLawyer">Юрист
                        <div{%if(permisions['lawyer']['pa']!==false and permisions['lawyer']['pa']['edit']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['lawyer']['pa']!==false and permisions['lawyer']['pa']['edit']==1)%} checked="checked"{%endif%} id="popupLawyer" name="perm['lawyer']['edit']">
                    </label>
                </li>
                <li>
                    <label for="editingArguments">Редактирование доводов
                        <div{%if(permisions['arguments']['pa']!==false and permisions['arguments']['pa']['edit']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['arguments']['pa']!==false and permisions['arguments']['pa']['edit']==1)%} checked="checked"{%endif%} id="editingArguments" name="perm['arguments']['edit']">
                    </label>
                </li>
                <li>
                    <label for="editingFas">Редактирование данных УФАС
                        <div{%if(permisions['template']['pa']!==false and permisions['template']['pa']['edit']==1)%} style="background-position: 0px bottom;"{%endif%}></div>
                        <input type="checkbox"{%if(permisions['template']['pa']!==false and permisions['template']['pa']['edit']==1)%} checked="checked"{%endif%} id="editingFas" name="perm['template']['edit']">
                    </label>
                </li>
            </ul>
            <button id="j-permisions-save">Сохранить</button>
        </form>
    </div>
</article>