<article class="admin-popup-wrap">
    <div class="admin-popup-bg"></div>
    <div class="admin-popup-content">
        <div class="admin-popup-close"></div>
        <h6>Изменить доступ</h6>
        <form action="#" method="POST">
            <ul>
                <li>
                    <label for="editUser">Редактирование пользователей
                        <div></div>
                        <input type="checkbox" id="editUser">
                    </label>
                </li>
                <li>
                    <label for="usersReading">Чтение пользователей
                        <div></div>
                        <input type="checkbox" id="usersReading">
                    </label>
                </li>
                <li>
                    <label for="editingComplaints">Редактирование жалоб
                        <div></div>
                        <input type="checkbox" id="editingComplaints">
                    </label>
                </li>
                <li>
                    <label for="readingComplaints">Чтение жалоб
                        <div></div>
                        <input type="checkbox" id="readingComplaints">
                    </label>
                </li>
                <li>
                    <label for="popupLawyer">Юрист
                        <div></div>
                        <input type="checkbox" id="popupLawyer">
                    </label>
                </li>
                <li>
                    <label for="editingArguments">Редактирование доводов
                        <div></div>
                        <input type="checkbox" id="editingArguments">
                    </label>
                </li>
                <li>
                    <label for="editingFas">Редактирование данных УФАС
                        <div></div>
                        <input type="checkbox" id="editingFas">
                    </label>
                </li>
            </ul>
            <button>Сохранить</button>
        </form>
    </div>
</article>