

<!--  ECP -->
<script src="/js/ecp/es6-promise.min.js" type="text/javascript"></script>
<script src="/js/ecp/cades.min.js" type="text/javascript"></script>
<script src="/js/jquery.inputmask.bundle.js" type="text/javascript"></script>
<script src="/js/edit_add_applicant.js" type="text/javascript"></script>
<script type="text/javascript">
    Cades.prototype.isChromiumBased = function () {
        var retVal_chrome = navigator.userAgent.match(/chrome/i);
        var isOpera = navigator.userAgent.match(/opr/i);
        return (retVal_chrome != null && retVal_chrome.length > 0) || isOpera != null;
    };
</script>
<!-- <script src="/js/ecp/cades.custom.usage.js" type="text/javascript"></script> -->
<script src="/js/ecp/Custom_low.level.find.cetrificates.js" type="text/javascript"></script>

<!--  ECP -->
<!--<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="c-cnt-pagename">
                Добавления заявителя
            </div>
       <form id="applicant_form" action='/applicant/create' method='post' enctype='multipart/form-data' >
            <div class="c-zayavitel">
                <input id="czv1"  name="type" type="radio" value="urlico"  checked hidden>
                <label for="czv1" id="urlico" class="c-zv-lb1">юридическое лицо</label>
                <input id="czv2" name="type"  type="radio" value="ip" hidden>
                <label for="czv2" id="ip" class="c-zv-lb2">индивидуальный предприниматель</label>
                <input id="czv3" name="type"  type="radio" value="fizlico" hidden>
                <label for="czv3" id="fizlico" class="c-zv-lb3">физическое лицо</label>
            </div>

            <div class="c-zv-frmb ">
                <div class="apllicant-field-container">
                </div>
                <div class="c-zv-f-str2">
                    <label for="czvr11">Прикрепить файлы</label>
                    <input  id="czvr11" name='file[]' type='file' multiple min='1' max='9999' hidden>
                    <div class="c-zv-f-q">
                        ?
                        <div class="c-zv-f-q-t">
                            Полномочия заявителя — это либо решение об избрании руководителя (если руководитель является заявителем), либо доверенность от организации на осуществление действий по подаче жалоб в УФАС (если ЭП выпущена не на единолично исполняющее лицо)
                        </div>
                    </div>
                </div>
                <div class="c-zv-f-str3">
                    <input id="add_applicant" type="submit" value="Сохранить">
                </div>
            </div>


        </div>
    </div>
</div>-->
<div class="content front-applicant">
    <div class="wrapper wrap-with-menuPanel wrap-with-menuPanel-pd">
        <div class="c-cnt-pagename" style="float: none;">Добавить заявителя</div>
        <div class="tabs-block">
            <div class="aplicant-tabs-label">
                <div data-tabsLabel="legal-entity" class="active-tabs-label tabs-ur" onclick="">Юридическое лицо</div>
                <div data-tabsLabel="individual-entrepreneur" class="tabs-ip" onclick="">Индивидуальный предприниматель</div>
                <div data-tabsLabel="physical-face" class="tabs-fl" onclick="">Физическое лицо</div>
            </div>

            <div data-tabs="legal-entity" class="tabs-content active-tabs-content tabcontent-ur">
               
                <form action="/applicant/create" enctype="multipart/form-data" method="POST">
                    {{hidden_field('type', 'value':'urlico')}}
                    {{hidden_field('for_user_id', 'value':for_user_id)}}
                  <!--  <label for="entity-textarea">
                        <div>Полное наименование</div>
                        <textarea name="full-name" id="entity-textarea" style="width: 815px;"></textarea>
                    </label> -->
                    <input type="hidden" value="0" name="ecp" class="ecp_ur">
                    <input type="hidden" value="0" name="ecp_text" class="ecp_text">
                    <label for="entity-short">
                        <div>Краткое наименование</div>
                        <input type="text" name="kratkoe-name" id="entity-short" style="width: 480px;">
                    </label>
                    <label for="entity-inn">
                        <div>ИНН</div>
                        <input type="number" name="inn" id="entity-inn" readonly class="ent-inn" style="width: 260px;">
                    </label>

                    <label for="entity-kpp" style="display: none" id="wrap_kpp">
                        <div>КПП</div>
                        <input type="number" name="kpp" id="entity-kpp" style="width: 260px;">
                    </label>

                    <label for="entity-address">
                        <div>Адрес местонахождения</div>
                        <input type="text" name="address" id="entity-address"  style="width: 810px;">
                    </label>
                    <label for="post-address">
                        <div>Почтовый адрес</div>
                        <input type="text" name="post" id="post-address"  style="width: 610px;">
                    </label>
                    <label for="entity-position">
                        <div>Должность заявителя</div>
                        <input type="text" name="position-fio" id="entity-position" style="width: 480px;">
                    </label>
                    <label for="entity-fio-z">
                        <div>ФИО заявителя</div>
                        <input type="text" name="fio" id="entity-fio-z" style="width: 480px;">
                    </label>
                    <label for="entity-fio-k">
                        <div>ФИО контактного лица</div>
                        <input type="text" name="fio-kontakt-face" id="entity-fio-k" style="width: 480px;">
                    </label>
                    <label for="entity-phone">
                        <div>Контактный факс, телефон</div>
                        <input type="text" placeholder="+7 (123) 123-1212" name="phone" id="entity-phone" style="width: 260px;">
                    </label>
                    <label for="entity-email">
                        <div>E-mail</div>
                        <input type="text" name="email" id="entity-email" style="width: 480px;">
                    </label>
                    <div class="file-attachment tab1">
                        <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                            <div class="text-above">Прикрепить файлы</div>
                            <input id="upload-files" class="upload_f first" data-filedid="first" type="file" name="upload-files[]" accept=".pdf,.rtf,.rar,.zio,.jpg,.jpeg,.png,.bmp,.doc,.docx,.tiff" style="width:100%; height 100%">
                        </div>
                        <div class="file-names">
                            <div class="attached-files"></div>
                        </div>
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery('body').on('change','.tab1 .upload_f', function(){
                                    var classNameInputFile = '';
                                    var cnt = jQuery(this)[0].files.length;
                                    if(cnt > 0){
                                        var count = jQuery('.tab1 .upload_f').length + 1;
                                        classNameInputFile = 'file' + parseInt(Math.random() * 10000);
                                        jQuery(".tab1 .file-wrapper").append('<input id="upload-files" class="upload_f '+ classNameInputFile +'" data-filedid="'+ classNameInputFile + '" type="file" name="upload-files[]" accept=".pdf,.rtf,.rar,.zio,.jpg,.jpeg,.png,.bmp,.doc,.docx,.tiff">');
                                        var upload_file = jQuery(this)[0];
                                        var file_data = upload_file.files[0]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = upload_file.files[0]['size'] / 1024;
                                        jQuery('.tab1 .file-names .attached-files').append('<div id="attached-file-' + count + '" class="attached-file-row"><div class="file-icon ' + get_class_by_file_type(file_type) + '"></div><div class="file-link">' + upload_file.files[0]['name'] + ' (' + file_size.toFixed(2) + ' Кб)</div><div class="delete-file" data-remclass="' + upload_file.getAttribute("data-filedid") + '" title="Удалить файл"></div><div style="clear:both;"></div></div>');
                                        jQuery(this).off('change');
                                        jQuery(this).hide();
                                    }
                                });
                                jQuery('body').on('click','.delete-file', function(){
                                    var className = $(this).attr('data-remclass');
                                    $(this).parent().remove();
                                    $('.' + className).remove();
                                });
                            });
                        </script>
                    </div>
                    <button class="save-tab-form add_applicant">Сохранить изменения</button>
                </form>
            </div>

            <div data-tabs="individual-entrepreneur" class="tabs-content tabcontent-in">
                <form action="/applicant/create" enctype="multipart/form-data" method="POST">
                    {{hidden_field('type', 'value':'indlico')}}
                    {{hidden_field('for_user_id', 'value':for_user_id)}}
<!--                    <label for="entity-textarea">-->
<!--                        <div>Полное наименование</div>-->
<!--                        <textarea name="full-name" id="entity-textarea" style="width: 815px;"></textarea>-->
<!--                    </label>-->
                    <input type="hidden" value="0" name="ecp" class="ecp_ur">
                    <input type="hidden" value="0" name="ecp_text" class="ecp_text">
                    <label for="entity-short">
                        <div>Краткое наименование</div>
                        <input type="text" name="kratkoe-name" id="entity-short" style="width: 480px;">
                    </label>
                    <label for="entity-inn">
                        <div>ИНН</div>
                        <input type="number" name="inn" id="entity-inn" class="ent-inn" readonly style="width: 260px;">
                    </label>
                    <label for="entity-address">
                        <div>Адрес местонахождения</div>
                        <input type="text" name="address" id="entity-address" style="width: 810px;">
                    </label>
                    <label for="entity-position">
                        <div>Должность заявителя</div>
                        <input type="text" name="position-fio" id="entity-position" style="width: 480px;">
                    </label>
                    <label for="post-address">
                        <div>Почтовый адрес</div>
                        <input type="text" name="post" id="post-address"  style="width: 610px;">
                    </label>
                    <label for="entity-fio-z">
                        <div>ФИО заявителя</div>
                        <input type="text" name="fio" id="entity-fio-z" style="width: 480px;">
                    </label>
                    <label for="entity-phone">
                        <div>Контактный факс, телефон</div>
                        <input type="text" placeholder="+7 (123) 123-1212" name="phone" id="entity-phone" style="width: 260px;">
                    </label>
                    <label for="entity-email">
                        <div>E-mail</div>
                        <input type="text" name="email" id="entity-email" style="width: 480px;">
                    </label>
                    <label for="entity-position-k">
                        <div>ФИО контактного лица</div>
                        <input type="text" name="fio-kontakt-face" id="entity-fio-k" style="width: 480px;">
                    </label>
                    <div class="file-attachment tab2">
                        <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                            <div class="text-above">Прикрепить файлы</div>
                            <input id="upload-files" class="upload_f" type="file" multiple name="upload-files[]" style="width:100%; height 100%">
                        </div>
                        <div class="file-names">
                            <div class="attached-files"></div>
                        </div>
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery('body').on('change','.tab2 .upload_f', function(){
                                    var classNameInputFile = '';
                                    var cnt = jQuery(this)[0].files.length;
                                    if(cnt > 0){
                                        var count = jQuery('.tab2 .upload_f').length + 1;
                                        classNameInputFile = 'file' + parseInt(Math.random() * 10000);
                                        jQuery(".tab2 .file-wrapper").append('<input id="upload-files" class="upload_f '+ classNameInputFile +'" data-filedid="'+ classNameInputFile + '" type="file" name="upload-files[]">');
                                        var upload_file = jQuery(this)[0];
                                        var file_data = upload_file.files[0]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = upload_file.files[0]['size'] / 1024;
                                        jQuery('.tab2 .file-names .attached-files').append('<div id="attached-file-' + count + '" class="attached-file-row"><div class="file-icon ' + get_class_by_file_type(file_type) + '"></div><div class="file-link">' + upload_file.files[0]['name'] + ' (' + file_size.toFixed(2) + ' Кб)</div><div class="delete-file" data-remclass="' + upload_file.getAttribute("data-filedid") + '" title="Удалить файл"></div><div style="clear:both;"></div></div>');
                                        jQuery(this).off('change');
                                    }
                                });
                                jQuery('body').on('click','.delete-file', function(){
                                    var className = $(this).attr('data-remclass');
                                    $(this).parent().remove();
                                    $('.' + className).remove();
                                });
                            });
                        </script>
                    </div>
                    <button class="save-tab-form add_applicant">Сохранить изменения</button>
                </form>
            </div>
            <div data-tabs="physical-face" class="tabs-content tabcontent-ph">
                <form action="/applicant/create" enctype="multipart/form-data" method="POST">
                    {{hidden_field('type', 'value':'fizlico')}}
                    {{hidden_field('for_user_id', 'value':for_user_id)}}
					{{hidden_field('entity-inn', 'value':'')}}
					<input type="hidden" value="0" name="ecp" class="ecp_ur">
                    <input type="hidden" value="0" name="ecp_text" class="ecp_text">
                    <label for="entity-fio-z">
                        <div>ФИО заявителя</div>
                        <input type="text" name="fio" id="entity-fio-z" style="width: 480px;">
                    </label>
                    <label for="entity-address">
                        <div>Адрес местонахождения</div>
                        <input type="text" name="address" id="entity-address" style="width: 480px;">
                    </label>
                    <label for="entity-phone">
                        <div>Контактный факс, телефон</div>
                        <input type="text" placeholder="+7 (123) 123-1212"  name="phone" id="entity-phone" style="width: 260px;">
                    </label>
                    <label for="post-address">
                        <div>Почтовый адрес</div>
                        <input type="text" name="post" id="post-address"  style="width: 610px;">
                    </label>
                    <label for="entity-email">
                        <div>E-mail</div>
                        <input type="text" name="email" id="entity-email" style="width: 480px;">
                    </label>
                    <label for="entity-position-k">
                        <div>ФИО контактного лица</div>
                        <input type="text" name="fio-kontakt-face" id="entity-fio-k" style="width: 480px;">
                    </label>
                    <div class="file-attachment tab3">
                        <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                            <div class="text-above">Прикрепить файлы</div>
                            <input id="upload-files"  class="upload_f" type="file" multiple name="upload-files[]" style="width:100%; height 100%">
                        </div>
                        <div class="file-names">
                            <div class="attached-files"></div>
                        </div>
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery('body').on('change','.tab3 .upload_f', function(){
                                    var classNameInputFile = '';
                                    var cnt = jQuery(this)[0].files.length;
                                    if(cnt > 0){
                                        var count = jQuery('.tab3 .upload_f').length + 1;
                                        classNameInputFile = 'file' + parseInt(Math.random() * 10000);
                                        jQuery(".tab3 .file-wrapper").append('<input id="upload-files" class="upload_f '+ classNameInputFile +'" data-filedid="'+ classNameInputFile + '" type="file" name="upload-files[]">');
                                        var upload_file = jQuery(this)[0];
                                        var file_data = upload_file.files[0]['name'].split('.');
                                        var file_type = file_data[file_data.length - 1];
                                        var file_size = upload_file.files[0]['size'] / 1024;
                                        jQuery('.tab3 .file-names .attached-files').append('<div id="attached-file-' + count + '" class="attached-file-row"><div class="file-icon ' + get_class_by_file_type(file_type) + '"></div><div class="file-link">' + upload_file.files[0]['name'] + ' (' + file_size.toFixed(2) + ' Кб)</div><div class="delete-file" data-remclass="' + upload_file.getAttribute("data-filedid") + '" title="Удалить файл"></div><div style="clear:both;"></div></div>');
                                        jQuery(this).off('change');
                                    }
                                });
                                jQuery('body').on('click','.delete-file', function(){
                                    var className = $(this).attr('data-remclass');
                                    $(this).parent().remove();
                                    $('.' + className).remove();
                                });
                            });
                        </script>
                    </div>
                    <button class="save-tab-form add_applicant">Сохранить изменения</button>
                </form>
            </div>
        </div>
    </div>
</div>

<article class="admin-popup-wrap addAppCertificate addAppCertificate-main" style="display:none;">
    <div class="admin-popup-bg"></div>
    <div class="admin-popup-content index-main-popup">
        <div id="import-aplicant" class="admin-popup-close"></div>
        <h6>Импорт заявителя из данных сертификата</h6>
        <div class="addAppCertificate__existingCerList existingCerListBox">
            <div class="select-holder">
                <div class="title-info-box">Выберите сертификат для импорта данных заявителя</div>
                <div class="custom_select">
                    <div class="current-option">
                        <div></div>
                        <span class="existingCerListBox__title">Действителен до [дата] | Имя организации/ФОИ физ.лица</span>
                    </div>
                    <ul class="custom-options">
                        <li class="existingCerListBox__item">Действия заказчика 1</li>
                        <li class="existingCerListBox__item">Действия заказчика 2</li>
                        <li class="existingCerListBox__item">Действия заказчика 3</li>
                        <li class="existingCerListBox__item">Действия заказчика 4</li>
                        <li class="existingCerListBox__item">Действия заказчика 5</li>
                    </ul>
                </div>
            </div>
            <p class="existingCerListBox__dscr">Показаны все сертификаты доступные в КриптоПро на Вашем компьютере</p>
        </div>
        <div class="addAppCertificate__btnHolder">
            <div class="addAppCertificate__addBtn">Добавить</div>
            <div class="addAppCertificate__cancelBtn">Отменить</div>
        </div>
    </div>
</article>

<article class="admin-popup-wrap addAppCertificate addAppCertificate-alert" style="display:none;">
    <div class="admin-popup-bg-hiddenClick"></div>
    <div class="admin-popup-content index-main-popup">
        <h6>Импорт заявителя из данных сертификата</h6>
        <p class="addAppCertificate__dscrAlert">Для работы функции импорта из сертификата необходим плагин КриптоПРО. Установить плагин для Вашего Браузера сейчас?</p>
        <div class="addAppCertificate__btnHolder">
            <div class="addAppCertificate__addBtn"><a href="https://www.cryptopro.ru/products/cades/plugin/get_2_0">Установить</a></div>
            <div class="addAppCertificate__cancelBtn"><a href="/complaint/index">Отменить</a></div>
        </div>
    </div>
</article>


<article class="admin-popup-wrap addAppCertificate addAppCertificate-preloader" style="display:flex;">
    <div class="admin-popup-bg-hiddenClick"></div>
    <div class="admin-popup-content index-main-popup">
        <h6>Ожидание</h6>
        <div class="preloaderHolder">
            <div class="preloader"></div>
        </div>
    </div>
</article>

<article class="admin-popup-wrap addAppCertificate addAppCertificate-main2" style="display:none;">
    <div class="admin-popup-bg-hiddenClick"></div>
    <div class="admin-popup-content index-main-popup">
        <h6>Импорт заявителя из данных сертификата</h6>
        <div class="addAppCertificate__existingCerList existingCerListBox">
            <div class="select-holder">
                <div class="title-info-box">Выберите сертификат для импорта данных заявителя</div>
                <div class="custom_select">
                    <div class="current-option">
                        <div></div>
                        <span class="existingCerListBox__title">Действителен до [дата] | Имя организации/ФОИ физ.лица</span>
                    </div>
                    <ul class=" certificate-box-2 custom-options"></ul>
                </div>
            </div>
            <p class="existingCerListBox__dscr">Показаны все сертификаты доступные в КриптоПро на Вашем компьютере</p>
        </div>
        <div class="addAppCertificate__btnHolder">
            <div class="addAppCertificate__addBtn">Добавить</div>
            <div class="addAppCertificate__cancelBtn"><a href="/complaint/index">Отменить</a></div>
        </div>
    </div>
</article>

