
<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="c-cnt-pagename">
                Добавления заявителя
            </div>
       <form id="applicant_form" action='/applicant/create' method='post' enctype='multipart/form-data' >
            <div class="c-zayavitel">
                <input id="czv1"  name="type" type="radio" value="urlico"  checked hidden>
                <label for="czv1" id="urlico" class="c-zv-lb1">юридическое лицо</label>
                <input id="czv2" name="type"  type="radio" value="ip" hidden>
                <label for="czv2" id="ip" class="c-zv-lb2">индивидуальный предприниматель</label>
                <input id="czv3" name="type"  type="radio" value="fizlico" hidden>
                <label for="czv3" id="fizlico" class="c-zv-lb3">физическое лицо</label>
            </div>

            <div class="c-zv-frmb ">
                <div class="apllicant-field-container">
                </div>
                <div class="c-zv-f-str2">
                    <label for="czvr11">Прикрепить файлы</label>
                    <input  id="czvr11" name='file[]' type='file' multiple min='1' max='9999' hidden>
                    <div class="c-zv-f-q">
                        ?
                        <div class="c-zv-f-q-t">
                            Полномочия заявителя — это либо решение об избрании руководителя (если руководитель является заявителем), либо доверенность от организации на осуществление действий по подаче жалоб в УФАС (если ЭП выпущена не на единолично исполняющее лицо)
                        </div>
                    </div>
                </div>
                <div class="c-zv-f-str3">
                    <input id="add_applicant" type="submit" value="Сохранить">
                </div>
            </div>


        </div>
    </div>
</div>