<div class="content front-applicant">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-cnt-pagename" style="float: none;">Редактировать заявителя</div>
        <div class="tabs-block">
            {{hidden_field('applicant-current-type', 'value':applicant.type)}}
            <div class="aplicant-tabs-label">
                <div onclick="applicant.setUrlico();" data-tabsLabel="legal-entity" {%if applicant.type=="urlico" %}class="active-tabs-label"{%endif%}>Юридическое лицо</div>
                <div onclick="applicant.setIp();" data-tabsLabel="individual-entrepreneur" {%if applicant.type=="ip" %}class="active-tabs-label"{%endif%}>Индивидуальный предприниматель</div>
                <div onclick="applicant.setFizlico();" data-tabsLabel="physical-face"  {%if applicant.type=="fizlico" %}class="active-tabs-label"{%endif%}>Физическое лицо</div>
            </div>
            <div data-tabs="legal-entity" class="tabs-content {%if applicant.type=="urlico" %}active-tabs-content{%endif%}">
                <form action="/applicant/save" method="POST" enctype="multipart/form-data" id="urlico">
                    {{hidden_field('id', 'value':applicant.id)}}
                    {{hidden_field('type', 'value':'urlico')}}
                    <label for="entity-textarea">
                        <div>Полное наименование</div>
                        {{text_area('name_full', 'value':applicant.name_full, 'id':'entity-textarea', "class":"name-full-textarea")}}
                    </label>
                    <label for="entity-short">
                        <div>Краткое наименование</div>
                        {{text_field("name_short", "value":applicant.name_short, "data-name":"kratkoe-name", "class":"upper-text",  "id":"entity-short")}}
                    </label>
                    <label for="entity-inn">
                        <div>ИНН</div>
                        {{numeric_field('inn', 'value':applicant.inn, "id":"entity-inn", "data-name":"number")}}
                    </label>
                    <label for="entity-kpp">
                        <div>КПП</div>
                        {{numeric_field('kpp', 'value':applicant.kpp, "id":"entity-kpp")}}
                    </label>
                    <label for="entity-address">
                        <div>Адрес местонахождения</div>
                        {{text_field('address', 'value':applicant.address, "id":"entity-address", "data-name":"address")}}
                    </label>
                    <label for="entity-position">
                        <div>Должность заявителя</div>
                        {{text_field('position', 'value':applicant.position, "id":"entity-position", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-fio-z">
                        <div>ФИО заявителя</div>
                        {{text_field('fio_applicant', 'value':applicant.fio_applicant, "id":"entity-fio-z", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-position-k">
                        <div>ФИО контактного лица</div>
                        {{text_field('fio_contact_person', 'value':applicant.fio_contact_person, "id":"entity-fio-k", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-phone">
                        <div>Контактный факс, телефон</div>
                        {{numeric_field('telefone', 'value':applicant.telefone, "id":"entity-phone",  "data-name":"number")}}
                    </label>
                    <label for="entity-email">
                        <div>E-mail</div>
                        {{text_field('email', 'value':applicant.email, "id":"entity-email", "data-name":"position-fio" )}}
                    </label>
                    <div class="file-attachment tab1">
                        <div class="file-wrapper"  style="margin-bottom: 20px; height: 30px">
                            <div class="text-above">Прикрепить файлы</div>
                            <input id="upload-files" type="file" class="upload_f" multiple name="upload-files[]" style="width:100%; height 100%">
                        </div>
                        <div class="file-names"></div>
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery('body').on('change','.tab1 .upload_f', function(){
                                    var cnt = jQuery(this)[0].files.length;
                                    if(cnt > 0){
                                        var count = jQuery('.tab1 .upload_f').length + 1;
                                        jQuery(".tab1 .file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                        jQuery(this).off('change');
                                    }
                                    var html = '';
                                    var upload_file = jQuery(this);
                                    for(var i = 0; i < upload_file.length; i++){
                                        for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                            var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                            var file_type = file_data[file_data.length - 1];
                                            var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                            var html = html + '<p>' + jQuery(upload_file[i])[0].files[j]['name'] + '</p>';
                                        }
                                    }
                                    jQuery('.tab1 .file-names').append(html);
                                });
                            });
                        </script>
                        <div class="attached-files">
                            {% if attached_files|count > 0 %}
                                {% for file in attached_files %}
                                    {{ file }}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <button onclick="confirm_change_applicant_type(jQuery('#applicant-current-type').val(), 'urlico');return false;" class="save-tab-form add_applicant">Сохранить изменения</button>
                </form>
            </div>
            <div data-tabs="individual-entrepreneur" class="tabs-content {%if applicant.type=="ip" %}active-tabs-content{%endif%}">
                <form action="/applicant/save" method="POST" enctype="multipart/form-data" id="ip">
                    {{hidden_field('id', 'value':applicant.id)}}
                    {{hidden_field('type', 'value':'ip')}}
                    <label for="entity-textarea">
                        <div>Полное наименование</div>
                        {{text_area('name_full', 'value':applicant.name_full, 'id':'entity-textarea', "class":"name-full-textarea")}}
                    </label>
                    <label for="entity-inn">
                        <div>ИНН</div>
                        {{numeric_field('inn', 'value':applicant.inn, "id":"entity-inn", "data-name":"number")}}
                    </label>
                    <label for="entity-address">
                        <div>Адрес местонахождения</div>
                        {{text_field('address', 'value':applicant.address, "id":"entity-address", "data-name":"address")}}
                    </label>
                    <label for="entity-position">
                        <div>Должность заявителя</div>
                        {{text_field('position', 'value':applicant.position, "id":"entity-position", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-fio-z">
                        <div>ФИО заявителя</div>
                        {{text_field('fio_applicant', 'value':applicant.fio_applicant, "id":"entity-fio-z", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-phone">
                        <div>Контактный факс, телефон</div>
                        {{numeric_field('telefone', 'value':applicant.telefone, "id":"entity-phone",  "data-name":"number")}}
                    </label>
                    <label for="entity-email">
                        <div>E-mail</div>
                        {{text_field('email', 'value':applicant.email, "id":"entity-email", "data-name":"position-fio" )}}
                    </label>
                    <label for="entity-position-k">
                        <div>ФИО контактного лица</div>
                        {{text_field('fio_contact_person', 'value':applicant.fio_contact_person, "id":"entity-fio-k", "data-name":"position-fio")}}
                    </label>
                    <div class="file-attachment tab2">
                        <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                            <div class="text-above" >Прикрепить файлы</div>
                            <input id="upload-files" class="upload_f" type="file" multiple name="upload-files[]" style="width:100%; height 100%">
                        </div>
                        <div class="file-names"></div>
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery('body').on('change','.tab2 .upload_f', function(){
                                    var cnt = jQuery(this)[0].files.length;
                                    if(cnt > 0){
                                        var count = jQuery('.tab2 .upload_f').length + 1;
                                        jQuery(".tab2 .file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                        jQuery(this).off('change');
                                    }
                                    var html = '';
                                    var upload_file = jQuery(this);
                                    for(var i = 0; i < upload_file.length; i++){
                                        for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                            var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                            var file_type = file_data[file_data.length - 1];
                                            var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                            var html = html + '<p>' + jQuery(upload_file[i])[0].files[j]['name'] + '</p>';
                                        }
                                    }
                                    jQuery('.tab2 .file-names').append(html);
                                });
                            });
                        </script>
                        <div class="attached-files">
                            {% if attached_files|count > 0 %}
                                {% for file in attached_files %}
                                    {{ file }}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <button onclick="confirm_change_applicant_type(jQuery('#applicant-current-type').val(), 'ip');return false;"  class="save-tab-form add_applicant">Сохранить изменения</button>
                </form>
            </div>
            <div data-tabs="physical-face" class="tabs-content {%if applicant.type=="fizlico" %}active-tabs-content{%endif%}">
                <form action="/applicant/save" method="POST" enctype="multipart/form-data" id="fizlico">
                    {{hidden_field('id', 'value':applicant.id)}}
                    {{hidden_field('type', 'value':'fizlico')}}
                    <label for="entity-fio-z">
                        <div>ФИО заявителя</div>
                        {{text_field('fio_applicant', 'value':applicant.fio_applicant, "id":"entity-fio-z", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-address">
                        <div>Адрес местонахождения</div>
                        {{text_field('address', 'value':applicant.address, "id":"entity-address", "data-name":"position-fio")}}
                    </label>
                    <label for="entity-phone">
                        <div>Контактный факс, телефон</div>
                        {{numeric_field('telefone', 'value':applicant.telefone, "id":"entity-phone",  "data-name":"number")}}
                    </label>
                    <label for="entity-email">
                        <div>E-mail</div>
                        {{text_field('email', 'value':applicant.email, "id":"entity-email", "data-name":"position-fio" )}}
                    </label>
                    <label for="entity-position-k">
                        <div>ФИО контактного лица</div>
                        {{text_field('fio_contact_person', 'value':applicant.fio_contact_person, "id":"entity-fio-k", "data-name":"position-fio")}}
                    </label>
                    <div class="file-attachment tab3">
                        <div class="file-wrapper" style="margin-bottom: 20px; height: 30px">
                            <div class="text-above">Прикрепить файлы</div>
                            <input id="upload-files" type="file" class="upload_f" multiple name="upload-files[]" style="width:100%; height 100%">
                        </div>
                        <div class="file-names"></div>
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery('body').on('change','.tab3 .upload_f', function(){
                                    var cnt = jQuery(this)[0].files.length;
                                    if(cnt > 0){
                                        var count = jQuery('.tab3 .upload_f').length + 1;
                                        jQuery(".tab3 .file-wrapper").append('<input id="upload-files" class="upload_f" type="file" multiple="multiple" name="upload-files[]">');
                                        jQuery(this).off('change');
                                    }
                                    var html = '';
                                    var upload_file = jQuery(this);
                                    for(var i = 0; i < upload_file.length; i++){
                                        for(var j = 0; j < jQuery(upload_file[i])[0].files.length; j++){
                                            var file_data = jQuery(upload_file[i])[0].files[j]['name'].split('.');
                                            var file_type = file_data[file_data.length - 1];
                                            var file_size = jQuery(upload_file[i])[0].files[j]['size'] / 1024;
                                            var html = html + '<p>' + jQuery(upload_file[i])[0].files[j]['name'] + '</p>';
                                        }
                                    }
                                    jQuery('.tab3 .file-names').append(html);
                                });
                            });
                        </script>
                        <div class="attached-files">
                            {% if attached_files|count > 0 %}
                                {% for file in attached_files %}
                                    {{ file }}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <button onclick="confirm_change_applicant_type(jQuery('#applicant-current-type').val(), 'fizlico');return false;" class="save-tab-form add_applicant">Сохранить изменения</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        var active_tab = $(".tabs-content.active-tabs-content form").attr("id");
        switch (active_tab) {
            case "urlico":
                applicant.setUrlico();
                break;
            case "ip":
                applicant.setIp();
                break;
            case "fizlico":
                applicant.setFizlico();
                break;
            default:
                console.log("Active tab not found");
                break;
        }
    });
</script>
{{hidden_field('delete-file-id', 'value':'')}}
    {{hidden_field('delete-applicant-id', 'value':applicant.id)}}
    <div class="modal fade modal-confirm-change-applicant-type" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">При смене правовой формы будут удалены ранее введённые данные, присущие текущему статусу заявителя, продолжить?</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" applicant-type="" onclick="jQuery('.modal-confirm-change-applicant-type').modal('hide');validateApplicantform();return false;" class="btn btn-primary">Да</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade confirm-deletion-file-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Удалить файл?</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="jQuery('#delete-file-id').val('');">Отмена</button>
            <button type="button" onclick="delete_applicant_file_front()" class="btn btn-primary">Удалить</button>
          </div>
        </div>
      </div>
    </div>