<?php

?>
<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="eror_404">
                <p> Извините, у нас что-то сломалось, но мы уже исправляем это</p>
            </div>
        </div>
</div>
    <style>
        .eror_404{
            margin: 100px 0 100px 0;
            text-align: center;
            color: red;
            font-weight: bolder;
        }
    </style>
