<div class="content">
    <div class="wrapper">
        <div class="c-content">
            <div class="c-cnt-pagename">
                Добавление жалобы
            </div>

            <div class="c-jadd1">
                <div class="c-jadd1-z">
                    <span>Номер извещения</span><br>
                    <i>После ввода номера извещения, все данные о закупке заполняться автоматически</i>
                </div>
                <div class="c-jadd1-f">
                    №<input type="text" value="0173100003412000102" class="c-inp-done">
                    <b>данные Получены!</b>
                </div>
            </div>

            <div class="c-jadd-sp">
                <div class="c-jadd-text">
                    <div class="c-jadd1-z">
                        <span>Данные о закупке</span>
                    </div>
                    <div class="c-jadd-l">
                        <div class="c-jadd-lr-row">
                            <span>Способ проведения закупки</span>
                            Открытый конкурс
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Закупку осуществляет</span>
                            Федеральное казначейство
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Наименование закупки</span>
                            Оказание услуг по эксплуатации Единой информационной системы в сфере закупок
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Контакты</span>
                            Федеральное казначейство<br>
                            РФ, 109097, Москва, ул. Ильинка, 7<br>
                            Шадрин Евгений Игоревич<br>
                            E-mail: zakupki_uis@roskazna.ru<br>
                            Телефон: 7-495-2147529
                        </div>
                    </div>
                    <div class="c-jadd-r">
                        <div class="c-jadd-lr-row">
                            <span>Наименование закупки</span>
                            <div class="c-jadd-lr-sel">
                                <select>
                                    <option>УФАС по г. Санкт-Петербургу</option>
                                    <option>УФАС по г. Санкт-Петербургу</option>
                                    <option>УФАС по г. Санкт-Петербургу</option>
                                </select>
                            </div>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата и время начала подачи заявок</span>
                            20.11.2015 19:30
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата и время окончания подачи заявок</span>
                            11.12.2015 10:00
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата и время вскрытия конвертов с заявками </span>
                            11.12.2015 10:00
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата рассмотрения и оценки заявок на участие в конкурсе</span>
                            14.12.2015
                        </div>
                    </div>
                </div>
                <div class="c-jadd-spoiler folded">
                    <a></a>
                </div>
            </div>

            <div class="c-jadd2">
                <div class="c-jadd2-z">
                    Жалоба на положения аукционной документации
                </div>
                <div class="c-jadd2-f">
                    <span class="c-jadd2-f-z">Сокращенное имя жалобы (для идинтификации внутри системы)</span>
                    <input type="text">
                    <div class="c-jd2-f-dov-b">
                        <div class="c-jd2-f-dov">
                            Доводы жалобы
                        </div>
                        <div class="c-jd2-f-dov-dd">
                            <div class="c-jd2-f-dov-dd-z">
                                Доводы жалобы
                            </div>
                            <div class="c-jd2-f-dov-dd-t">
                                <span>Объединение различных районов <a></a></span>
                                <span>Многократное повторение товаров <a></a></span>
                                <span>Старые ГОСТ <a></a></span>
                                <span>Отсутствие требования опыта в соответствии с ПП №99 <a></a></span>
                            </div>
                            <div class="c-jd2-f-dov-dd-pick mCustomScrollbar">
                                <div class="c-jd2-f-dov-dd-pick-b">
                                    <div class="c-jd2-cb-b">
                                        <span>Несоответствие ГОСТам</span>
                                        <input id="jd2cbb1" type="checkbox" checked hidden>
                                        <label for="jd2cbb1">Установление требований к составным частям</label>
                                        <input id="jd2cbb2" type="checkbox" checked disabled hidden>
                                        <label for="jd2cbb2">Установление требований к составным частям</label>
                                        <input id="jd2cbb3" type="checkbox" disabled hidden>
                                        <label for="jd2cbb3">Установление требований к составным частям</label>
                                        <input id="jd2cbb4" type="checkbox" hidden>
                                        <label for="jd2cbb4">Установление требований к составным частям</label>
                                    </div>
                                    <div class="c-jd2-cb-b">
                                        <span>Несоответствие ГОСТам</span>
                                        <input id="jd2cbb1" type="checkbox" checked hidden>
                                        <label for="jd2cbb1">Установление требований к составным частям</label>
                                        <input id="jd2cbb2" type="checkbox" checked disabled hidden>
                                        <label for="jd2cbb2">Установление требований к составным частям</label>
                                        <input id="jd2cbb3" type="checkbox" disabled hidden>
                                        <label for="jd2cbb3">Установление требований к составным частям</label>
                                        <input id="jd2cbb4" type="checkbox" hidden>
                                        <label for="jd2cbb4">Установление требований к составным частям</label>
                                    </div>
                                    <div class="c-jd2-cb-b">
                                        <span>Несоответствие ГОСТам</span>
                                        <input id="jd2cbb1" type="checkbox" checked hidden>
                                        <label for="jd2cbb1">Установление требований к составным частям</label>
                                        <input id="jd2cbb2" type="checkbox" checked disabled hidden>
                                        <label for="jd2cbb2">Установление требований к составным частям</label>
                                        <input id="jd2cbb3" type="checkbox" disabled hidden>
                                        <label for="jd2cbb3">Установление требований к составным частям</label>
                                        <input id="jd2cbb4" type="checkbox" hidden>
                                        <label for="jd2cbb4">Установление требований к составным частям</label>
                                    </div>
                                    <div class="c-jd2-cb-b">
                                        <span>Несоответствие ГОСТам</span>
                                        <input id="jd2cbb1" type="checkbox" checked hidden>
                                        <label for="jd2cbb1">Установление требований к составным частям</label>
                                        <input id="jd2cbb2" type="checkbox" checked disabled hidden>
                                        <label for="jd2cbb2">Установление требований к составным частям</label>
                                        <input id="jd2cbb3" type="checkbox" disabled hidden>
                                        <label for="jd2cbb3">Установление требований к составным частям</label>
                                        <input id="jd2cbb4" type="checkbox" hidden>
                                        <label for="jd2cbb4">Установление требований к составным частям</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <span class="c-jadd2-f-z">Текст жалобы</span>

                    <div class="c-jd2-f-edit">
                        <div class="c-jd2-f-edit-h">
                            <span class="c-jd2-e-btn1">Aa</span>
                            <span class="c-jd2-e-btn2">Aa</span>
                            <span class="c-jd2-e-btn3">Aa</span>
                            <span class="c-jd2-e-btn4">Aa</span>
                            <span class="c-jd2-e-btn5"></span>
                            <label for="cjd2file" class="c-jd2-e-btn6">Прикрепить файлы</label>
                            <input type="file" id="cjd2file" hidden>
                        </div>
                        <div class="c-jd2-f-edit-text mCustomScrollbar">
                            <div class="c-jd2-f-edit-t">
                             <textarea>text</textarea>
                            </div>
                        </div>
                    </div>

                    <div class="c-jd2-f-save">
                        <input type="submit" value="Сохранить черновик">
                    </div>

                    <div class="c-jd2-f-cat">
                        <input type="radio" name="jd2cat" id="jd2cat1" checked hidden>
                        <label for="jd2cat1">Подписать ЭП</label>
                        <input type="radio" name="jd2cat" id="jd2cat2" hidden>
                        <label for="jd2cat2">Отправить в УФАС</label>
                    </div>
                </div>
            </div>

            <div class="c-jadd3">
                <div class="c-jd3-z">
                    <span>Помощь юриста</span>
                    <i>Не знаете как оформить жалобу, есть вопросы? Обратитесь к нашему юристу.</i>
                </div>
                <div class="c-jd3-f">
                    <textarea></textarea>
                    <input type="submit" value="начать консультацию">
                </div>
            </div>

            <div class="cfooter">
                <div class="wrapper">
                    <div class="cflogo">
                        <a href="#"></a>
                    </div>
                    <div class="cf-str">
                        &copy; ФАС-Онлайн, 2016, при поддержке «Госпартнер»
                        <a href="#">Контакты</a>
                        <a href="#">Помощь</a>
                        <a href="#">О проекте</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>