<div class="content add-complaint-page">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            {{flashSession.output()}}
            <div class="c-cnt-pagename">
                Добавление жалобы
            </div>

            <div class="c-jadd1">
                <div class="c-jadd1-z">
                    <span>Номер извещения</span><br>
                    <i>После ввода номера извещения, все данные о закупке заполнятся автоматически</i>
                </div>
                <div class="c-jadd1-f" id="result_container">
                    №<input id="auction_id" type="text" value="" >
                    <input id="notice_button" type="submit" value="Получить данные">
                    <span class="loading-gif">
                        <img width="30px" height="30px" src="/img/loading.gif">

                     </span>
                </div>
            </div>

            <div class="c-jadd-sp">
                <div class="c-jadd-text">
                    <div class="c-jadd1-z">
                        <span >Данные о закупке</span>
                    </div>
                    <div class="c-jadd-l">
                        <div class="c-jadd-lr-row">
                            <span>Способ проведения закупки</span>
                            <span class="auction-data" id="type"></span>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Закупку осуществляет</span>
                            <span class="auction-data" id="purchases_made"></span>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Наименование закупки</span>
                            <span class="auction-data" id="purchases_name"></span>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Контакты</span>
                            <span class="auction-data" id="contact"></span>
                        </div>
                    </div>
                    <div class="c-jadd-r date-container">



                    </div>
                </div>
                <div class="c-jadd-spoiler folded">
                    <span style="text-transform: uppercase;">Показать подробно</span>
                </div>
            </div>

            <div class="c-jadd2 complaint-main-container">
                <div class="c-jadd2-z complaint-header">

                </div>
                <div class="c-jadd2-f">
                    <span class="c-jadd2-f-z">Сокращенное имя жалобы (для идинтификации внутри системы)</span>
                    <input id="complaint_name" type="text">
                    <div class="c-jd2-f-dov-b">
                        <div class="c-jd2-f-dov">
                            Доводы жалобы
                        </div>
                        <div class="argument_text_container c-jd2-f-dov-dd-t2" >

                        </div>
                        <div class="c-jd2-f-dov-dd">
                            <div class="c-jd2-f-dov-dd-z">
                                Доводы жалобы
                            </div>
                            <div id="argument_text_container" class="argument_text_container c-jd2-f-dov-dd-t" >

                            </div>
                            <div class="c-jd2-f-dov-dd-pick mCustomScrollbar">
                                <div class="c-jd2-f-dov-dd-pick-b category-container">
                                    {% for argument in arguments  %}
                                        {% if argument['category'].cnt > 0 %}
                                            <div class="c-jd2-cb-b category-tamplate category-{{ argument['category'].id }}">
                                                <span>{{ argument['category'].name }}</span>
                                                {% for template in argument['templates']  %}
                                                  <input class="template_checkbox" id="jd2cbb{{ template.id }}" value="{{ template.id }}" category="{{ argument['category'].id }}" type="checkbox"  hidden>
                                                  <label id="template_{{ template.id }}" for="jd2cbb{{ template.id }}">{{ template.name }}</label>
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <span class="c-jadd2-f-z">Текст жалобы</span>

                    <div class="c-jd2-f-edit">
                        <div class="c-jd2-f-edit-h">
                            <div style="float: left; padding-top: 8px;" id="itselem"></div>
                            <div class="complaint-attachment">
                                <div class="file-wrapper">
                                    <div class="text-above">Прикрепить файлы</div>
                                    <input id="upload-files" type="file" multiple name="upload-files[]">
                                </div>
                                
                                <script type="text/javascript">
                                    jQuery(document).ready(function(){
                                        jQuery('#upload-files').change(function(){
                                            var cnt = jQuery('#upload-files')[0].files.length;
                                            var i = 0;
                                            var html = '';
                                            for (i = 0; i < cnt; i++) {
                                                html = html + '<p>' + jQuery('#upload-files')[0].files[i]['name'] + '</p>';
                                            }
                                            jQuery('.file-names').html(html);
                                        });
                                    });
                                </script>
                            </div>
                            <input type="file" id="cjd2file" hidden />
                        </div>
                        <div class="file-names"></div>
                        <div class="c-jd2-f-edit-text mCustomScrollbar">
                            <div id="edit_container" class="c-jd2-f-edit-t">
                           </div>
                        </div>
                    </div>

                    <div class="c-jd2-f-save">
                        <input id="complaint_save" class="complaint_save-blue" type="submit" value="Сохранить черновик">
                    </div>

                    <div class="c-jd2-f-cat">
                        <script type="text/javascript">
                            /*var token = '{{token}}';
                            $(document).on('click', '.trusted-ep', function(){

                                var id = 1;
                                $.ajax({
                                    type: "POST",
                                    url: '/ajax/getlast',
                                    error: function(data){
                                        console.log(data);
                                    },
                                    success: function(data) {
                                        var postdata = {'id[]':parseInt(data), 'logo':'https://net.trusted.ru/static/images/svg/bitrix.svg', 'token':token}
                                        $.ajax({
                                            type: "POST",
                                            url: '/ajax/trusted?command=sign',
                                            dataType: 'json',
                                            cache: false,
                                            data: postdata,
                                            error: function(data){
                                                console.log(data);
                                            },
                                            success: function(data) {
                                                console.log(data);
                                            },
                                            timeout: 120000 // sets timeout to 2 minutes
                                        });
                                    },
                                    timeout: 120000 // sets timeout to 2 minutes
                                });
                            });*/
                        </script>
                        <input type="radio" name="jd2cat" id="jd2cat1" checked hidden>
                        <label class = "trusted-ep" for="jd2cat1">Подписать ЭП</label>
                        <input type="radio" name="jd2cat" id="jd2cat2" hidden>
                        <label for="jd2cat2">Отправить в УФАС</label>
                    </div>
                </div>
            </div>

            <div class="c-jadd3">
                <div class="c-jd3-z">
                    <span>Помощь юриста</span>
                    <i>Не знаете как оформить жалобу, есть вопросы? Обратитесь к нашему юристу.</i>
                </div>
                <div  class="q-container c-jd3-commb">

                </div>
                <div class="c-jd3-f">
                    <textarea id="question_text"></textarea>
                    <input id="question_button" type="submit" value="начать консультацию">
                </div>
            </div>


        </div>
    </div>
</div>

<script>
var templates = {};
{% for argument in arguments  %}
    {% for template in argument['templates']  %}
       templates[{{template.id}}] = '{{template.text}}';
    {% endfor %}
{% endfor %}
</script>