<script src="/js/order_ajax.js"></script>
<script src="/js/ecp/es6-promise.min.js" type="text/javascript"></script>
<script src="/js/ecp/cades.min.js" type="text/javascript"></script>
<script type="text/javascript">
    Cades.prototype.isChromiumBased = function () {
        var retVal_chrome = navigator.userAgent.match(/chrome/i);
        var isOpera = navigator.userAgent.match(/opr/i);
        return (retVal_chrome != null && retVal_chrome.length > 0) || isOpera != null;
    };
</script>
<script src="/js/ecp/Custom_low.level.signFile.js" type="text/javascript"></script>
<script type="application/javascript" src="/js/docx_generator/js/docxtemplater.v2.js"></script>
<script type="application/javascript" src="/js/docx_generator/js/jszip-utils.js"></script>
<script src="/js/bowser.min.js"></script>
<script src="/js/plugin.js"></script>
<!--[if IE]>
<script type="text/javascript" src="/js/docx_generator/js/jszip-utils-ie.js"></script>
<![endif]-->
<script type="text/javascript" src="/js/checkPlugin.js"></script>
<script type="text/javascript" src="/js/RecallComplaint.js"></script>
<script type="text/javascript" src="/js/checkDate.js"></script>
<link rel="stylesheet" href="/css/mystyle.css">

<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="mybox">
        		<div class="tarif">
        			<div class="left">
        				<p>Текущий тариф</p>
        				<h3>{{user_tarif['tarif_name']}}</h3>
        			</div>
        			<div class="right">
        				<p>У вас {% if(user_tarif['tarif_price'] == 0) %}бесплатный {% endif %}тариф "{{user_tarif['tarif_name']}}"<br> <!--Осталось 3 жалобы--></p>
        			</div>
        		</div>
        		<div class="participant">
					{% for index, tarif in tarifs %}
						<div class="tarif_{{tarif['tarif_type']}} {% if index is even %}left{% else %}right{% endif %}">
							<p class="status">- {{tarif['tarif_anounce']}}</p>
							<h3>{{tarif['tarif_name']}}</h3>
							{% if(tarif['tarif_type'] == 'complaint') %}
								<div>
									<p id='lprice_{{index}}' class="price">{{tarif['tarif_price']}} <span></span></p>
									<p id='ltrafic_{{index}}' class="trafic">{{tarif['tarif_price']}} <span></span> / 1 жалоба</p>
								</div>
								<input class="tarif_range_{{tarif['id']}}" id='lrange_{{index}}' type="range" min='1' max='5' step='1' value='1'>
								<script type="text/javascript">
									function funclrange_{{index}}() {
										var lrange_{{index}} = document.getElementById('lrange_{{index}}').value;
										var lprice_{{index}} = document.getElementById('lprice_{{index}}');
										var ltrafic_{{index}} = document.getElementById('ltrafic_{{index}}');
										lrange_{{index}} = +lrange_{{index}};
										var price_sum = ({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*(lrange_{{index}}-1))*lrange_{{index}};
										var price_one = ({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*(lrange_{{index}}-1));
										
										//console.log(price_sum);
										
										lprice_{{index}}.innerHTML = price_sum + ' <span></span>';
                                        ltrafic_{{index}}.innerHTML = price_one + ' <span></span> / 1 жалоба';
										
									}
									lrange_{{index}}.onclick = funclrange_{{index}};
									lrange_{{index}}.onmousemove = funclrange_{{index}};
								</script>
							{% else %}
								<div>
									<p id='rprice_{{index}}' class="price">{{tarif['tarif_price']}} <span></span></p>
									<p id='rtrafic_{{index}}' class="trafic">{{tarif['tarif_price']}} <span></span> / месяц</p>
								</div>
								<input class="tarif_range_{{tarif['id']}}" id='rrange_{{index}}' type="range" min='1' max='12' step='3' value="1">
								
								<script type="text/javascript">
									function funcrrange_{{index}}() {
										var rrange_{{index}} = document.getElementById('rrange_{{index}}').value;
										var rprice_{{index}} = document.getElementById('rprice_{{index}}');
										var rtrafic_{{index}} = document.getElementById('rtrafic_{{index}}');
										rrange_{{index}} = +rrange_{{index}};
										
										switch(rrange_{{index}}) {
											case 1:
												var price_sum = {{tarif['tarif_price']}};
												var price_one = {{tarif['tarif_price']}};
											break;
											case 4:
												var price_sum = ({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*1)*3;
												var price_one = ({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*1);
											break;
											case 7:
												var price_sum = ({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*2)*6;
												var price_one = ({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*2);
											break;
											case 10:
												var price_sum = 15000;//({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*3)*12;//15000;//
												var price_one = 1250;//({{tarif['tarif_price']}}-{{tarif['tarif_discount']}}*3);//price_one = 1250;//
											break;
										}
										
										//console.log(rrange_{{index}});
										
										rprice_{{index}}.innerHTML = price_sum + ' <span></span>';
                                        rtrafic_{{index}}.innerHTML = price_one + ' <span></span> / месяц';
										
									}
									rrange_{{index}}.onclick = funcrrange_{{index}};
									rrange_{{index}}.onmousemove = funcrrange_{{index}};
								</script>
								
							{% endif %}
							<button  class="btn changetarif_btn" rel="{{tarif['id']}}">Перейти к оплате</button>
							{{tarif['tarif_description']}}
						</div>
					
					{% endfor %}
        			
        		</div>
        	</div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var currentPage = 'complaint/changetarif';
</script>


