<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="c-cnt-pagename">
                Важно, нельзя скопировать документацию
            </div>

            <div class="c-jadd1-1">
                <div class="c-jadd1-1-h">
                    <div class="c-jadd1-1-h-l">
                        Номер извещения №{{complaint.auction_id}}
                    </div>
                    <div class="c-jadd1-1-h-r">
                        {% if complaint.status == 'draft' %}
                        <span class="jl-status jl-chernov">Черновик</span>
                        {% endif %}
                        {% if complaint.status == 'justified' %}
                        <span class="jl-status jl-done">Обоснована</span>
                        {% endif %}
                        {% if complaint.status == 'unfounded' %}
                        <span class="jl-status jl-notdone">Необоснована</span>
                        {% endif %}
                        {% if complaint.status == 'under_consideration' %}
                        <span class="jl-status jl-rassmotr">На рассмотрении</span>
                        {% endif %}
                        {% if complaint.status == 'submitted' %}
                        <span class="jl-status jl-podana">Подана</span>
                        {% endif %}
                        {% if complaint.status == 'recalled' %}
                        <span class="jl-status jl-fail">Отозвана</span>
                        {% endif %}
                        {% if complaint.status == 'archive' %}
                        <span class="jl-status jl-archive">Архив</span>
                        {% endif %}
                    </div>

                </div>
                <div class="c-jadd1-1-b">
                    {% if complaint.status == 'draft' %}
                      <a href="/complaint/edit/{{ complaint.id }}?action=edit">Редактировать</a>
                    {% else %}
                    <a class="grey" href="#">Редактировать</a>
                    {% endif %}
                    <a class="button-copy-edit-page" value="{{ complaint.id }}" >Копировать</a>
                    {% if complaint.status == 'submitted' %}
                      <a  href="/complaint/recall/{{ complaint.id }}">Отозвать</a>
                    {% else %}
                        <a class="grey" href="#">Отозвать</a>
                    {% endif %}
                    <a href="#">В архив</a>
                    <a href="#">Удалить</a>
                    {% if complaint.status == 'draft' %} <a href="#" class="c-jadd1-1-b-btn">Отправить в УФАС</a> {%
                    endif %}
                </div>
            </div>
            {% if complaint.status == 'draft' and action_edit === true %}
            <div class="c-jadd1">
                <div class="c-jadd1-z">
                    <span>Номер извещения</span><br>
                    <i>После ввода номера извещения, все данные о закупке заполняться автоматически</i>
                </div>
                <div class="c-jadd1-f" id="result_container">
                    №<input id="auction_id" type="text" value="" >
                    <input id="notice_button" type="submit" value="Получить данные">
                    <span class="loading-gif">
                        <img width="30px" height="30px" src="/img/loading.gif">

                     </span>
                </div>
            </div>
            {% endif %}
            <div class="c-jadd-sp">
                <div class="c-jadd-text">
                    <div class="c-jadd1-z">
                        <span>Данные о закупке</span>
                    </div>
                    <div class="c-jadd-l">
                       <div class="c-jadd-lr-row">
                            <span>Способ проведения закупки</span>
                            <span class="auction-data" id="type">{{ complaint.type }}</span>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Закупку осуществляет</span>
                            <span class="auction-data" id="purchases_made">{{ complaint.purchases_made }}</span>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Наименование закупки</span>
                           <span class="auction-data" id="purchases_name"> {{ complaint.purchases_name }}</span>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Контакты</span>
                           <span class="auction-data" id="contact"> {{ complaint.contact }}</span>
                        </div>
                    </div>
                    <div class="c-jadd-r date-container">

                    </div>
                </div>
                <div class="c-jadd-spoiler folded">
                    <a></a>
                </div>
            </div>

            <div class="c-jadd2">
                <div class="c-jadd2-z">
                    {{ complaint.complaint_name }}
                </div>
                <div class="c-jadd2-f">
                    <div class="c-jd2-f-flist">
                        <div class="c-zv-f-doc">
                            Решение по извещению 127563728493872.doc (125 Кб)
                            <div class="c-zv-f-del"></div>
                        </div>
                        <div class="c-zv-f-pdf">
                            Доказательства.pdf (34 Кб)
                            <div class="c-zv-f-del"></div>
                        </div>
                    </div>
                    <div class="c-jd2-f-edit">
                        <div class="c-jd2-f-edit-text mCustomScrollbar">
                            {% if complaint.status == 'draft' and action_edit === true %}
                                <div contenteditable class="c-jd2-f-edit-t complaint-text">
                                    {{ complaint.complaint_text }}
                                </div>
                            {% else %}
                                <div class="c-jd2-f-edit-t">
                                    {{ complaint.complaint_text }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    {% if complaint.status == 'draft' and action_edit === true %}
                    <div class="c-jd2-f-save">
                        <input id="complaint_edit_save" class="complaint_save-blue" type="submit" value="Сохранить черновик">
                    </div>
                    {% endif %}

                    <div class="c-jd2-f-cat">
                        <input type="radio" name="jd2cat" id="jd2cat1" checked hidden>
                        <label for="jd2cat1">Подписать ЭП</label>
                        <input type="radio" name="jd2cat" id="jd2cat2" hidden>
                        <label for="jd2cat2">Отправить в УФАС</label>
                    </div>
                </div>
            </div>

            <div class="c-jadd3">
                <div class="c-jd3-z">
                    <span>Помощь юриста</span>
                    <i>Не знаете как оформить жалобу, есть вопросы? Обратитесь к нашему юристу.</i>
                </div>

                {% for item in complaint_question %}
                <div class="c-jd3-commb">
                    <div class="c-jd3-cb-usr">
                        {{ item['question'].text}}
                    </div>
                    <div class="c-jd3-cb-answ">
                        {% if item['admin'].id is defined %}
                        <div class="c-jd3-cb-answ-a">
                            <img src="images/img-urist.png" alt="">
                            <b>
                                {{ item['admin'].name }}
                            </b>
                            <i>
                                Ваш юридический<br>
                                консультант
                            </i>
                        </div>
                        {% endif %}
                        <div class="c-jd3-cb-answ-t">
                            {% if item['answer']['id'] is defined %}
                            {{ item['answer']['text'] }}
                            {% else %}
                            Когда наш консультант ответит Вам прийдет уведомление.
                            {% endif %}
                        </div>
                    </div>
                </div>

                {% endfor %}


                <div class="c-jd3-f">
                    <textarea></textarea>
                    <input type="submit" value="начать консультацию">
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    auction.data['complaint_id'] = '{{complaint.id }}';

    auction.data['type'] = '{{complaint.type }}';
    auction.data['purchases_made'] = '{{complaint.purchases_made }}';
    auction.data['purchases_name'] = '{{complaint.purchases_name }}';
    auction.data['contact'] = '{{complaint.contact }}';
    auction.data['nachalo_podachi'] = '{{complaint.nachalo_podachi }}';
    auction.data['okonchanie_podachi'] = '{{complaint.okonchanie_podachi }}';
    auction.data['vskrytie_konvertov'] = '{{complaint.vskrytie_konvertov }}';
    auction.data['data_rassmotreniya'] = '{{complaint.data_rassmotreniya }}';
    auction.data['data_provedeniya'] = '{{complaint.data_provedeniya }}';
    auction.data['okonchanie_rassmotreniya'] = '{{complaint.okonchanie_rassmotreniya }}';
    auction.data['vremya_provedeniya'] = '{{complaint.vremya_provedeniya }}';
    auction.setData();

</script>