<div class="content">
    <div class="wrapper">
        <div class="c-content">
            <div class="c-cnt-pagename">
                Важно, нельзя скопировать документацию
            </div>

            <div class="c-jadd1-1">
                <div class="c-jadd1-1-h">
                    <div class="c-jadd1-1-h-l">
                        Номер извещения №{{complaint.auction_id}}
                    </div>
                    <div class="c-jadd1-1-h-r">
                    {% if complaint.status == 'draft' %}
                    <span class="jl-status jl-chernov">Черновик</span>
                    {% endif %}
                    {% if complaint.status == 'justified' %}
                    <span class="jl-status jl-done">Обоснована</span>
                    {% endif %}
                    {% if complaint.status == 'unfounded' %}
                    <span class="jl-status jl-notdone">Необоснована</span>
                    {% endif %}
                    {% if complaint.status == 'under_consideration' %}
                    <span class="jl-status jl-rassmotr">На рассмотрении</span>
                    {% endif %}
                    {% if complaint.status == 'submitted' %}
                    <span class="jl-status jl-podana">Подана</span>
                    {% endif %}
                    {% if complaint.status == 'recalled' %}
                    <span class="jl-status jl-fail">Отозвана</span>
                    {% endif %}
                    {% if complaint.status == 'archive' %}
                    <span class="jl-status jl-archive">Архив</span>
                    {% endif %}
                    </div>

                </div>
                <div class="c-jadd1-1-b">
                    <a href="#">Редактировать</a>
                    <a href="#">Копировать</a>
                    <a href="#">Отозвать</a>
                    <a href="#">В архив</a>
                    <a href="#">Удалить</a>
                    {% if complaint.status == 'draft' %} <a href="#" class="c-jadd1-1-b-btn">Отправить в УФАС</a> {% endif %}
                </div>
            </div>

            <div class="c-jadd-sp">
                <div class="c-jadd-text">
                    <div class="c-jadd1-z">
                        <span>Данные о закупке</span>
                    </div>
                    <div class="c-jadd-l">
                        <div class="c-jadd-lr-row">
                            <span>Способ проведения закупки</span>
                            {{ complaint.type }}
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Закупку осуществляет</span>
                            {{ complaint.purchases_made }}
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Наименование закупки</span>
                            {{ complaint.purchases_name }}
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Контакты</span>
                            {{ complaint.contact }}
                        </div>
                    </div>
                    <div class="c-jadd-r">
                        <div class="c-jadd-lr-row">
                            <span>Наименование закупки</span>
                            <div class="c-jadd-lr-sel">
                                <select>
                                    <option>УФАС по г. Санкт-Петербургу</option>
                                    <option>УФАС по г. Санкт-Петербургу</option>
                                    <option>УФАС по г. Санкт-Петербургу</option>
                                </select>
                            </div>
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата и время начала подачи заявок</span>
                            {{ complaint.date_start }}
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата и время окончания подачи заявок</span>
                            {{ complaint.date_end }}
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата и время вскрытия конвертов с заявками </span>
                            {{ complaint.date_opening }}
                        </div>
                        <div class="c-jadd-lr-row">
                            <span>Дата рассмотрения и оценки заявок на участие в конкурсе</span>
                            {{ complaint.date_review }}
                        </div>
                    </div>
                </div>
                <div class="c-jadd-spoiler folded">
                    <a></a>
                </div>
            </div>

            <div class="c-jadd2">
                <div class="c-jadd2-z">
                    {{ complaint.complaint_name }}
                </div>
                <div class="c-jadd2-f">
                    <div class="c-jd2-f-flist">
                        <div class="c-zv-f-doc">
                            Решение по извещению 127563728493872.doc (125 Кб) <div class="c-zv-f-del"></div>
                        </div>
                        <div class="c-zv-f-pdf">
                            Доказательства.pdf (34 Кб) <div class="c-zv-f-del"></div>
                        </div>
                    </div>
                    <div class="c-jd2-f-edit">
                        <div class="c-jd2-f-edit-text mCustomScrollbar">
                            <div class="c-jd2-f-edit-t">
                                {{ complaint.complaint_text }}
                            </div>
                        </div>
                    </div>

                    <div class="c-jd2-f-cat">
                        <input type="radio" name="jd2cat" id="jd2cat1" checked hidden>
                        <label for="jd2cat1">Подписать ЭП</label>
                        <input type="radio" name="jd2cat" id="jd2cat2" hidden>
                        <label for="jd2cat2">Отправить в УФАС</label>
                    </div>
                </div>
            </div>

            <div class="c-jadd3">
                <div class="c-jd3-z">
                    <span>Помощь юриста</span>
                    <i>Не знаете как оформить жалобу, есть вопросы? Обратитесь к нашему юристу.</i>
                </div>
                <div class="c-jd3-commb">
                    <div class="c-jd3-cb-usr">
                        — Согласно п.1 ст.58 гл.7 ТК ТС «Страной происхождения товаров считается страна, в которой товары были полностью произведены или подвергнуты достаточной обработке (переработке) в соответствии с критериями, установленными таможенным законодательством таможенного союза.
                    </div>
                    <div class="c-jd3-cb-answ">
                        <div class="c-jd3-cb-answ-a">
                            <img src="images/img-urist.png" alt="">
                            <b>
                                Катерина<br>
                                Ларина
                            </b>
                            <i>
                                Ваш юридический<br>
                                консультант
                            </i>
                        </div>
                        <div class="c-jd3-cb-answ-t">
                            При этом под страной происхождения товаров может пониматься группа стран, либо таможенные союзы стран, либо регион или часть страны, если имеется необходимость их выделения для целей определения страны происхождения товаров».<br><br>
                            При этом под страной происхождения товаров может пониматься группа стран, либо таможенные союзы стран, либо регион или часть страны, если имеется необходимость их выделения для целей определения страны происхождения товаров».<br><br>
                            При этом под страной происхождения товаров может пониматься группа стран, либо таможенные союзы стран, либо регион или часть страны, если имеется необходимость их выделения для целей определения страны происхождения товаров».
                        </div>
                    </div>
                </div>
                <div class="c-jd3-commb">
                    <div class="c-jd3-cb-usr">
                        — Таким образом документом, подтверждающим страну происхождения товара?
                    </div>
                    <div class="c-jd3-cb-answ">
                        <div class="c-jd3-cb-answ-a">
                            <img src="images/img-urist.png" alt="">
                            <b>
                                Катерина<br>
                                Ларина
                            </b>
                            <i>
                                Ваш юридический<br>
                                консультант
                            </i>
                        </div>
                        <div class="c-jd3-cb-answ-t">
                            Ч.2 ст.58 гл.7 ТК ТС «Документами, подтверждающими страну происхождения товаров, являются декларация о происхождении товара или сертификат о происхождении товара».
                        </div>
                    </div>
                </div>
                <div class="c-jd3-f">
                    <textarea></textarea>
                    <input type="submit" value="начать консультацию">
                </div>
            </div>
        </div>
    </div>
</div>