<div id="chsort">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="c-c-sort">
                <div class="c-cs-cb">
                    <input class="select_all_complaint" id="csall" type="checkbox" name="csall" hidden>
                    <label  for="csall">Выбрать все</label>
                </div>
                <div class="c-cs-btns">
                    <a class="button-copy">Копировать</a>

                    <a class="change-status" value="recalled" >Отозвать</a>
                    <a class="change-status" value="archive" >В архив</a>
                    <a class="change-status" value="delete">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
          <!--  <div class="c-cnt-pagename">
                Жалобы от ООО “Парус”
            </div> -->

            <div class="c-c-sort">
                <div class="c-cs-cb">
                    <input class="select_all_complaint" id="csall1" type="checkbox" name="csall1" hidden>
                    <label  for="csall1">Выбрать все</label>
                </div>
                <div class="c-cs-btns">
                    <a class="button-copy">Копировать</a>
                    <a class="button-recall" value="recalled" >Отозвать</a>
                    <a class="change-status" value="archive" >В архив</a>
                    <a class="change-status" value="delete">Удалить</a>
                </div>
            </div>

            <ul class="c-c-jlist">
                {% for complaint in complaints %}
                <li>
                    <div class="c-c-jl-z">
                        <div class="c-c-jl-z-l">
                            <input id="jlist{{ complaint['id'] }}" class="complaint-checkbox" type="checkbox" value="{{ complaint['id'] }}" name="jlist{{ complaint['id'] }}" hidden>
                            <label for="jlist{{ complaint['id'] }}"></label><a href="/complaint/edit/{{ complaint['id'] }}" class="complaint-name">{{ complaint['complaint_name'] }}</a>
                        </div>
                        <div class="c-c-jl-z-r">

                            {% if complaint['status'] == 'draft' %}
                            <span class="jl-status jl-chernov">Черновик</span>
                            {% endif %}
                            {% if complaint['status'] == 'justified' %}
                            <span class="jl-status jl-done">Обоснована</span>
                            {% endif %}
                            {% if complaint['status'] == 'unfounded' %}
                            <span class="jl-status jl-notdone">Необоснована</span>
                            {% endif %}
                            {% if complaint['status'] == 'under_consideration' %}
                            <span class="jl-status jl-rassmotr">На рассмотрении</span>
                            {% endif %}
                            {% if complaint['status'] == 'submitted' %}
                            <span class="jl-status jl-podana">Подана</span>
                            {% endif %}
                            {% if complaint['status'] == 'recalled' %}
                            <span class="jl-status jl-fail">Отозвана</span>
                            {% endif %}
                            {% if complaint['status'] == 'archive' %}
                            <span class="jl-status jl-archive">Архив</span>
                            {% endif %}

                        </div>
                    </div>
                    <div class="c-c-jl-info">
                        <table>
                            <tr>
                                <td>
                                    <span>Жалоба от</span>
                                    {{ complaint['date'] }}<br>
                                    {{ complaint['apname'] }}
                                </td>
                                <td>
                                    <span>На</span>
                                    {{ complaint['purchases_made'] }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span>Закупка №</span>
                                    {{ complaint['auction_id'] }}
                                </td>
                                <td>
                                    <span>Наименование закупки</span>
                                    {{ complaint['purchases_name'] }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </li>
                {% endfor %}

            </ul>


        </div>
    </div>
</div>
<script>
var currentPage = 'complaint/index';
var currentStatus ='{{ status }}';
</script>
