<script src="/js/order_ajax.js"></script>
<script src="/js/ecp/es6-promise.min.js" type="text/javascript"></script>
<script src="/js/ecp/cades.min.js" type="text/javascript"></script>
<script type="text/javascript">
    Cades.prototype.isChromiumBased = function () {
        var retVal_chrome = navigator.userAgent.match(/chrome/i);
        var isOpera = navigator.userAgent.match(/opr/i);
        return (retVal_chrome != null && retVal_chrome.length > 0) || isOpera != null;
    };
</script>
<script src="/js/ecp/Custom_low.level.signFile.js" type="text/javascript"></script>
<script type="application/javascript" src="/js/docx_generator/js/docxtemplater.v2.js"></script>
<script type="application/javascript" src="/js/docx_generator/js/jszip-utils.js"></script>
<script src="/js/bowser.min.js"></script>
<script src="/js/plugin.js"></script>
<!--[if IE]>
<script type="text/javascript" src="/js/docx_generator/js/jszip-utils-ie.js"></script>
<![endif]-->
<script type="text/javascript" src="/js/checkPlugin.js"></script>
<script type="text/javascript" src="/js/RecallComplaint.js"></script>
<script type="text/javascript" src="/js/checkDate.js"></script>
<div id="chsort">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-c-sort">
            <div class="c-cs-cb">
                <input class="select_all_complaint" id="csall" type="checkbox" name="csall" hidden>
                <label for="csall">Выбрать все</label>
            </div>
            <div class="c-cs-btns">
                <a class="button-copy">Копировать</a>
                <a class="button-recall" value="recalled">Отозвать</a>
                {% if menu_status == 'archive' %}
                <a class="change-status set-active" value="activate">Активировать</a>
                {% else %}
                <a class="change-status to-archive" value="archive">В архив</a>
                {% endif %}
                <a class="change-status to-delete" value="delete">Удалить</a>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="wrapper wrap-with-menuPanel">
        <div class="c-content">
            <div class="drawing-complaints">
                <span>Бесплатная юридическая консультация</span>
                <a href="#pop-order" class="open_modal">Получить</a>
            </div>
            <div class="c-c-sort">
                <div class="c-cs-cb">
                    <input class="select_all_complaint" id="csall1" type="checkbox" name="csall1" hidden>
                    <label for="csall1">Выбрать все</label>
                </div>
                <div class="c-cs-btns">
                    <a class="button-copy">Копировать</a>
                    <a class="button-recall button-recallRec" value="recalled">Отозвать</a>
                    {% if menu_status == 'archive' %}
                    <a class="change-status set-active" value="activate">Активировать</a>
                    {% else %}
                    <a class="change-status to-archive" value="archive">В архив</a>
                    {% endif %}
                    <a class="change-status to-delete" value="delete">Удалить</a>
                </div>
            </div>

            <ul class="c-c-jlist">
                {% for complaint in page.items %}
                <li class="{{ complaint['status'] }}">
                    <div class="c-c-jl-z">
                        <div class="c-c-jl-z-l">
                            <input id="jlist{{ complaint['id'] }}" class="complaint-checkbox" type="checkbox" value="{{ complaint['id'] }}" name="jlist{{ complaint['id'] }}" hidden>
                            <label for="jlist{{ complaint['id'] }}"></label>
                            <a href="/complaint/edit/{{ complaint['id'] }}" class="complaint-name">{{ complaint['complaint_name'] }}</a>
                            <input type="hidden" id="current-status" name="current-status" value="{{ complaint['status'] }}">
                        </div>
                        <div class="c-c-jl-z-r">
                            {% if complaint['status'] == 'draft' %}
                            <span class="jl-status jl-chernov">Черновик</span>
                            {% endif %}
                            {% if complaint['status'] == 'justified' %}
                            <span class="jl-status jl-done">Обоснована</span>
                            {% endif %}
                            {% if complaint['status'] == 'unfounded' %}
                            <span class="jl-status jl-notdone">Необоснована</span>
                            {% endif %}
                            {% if complaint['status'] == 'under_consideration' %}
                            <span class="jl-status jl-rassmotr">На рассмотрении</span>
                            {% endif %}
                            {% if complaint['status'] == 'submitted' %}
                            <span class="jl-status jl-podana">Подана</span>
                            {% endif %}
                            {% if complaint['status'] == 'recalled' %}
                            <span class="jl-status jl-fail">Отозвана</span>
                            {% endif %}
							{% if complaint['status'] == 'returned' %}
								<span class="jl-status jl-fail">Возвращена</span>
							{% endif %}
                            {% if complaint['status'] == 'archive' %}
                            <span class="jl-status jl-archive">Архив</span>
                            {% endif %}

                        </div>
                    </div>
                    <div class="c-c-jl-info">
                        <table>
                            <tr>
                                <td>
                                    <span>Жалоба от</span>
                                    {{ date('d.m.Y', complaint['date']|strtotime) }}<br>
                                    {{ complaint['apname'] }}
                                </td>
                                <td>
                                    <span>На</span>
                                    {{ complaint['purchases_made'] }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span>Закупка №</span>
                                    {{ complaint['auction_id'] }}
                                </td>
                                <td>
                                    <span>Наименование закупки</span>
                                    {{ complaint['purchases_name'] }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </li>
                {% endfor %}

            </ul>

            <div class="user-pagination-box">
                {% if count_items==0 and status=='0'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Пока у Вас нет жалоб. Для создания жалобы необходимо
                    <div class="ch-l-i-btn" style="padding:10px; display: inline;float:none; width:263px;">
                        <a style="float:none; padding:10px; " href="/applicant/add">добавить заявителя</a>
                    </div>
                    , после чего нажать на кнопку «Добавить жалобу» в левом верхнем углу».
                </div>
                {% elseif count_items==0 and status=='draft'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Пока Вы не создали ни один черновик жалобы.

                    Для создания жалобы необходимо нажать на кнопку «Добавить жалобу» в левом верхнем углу.
                </div>
                {% elseif count_items==0 and status=='submitted'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Пока у Вас нет поданных жалоб.

                    Как только Вы подпишите и отправите жалобу, она появится в данном разделе.
                </div>
                {% elseif count_items==0 and status=='under_consideration'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Пока Ваших жалоб нет на рассмотрении.

                    Когда Вы подадите жалобу и контрольный орган примет её, она появится в данном разделе.
                </div>
                {% elseif count_items==0 and status=='justified'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Пока у Вас нет жалоб, признанных обоснованными.

                    В случае если контрольный орган признает Вашу жалобу обоснованной (частично обоснованной),

                    она появится в данном разделе.
                </div>
                {% elseif count_items==0 and status=='unfounded'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Ни одна из Ваших жалоб не признана необоснованной.

                    В случае если контрольный орган признает Вашу жалобу необоснованной, она появится в данном

                    разделе.
                </div>
                {% elseif count_items==0 and status=='recalled'%}
                <div style="margin-top:20px; position:relative; text-align:center;">Вы не отзывали свои жалобы после подачи.

                    В случае если жалоба будет со статусом «Подана» или «На рассмотрении» и Вы нажмёте на кнопку

                    «отозвать», то такая жалоба появится в данном разделе.
                </div>
                {% elseif count_items==0 and status=='archive'%}
                <div style="margin-top:20px; position:relative; text-align:center;">В архиве нет жалоб.

                    Вы можете отправить любую свою жалобу в архив, после чего она появится в данном

                    разделе.
                </div>
                {% endif %}

                {% if page.current>1 %}
                {{ link_to("complaint/index?page=" ~ page.before ~ "&status="~status~ "&search="~searhparam, 'Предыдущая', 'id' : 'user-pag-prev') }}
                {% endif %}
                <ul>
                    {% for page_item in paginator_builder %}
                    <li>
                        {% if page_item['type'] == 'page' %}
                        {{ link_to("complaint/index?page=" ~ page_item['num'] ~ "&status="~status~ "&search="~searhparam, page_item['num']) }}
                        {% elseif page_item['type'] == 'delimer' %}
                        <span>...</span>
                        {% elseif page_item['type'] == 'current' %}
                        <span class="active-user-pag-page">{{page_item['num']}}</span>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% if page.total_pages > page.current %}
                {{ link_to("complaint/index?page=" ~ page.next ~ "&status="~status ~ "&search="~searhparam, 'Следующая', 'id' : 'user-pag-next') }}
                {% endif %}
            </div>


        </div>
    </div>
</div>
<script>
    var currentPage = 'complaint/index';
    var currentStatus = '{{ status }}';
</script>

<div id="pop-before-ask-question" class="modal_div">
    <h2></h2>
    <div class="pop-done-txt"></div>
    <div class="modal-close"></div>
</div>

<style>
    .edit-status .admin-popup-content.index-main-popup {
        text-align: center;
    }

    .edit-status .admin-popup-content.index-main-popup p {
        font-size: 25px;
    }

    .edit-status .admin-popup-content.index-main-popup h6 {
        position: relative;
        overflow: hidden;
        padding-bottom: 19px;
        font-size: 31px;
        line-height: 64px;
        font-weight: 100;
        color: #ffffff;
        text-align: center;
    }

    .edit-status .admin-popup-content.index-popup {
        width: 500px;
    }
</style>
<article class="admin-popup-wrap edit-status" style="display:none;">
    <div class="admin-popup-bg"></div>
    <div class="admin-popup-content index-main-popup">
        <div class="admin-popup-close"></div>
        <h6>Выполнено!</h6>
        <p></p>
    </div>
</article>

<div id="pop-order" class="modal_div">
    <h2>Заказ жалобы</h2>
    <form method="post">
        <label class="fontNormal" for="poplog-inp1">Введите номер извещения (заказа)</label>
        <div class="c-inp-err-t"></div>
		<input type="hidden" id="user_phone" name="user_phone" value="{{ user_phone }}" required="required">
        <input type="text" id="poplog-inp1" required="required" name="auction_id" placeholder="Введите номер извещения 19 цифр" maxlength="19"> <!-- pattern="^[0]{1}[\d]{18}$" -->
        <input type="submit" value="Заказать">
    </form>
    <div class="modal-close"></div>
</div>

<div id="pop-empty-phone" class="modal_div">
	<h2>Ошибка</h2>
	<div class="pop-done-txt">
        Ваш запрос не отправлен.<br>
		У пользователя не заполнен телефон.
    </div>
	<div class="modal-close"></div>
</div>

<div id="pop-done" class="modal_div">
    <h2>Начать работу</h2>
    <div class="pop-done-txt">
        Ваш запрос отправлен. Юрист свяжется с<br/> Вами в ближайшее время
    </div>
    <div class="modal-close"></div>
</div>

<div id="pop-delete-complaint" class="modal_div">
    <h2></h2>
    <div class="pop-done-txt">
        Жалоба будет безвозвратно удалена. Продолжить?
        <div class="action-buttons">
            <div class="popup-button apr">Удалить</div>
            <div class="popup-button cnc popup-close">Отменить</div>
        </div>
    </div>
    <div class="modal-close"></div>
</div>

<div id="pop-browser-alert" class="modal_div">
    <h2></h2>
    <div class="pop-done-txt popup-content"></div>
    <div class="action-buttons" style="padding-bottom:40px;">
        <div class="popup-button cnc popup-close" style="background: #00aeef none repeat scroll 0 0; margin: 10px 80px 0; text-align:center;">Закрыть</div>
        <p>&nbsp;</p>
    </div>
    <div class="modal-close"></div>
    <br/>
</div>

<article class="admin-popup-wrap recall-compl-popup" style="display:none;">
    <div class="admin-popup-bg"></div>
    <div class="admin-popup-content index-main-popup">
        <div class="admin-popup-close"></div>
        <h6>Отзыв жалобы</h6>
        <p class="pop-done-txt" style="padding: 0 26px 30px"></p>
        <div class="popupBtn recall-compl">Отозвать</div>
        <div class="popupBtn cancel-recall">Отмена</div>
    </div>
</article>

<article class="admin-popup-wrap addAppCertificate addAppCertificate-alert" style="display:none;">
    <div class="admin-popup-bg-hiddenClick"></div>
    <div class="admin-popup-content index-main-popup">
        <h6>Импорт заявителя из данных сертификата</h6>
        <p class="addAppCertificate__dscrAlert">Для работы функции импорта из сертификата необходим плагин КриптоПРО. Установить плагин для Вашего Браузера сейчас?</p>
        <div class="addAppCertificate__btnHolder">
            <div class="addAppCertificate__addBtn">
                <a href="https://www.cryptopro.ru/products/cades/plugin/get_2_0">Установить</a>
            </div>
            <div class="addAppCertificate__cancelBtn">
                <a href="/complaint/index?status=submitted">Отменить</a>
            </div>
        </div>
    </div>
</article>
