<script src="/js/ecp/es6-promise.min.js" type="text/javascript"></script>
<script src="/js/ecp/cades.min.js" type="text/javascript"></script>
<script src="/js/ecp/cades.usage.js" type="text/javascript"></script>

<head>
    <style>
        .box {
            float: left;
            min-height: 200px;
            margin: 1em;
            display: inline-block;
            vertical-align: top;
        }
    </style>

    

    <!--<script src="./../lib/src/eventListener.polyfill.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cadesplugin_api.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.helper.promise.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.helper.to-array.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.store.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.signed-data.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.signer.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.cp-attribute.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.certificates.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.certificate.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.certificate-status.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.extended-key-usage.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.ekus.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.eku.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.key-usage.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.public-key.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.oid.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.encoded-data.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.private-key.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/src/cades.basic-constraints.js" type="text/javascript"></script>-->
    <!--<script src="./../lib/cades.js" type="text/javascript"></script>-->


</head>
<body>
<fieldset id="certificate-list">
    <legend>Sign message:</legend>
    <div name="certificate-select" class="box" style="width: 25%">
        <label for="certificate-select">List sertif:</label>
        <select id="certificate-select" style="width: 100%" size="10"></select>
        <button id="sign-message" onclick="signMessage('certificate-select', 'certificate-message', 'certificate-signature');">Sign</button>
    </div>
    <div name="content" class="box" style="width: 25%">
        <label for="certificate-message">Sign data</label>
        <textarea id="certificate-message" style="width: 100%; min-height: 200px;">Hello World</textarea>
    </div>
    <div name="signature" class="box" style="width: 40%">
        <label for="certificate-signature">sign in base64</label>
        <textarea id="certificate-signature" style="width: 100%; min-height: 200px;"></textarea>
    </div>
</fieldset>
<fieldset id="sign-file">
    <legend>Sign file:</legend>
    <div name="certificate-select-file" class="box" style="width: 25%">
        <label for="certificate-select-file">List sertif:</label>
        <select id="certificate-select-file" style="width: 100%" size="10"></select>
        <label for="file">Select file:</label>
        <input type="file" onchange="onLoad(event, 'certificate-select-file', 'file-content', 'file-signature')" id="file">
    </div>
    <div name="signature" class="box" style="width: 70%">
        <label for="file-signature">Sign in base64</label>
        <textarea id="file-signature" style="width: 100%; min-height: 200px;"></textarea>
        <input type="hidden" id="file-content"/>
    </div>
</fieldset>
</body>