{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ{% endblock %}
{% block body %}
<!-- ****************** user page ***************** -->
{{flashSession.output()}}
<div class="admin-main-wrap user-page">
    <div class="bread-crumbs-holder">
        <a href="#">Вернуться к списку пользователей</a>
    </div>
    <div class="block-user-editing">
        <form action="/admin/user/save" method="post">
            {{hidden_field('id', 'value':'')}}
            <div class="left-block-editing">
                <span>Данные пользователя</span>
                <label for="fUser">
                    {{text_field('lastname', 'value':'', 'id':'fUser')}}
                </label>
                <label for="iUser">
                    <p>Имя</p>
                    {{text_field('firstname', 'value':'', 'id':'iUser')}}
                </label>
                <label for="oUser">
                    <p>Отчество</p>
                    {{text_field('patronymic', 'value':'', 'id':'oUser')}}
                </label>
                <label for="telFaxUser">
                    <p>Контактный факс, телефон</p>
                    {{ numeric_field('phone', 'value':'', 'id':'telFaxUser')}}
                </label>
                <label for="userEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':'', 'id':'userEmail')}}
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="userPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('password', 'value':'', 'id':'userPass')}}
                </label>
                <label for="sendEmailNotice" class="lebel-checkbox">
                    {{check_field('password', 'value':'', 'id':'sendEmailNotice')}}
                    <p>Отправлять уведомления на e-mail</p>
                </label>
                <label for="userComment">
                    <p>Комментарий админа (только для админа!)</p>
                    {{text_area('admin_comment', 'value':'', 'id':'userComment')}}
                </label>
            </div>
            <div class="delete-or-save">
                <button>Удалить пользователя</button><!--todo-->
                <button>Сохранить изменения</button><!--todo-->
            </div>
        </form>
    </div>
</div>

<script>
    $( document ).ready(function() {
        $( "#password" ).val('');
    });
</script>
{% endblock %}