{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ{% endblock %}
{% block body %}
<!-- ****************** user page ***************** -->
{{flashSession.output()}}
<div class="admin-main-wrap user-page">
    <div class="bread-crumbs-holder">
        <a href="/admin/user/index">Вернуться к списку пользователей</a>
    </div>
    <div class="block-user-editing">
        <form action="/admin/user/create" method="post" id="add-user-form">
            {{hidden_field('id', 'value':'')}}
            <div class="left-block-editing">
                <span>Данные пользователя</span>
                <label for="fUser">
                    <p>Фамилия</p>
                    {{text_field('lastname', 'value':'', 'id':'fUser')}}
                </label>
                <label for="iUser">
                    <p>Имя</p>
                    {{text_field('firstname', 'value':'', 'id':'iUser')}}
                </label>
                <label for="oUser">
                    <p>Отчество</p>
                    {{text_field('patronymic', 'value':'', 'id':'oUser')}}
                </label>
                <label for="telFaxUser">
                    <p>Контактный факс, телефон</p>
                    {{ numeric_field('phone', 'value':'', 'id':'telFaxUser')}}
                </label>
                <label for="userEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':'', 'id':'userEmail')}}
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="userPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('password', 'value':'', 'id':'userPass')}}
                </label>
                <label for="sendEmailNotice" class="lebel-checkbox">
                    {{check_field('sendEmail', 'value':'', 'id':'sendEmailNotice')}}
                    <p>Отправлять уведомления на e-mail</p>
                </label>
                <label for="userComment">
                    <p>Комментарий админа (только для админа!)</p>
                    {{text_area('admin_comment', 'value':'', 'id':'userComment')}}
                </label>
            </div>
            <div class="delete-or-save">
                <button>Сохранить изменения</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function() {
        setTimeout(function(){
            $("#userPass").val("");
            $('#userEmail').val("");
        }, 500);
        $('form .delete-or-save button').click(function(evt){
            evt.preventDefault();
            addUserFormValidator.start();
            if (addUserFormValidator.result) {
                $("#add-user-form").submit();
            } else {
                return false;
            }
        });
    });
    var addUserFormValidator = {
        result: true,
        start: function () {
            this.result = true;
            var field_selector = '#fUser';
            if (!validator.text($(field_selector).val(), 3, 100)) {
               this.showError(field_selector, 'Ошибка! фамилия должна быть от 3 до 100 символов');
               this.result = false;
            } else {
               this.done(field_selector);
            }
            var field_selector = '#iUser';
            if (!validator.text($(field_selector).val(), 2, 100)) {
               this.showError(field_selector, 'Ошибка! Имя должно быть от 2 до 100 символов');
               this.result = false;
            } else {
               this.done(field_selector);
            }
            var field_selector = '#oUser';
            if (!validator.text($(field_selector).val(), 3, 100)) {
               this.showError(field_selector, 'Ошибка! Отчество должно быть от 3 до 100 символов');
               this.result = false;
            } else {
               this.done(field_selector);
            }
            var field_selector = '#telFaxUser';
            if (!validator.numeric($(field_selector).val(), 5, 100)) {
               this.showError(field_selector, 'Ошибка! Поле факс, телефон не может быть пустым');
               this.result = false;
            } else {
               this.done(field_selector);
            }
            var field_selector = '#userEmail';
            if (!validator.email($(field_selector).val())) {
               this.showError(field_selector, 'Ошибка! Неверный E-mail');
               this.result = false;
            } else {
               this.done(field_selector);
            }
            var field_selector = '#userPass';
             if (!validator.text($(field_selector).val(), 4, 100)) {
               this.showError(field_selector, 'Ошибка! Пароль должен быть от 4 до 100 символов');
               this.result = false;
            } else {
               this.done(field_selector);
            }
        },
        done: function (element) {
            $(element).addClass('c-inp-done');
            $(element).parent().children('.c-inp-err-t').remove();
        },
        showError: function (element, msg) {
            this.result = false;
            $(element).removeClass('c-inp-done');
            $(element).addClass('c-inp-error');
            $(element).parent().children('.c-inp-err-t').remove();
            $(element).parent().append('<div class="c-inp-err-t">' + msg + '</div>');

        }
    }
</script>
{% endblock %}