{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАТЬ ПОЛЬЗОВАТЕЛЯ{% endblock %}
{% block body %}
<!-- ****************** user page ***************** -->
{{flashSession.output()}}
<div class="admin-main-wrap user-page">
    <div class="bread-crumbs-holder">
        <a href="#" onclick="history.back();return false;">Вернуться к списку пользователей</a>
    </div>
    <h1>{{edituser.email}}</h1>
    <div class="admin-change-access">
        <span>Тариф пробный до 12.02.2016</span>
        <div class="change-access">Изменить тариф</div>
    </div>
    <div class="block-user-editing">
        <form action="/admin/user/save" method="post">
            {{hidden_field('id', 'value':edituser.id)}}
            <div class="left-block-editing">
                <span>Данные пользователя</span>
                <label for="fUser">
                    <p>ФИО</p>
                    {{text_field('lastname', 'value':edituser.lastname, 'id':'fUser')}}
                </label>
                <label for="iUser">
                    <p>Имя</p>
                    {{text_field('firstname', 'value':edituser.firstname, 'id':'iUser')}}
                </label>
                <label for="oUser">
                    <p>Отчество</p>
                    {{text_field('patronymic', 'value':edituser.patronymic, 'id':'oUser')}}
                </label>
                <label for="telFaxUser">
                    <p>Контактный факс, телефон</p>
                    {{ numeric_field('phone', 'value':edituser.phone, 'id':'telFaxUser')}}
                </label>
                <label for="userEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':edituser.email, 'id':'userEmail')}}
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="userPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('password', 'value':'', 'id':'userPass')}}
                </label>
                <label for="sendEmailNotice" class="lebel-checkbox">
                    {{check_field('password', 'value':'', 'id':'sendEmailNotice')}}
                    <p>Отправлять уведомления на e-mail</p>
                </label>
                <label for="userComment">
                    <p>Комментарий админа (только для админа!)</p>
                    {{text_area('admin_comment', 'value':edituser.admin_comment, 'id':'userComment')}}
                </label>
            </div>
            <div class="delete-or-save">
                <button class="delete">Удалить пользователя</button><!--todo-->
                <button>Сохранить изменения</button><!--todo-->
            </div>
        </form>
    </div>
    <div class="user-top-lt">
        <span>Заявители пользователя {{edituser.email}}</span>
        <div>Создать заявителя</div>
    </div>
    <div class="admin-lt-head">
        <div class="select-all">
            <div></div>Выбрать все
        </div>
        <div class="lt-head-btns">
            <!--<div>Изменить</div>-->
            <div>Заблокировать</div>
            <div>Удалить</div>
        </div>
    </div>
    <div class="admin-lt-content userPageLtContent" id="sort-table">
        <ul class="lt-content-top">
            <li sort-field="sort-name"><span class="sortable">Наименование</span></li>
            <li sort-field="sort-type"><span class="sortable">тип</span></li>
            <li sort-field="sort-inn"><span class="sortable">инн</span></li>
            <li sort-field="sort-fio"><span class="sortable">фио</span></li>
            <li><span>Контактные данные</span></li>
            <li sort-field="sort-complaints"><span class="sortable">Жалобы</span></li>
        </ul>
        {% for applicant in applicants %}
        <ul class="lt-content-main" sort-name="{{applicant['name_full']}}" sort-type="{{applicant['type']}}" sort-inn="{{applicant['inn']}}" sort-fio="{{applicant['fio_applicant']}}" sort-complaints="{{applicant['cnt']}}">
            <li>
                <div class="lt-psevdo-check"></div>
                {{applicant['name_full']}}
            </li>
            <li>
                {% if applicant['type'] == 'urlico' %}
                    юр
                {% elseif applicant['type'] == 'fizlico' %}
                    физ
                {% else %}
                    ип
                {% endif %}
            </li>
            <li>{{applicant['inn']}}</li>
            <li>{{applicant['fio_applicant']}}</li>
            <li>{{applicant['address']}}</li>
            <li>{{applicant['cnt']}}</li>
        </ul>
        {% endfor %}
    </div>
    <div class="appllicant-page">
        <div class="user-top-lt">
            <span>Жалобы пользователя {{edituser.email}}</span>
        </div>
        <div class="admin-lt-holder">
            <div class="admin-lt-head">
                <div class="select-all">
                    <div></div>Выбрать все
                </div>
                <div class="lt-head-btns">
                    <div>Копировать</div>
                    <div>Создать</div>
                    <div>В архив</div>
                    <div>Удалить</div>
                </div>
            </div>
            <div class="admin-lt-content"  id="sort-table-2">
                <ul class="lt-content-top">
                    <li sort-field="sort-name"><span class="sortable-2">Имя жалобы</span></li>
                    <li sort-field="sort-number"><span class="sortable-2">Номер закупки</span></li>
                    <li sort-field="sort-applicant"><span class="sortable-2">Заявитель</span></li>
                    <li sort-field="sort-date"><span class="sortable-2">Дата подачи</span></li>
                    <li sort-field="sort-status"><span class="sortable-2">Статус</span></li>
                </ul>
                {% for complaint in complaints %}
                <ul class="j-user-info lt-content-main {{ edituser.getComplaintColor(complaint['status'])}}" sort-name="{{complaint['complaint_name']}}" sort-number="{{complaint['auction_id']}}" sort-applicant="{{complaint['apname']}}" sort-date="{{complaint['date']|strtotime}}" sort-status="{{complaint['status']}}">
                    <li>
                        <div class="lt-psevdo-check">{{hidden_field('complaint-id', 'value':complaint['id'])}}</div>
                        {{complaint['complaint_name']}}
                    </li>
                    <li>{{complaint['auction_id']}}</li>
                    <li>{{complaint['apname']}}</li>
                    <li>{{date('d.m.Y', complaint['date']|strtotime)}}</li>
                    <!--<li class="j-user-status-info">
                        <div class="appll-status-icon">
                        <input class="j-comlient-status" name="status" type="hidden" value="{{complaint['status']}}">
                        </div>
                        <div class="close-status-list">Сменить статус</div>
                    </li>-->
                    <li class='with-dropdown'>
                        <div class="dropdown">
                          <div id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{edituser.getComplaintStatus(complaint['status'], TRUE)}}
                          </div>
                          <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li class="header-dropdown">Сменить статус<span class="caret"></span></li>
                            <li>{{edituser.getAllStatuses(0)}}</li>
                            <li>{{edituser.getAllStatuses(1)}}</li>
                            <li>{{edituser.getAllStatuses(2)}}</li>
                            <li>{{edituser.getAllStatuses(3)}}</li>
                            <li>{{edituser.getAllStatuses(4)}}</li>
                            <li>{{edituser.getAllStatuses(5)}}</li>
                            <li>{{edituser.getAllStatuses(6)}}</li>
                          </ul>
                        </div>
                    </li>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script>
    $( document ).ready(function() {
        $( "#password" ).val('');
    });
</script>
{% endblock %}