{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАТЬ ПОЛЬЗОВАТЕЛЯ{% endblock %}
{% block body %}
<!-- ****************** user page ***************** -->
{{flashSession.output()}}
{{flashSession.output()}}
<script type="text/javascript" src="/js/input_mask.js"></script>
<script>
    $(document).ready(function() {
        $('input[name="mobile_phone"]').mask("+7 (999) 999-9999");
    });
</script>
<div class="admin-main-wrap user-page">
    <div class="bread-crumbs-holder">
        <a href="/admin/user/index">Вернуться к списку пользователей</a>
    </div>
    <h1>{{edituser.email}}</h1>
    <div class="admin-change-access">
        <span>Тариф пробный до 12.02.2016</span>
        <div class="change-access">Изменить тариф</div>
    </div>
    <div class="block-user-editing">
        <form action="/admin/user/save" method="post" id="user-form">
            {{hidden_field('id', 'value':edituser.id)}}
            <div class="left-block-editing">
                <span>Данные пользователя</span>
                <label for="fUser">
                    <p>Как к вам обращаться</p>
                    {{text_field('conversion', 'value':edituser.conversion, 'id':'fUser')}}
                </label>
                <label for="telFaxUser">
                    <p>Телефон</p>
                    {{ text_field('mobile_phone', 'value':edituser.mobile_phone, 'id':'mobile_phone')}}
                </label>
                <label for="userEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':edituser.email, 'id':'userEmail')}}
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="userPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('password', 'value':'', 'id':'userPass')}}
                </label>
                <label for="sendEmailNotice" class="lebel-checkbox">
                    {{check_field('notifications', 'value':edituser.notifications, 'id':'sendEmailNotice')}}
                    <p>Отправлять уведомления на e-mail</p>
                </label>
                <label for="userComment">
                    <p>Комментарий админа (только для админа!)</p>
                    {{text_area('admin_comment', 'value':edituser.admin_comment, 'id':'userComment')}}
                </label>
            </div>
            <div class="delete-or-save">
                <button class="delete" onclick="">Удалить пользователя</button>
                <button>Сохранить изменения</button>
            </div>
        </form>
    </div>
    <div class="user-top-lt">
        <span>Заявители пользователя {{edituser.email}}</span>
        {{link_to("admin/applicants/add?user=" ~ edituser.id, '<div>Создать заявителя</div>')}}
    </div>
    <div class="admin-lt-head">
        <div class="select-all">
            <div></div>Выбрать все
        </div>
        <div class="lt-head-btns applicants-part-user-edit">
            <div class="block-applicant disabled-btn" onclick="block_unblock_user_applicant(1)">Заблокировать</div>
            <div class="unblock-applicant disabled-btn" onclick="block_unblock_user_applicant(0)">Разблокировать</div>
            <div class="disabled-btn" id="delete-button">Удалить</div>
        </div>
        <div class="modal fade confirm-deletion-applicant-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Удалить заявителя?</h4>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" onclick="delete_user_applicants()" class="btn btn-primary">Удалить</button>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="admin-lt-content userPageLtContent" id="sort-table">
        <ul class="lt-content-top">
            <li sort-field="sort-name"><span class="sortable">Наименование</span></li>
            <li sort-field="sort-type"><span class="sortable">тип</span></li>
            <li sort-field="sort-inn"><span class="sortable">инн</span></li>
            <li sort-field="sort-fio"><span class="sortable">фио</span></li>
            <li><span>Контактные данные</span></li>
            <li sort-field="sort-complaints"><span class="sortable">Жалобы</span></li>
        </ul>
        {% for applicant in applicants %}
        <ul class="lt-content-main {% if applicant['is_blocked'] == 0 %} hidden-arg {% endif %}" sort-name="{{applicant['name_short']}}" sort-type="{{applicant['type']}}" sort-inn="{{applicant['inn']}}" sort-fio="{{applicant['fio_applicant']}}" sort-complaints="{{applicant['cnt']}}">
            <li>
                <div class="lt-psevdo-check">{{hidden_field('applicant-id', 'value':applicant['id'])}}</div>
                {{applicant['name_short']}}
            </li>
            <li>
                {% if applicant['type'] == 'urlico' %}
                    юр
                {% elseif applicant['type'] == 'fizlico' %}
                    физ
                {% else %}
                    ип
                {% endif %}
            </li>
            <li>{{applicant['inn']}}</li>
            <li>{{applicant['fio_applicant']}}</li>
            <li>{{applicant['address']}}</li>
            <li>{{applicant['cnt']}}</li>
        </ul>
        {% endfor %}
    </div>
    <div class="appllicant-page complaints-list">
        <div class="user-top-lt">
            <span>Жалобы пользователя {{edituser.email}}</span>
        </div>
        <div class="admin-lt-holder">
            <div class="admin-lt-head">
                <div class="select-all">
                    <div></div>Выбрать все
                </div>
                <div class="lt-head-btns">
                    <div class="disabled-btn copy-complaint" onclick="changeStatusInUserComplaintList('copy')">Копировать</div>
                    <div class="disabled-btn" onclick="changeStatusInUserComplaintList('recalled')">Отозвать</div>
                    <div class="disabled-btn" onclick="changeStatusInUserComplaintList('archive')">В архив</div>
                    <div class="disabled-btn" id="delete-button">Удалить</div>
                </div>
            </div>
            <div class="modal fade confirm-deletion-complaint-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удалить выбранные жалобы?</h4>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" onclick="delete_complaints()" class="btn btn-primary">Удалить</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="admin-lt-content"  id="sort-table-2">
                <ul class="lt-content-top">
                    <li sort-field="sort-name"><span class="sortable-2">Имя жалобы</span></li>
                    <li sort-field="sort-number"><span class="sortable-2">Номер закупки</span></li>
                    <li sort-field="sort-applicant"><span class="sortable-2">Заявитель</span></li>
                    <li sort-field="sort-date"><span class="sortable-2">Дата подачи</span></li>
                    <li sort-field="sort-status"><span class="sortable-2">Статус</span></li>
                </ul>
                {% for complaint in complaints %}
                <ul class="j-user-info lt-content-main {{ edituser.getComplaintColor(complaint['status'])}}" sort-name="{{complaint['complaint_name']}}" sort-number="{{complaint['auction_id']}}" sort-applicant="{{complaint['apname']}}" sort-date="{{complaint['date']|strtotime}}" sort-status="{{complaint['status']}}">
                    <li>
                        <div class="lt-psevdo-check">{{hidden_field('complaint-id', 'value':complaint['id'])}}</div>
                        {{complaint['complaint_name']}}
                    </li>
                    <li>{{complaint['auction_id']}}</li>
                    <li>{{complaint['apname']}}</li>
                    <li>{{date('d.m.Y', complaint['date']|strtotime)}}</li>
                    <!--<li class="j-user-status-info">
                        <div class="appll-status-icon">
                        <input class="j-comlient-status" name="status" type="hidden" value="{{complaint['status']}}">
                        </div>
                        <div class="close-status-list">Сменить статус</div>
                    </li>-->
                    <li class='with-dropdown'>
                        <div class="dropdown">
                          <div id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{edituser.getComplaintStatus(complaint['status'], TRUE)}}
                          </div>
                          <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li class="header-dropdown">Сменить статус<span class="caret"></span></li>
                            <li>{{edituser.getAllStatuses(0)}}</li>
                            <li>{{edituser.getAllStatuses(1)}}</li>
                            <li>{{edituser.getAllStatuses(2)}}</li>
                            <li>{{edituser.getAllStatuses(3)}}</li>
                            <li>{{edituser.getAllStatuses(4)}}</li>
                            <li>{{edituser.getAllStatuses(5)}}</li>
                            <li>{{edituser.getAllStatuses(6)}}</li>
                          </ul>
                        </div>
                    </li>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="modal fade confirm-deletion-admin-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Удалить пользователя?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <a type="button" href="/admin/user/deleteUser/{{edituser.id}}" class="btn btn-primary">Удалить</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $( "#password" ).val('');
        if($("#sendEmailNotice").val() == "1") {
            $("label[for=sendEmailNotice]").addClass("main-active-checkbox");
            $("#sendEmailNotice").prop("checked", "checked");
        }

        $(".delete").click(function(evt){
            evt.preventDefault();
            $('.confirm-deletion-admin-lg').modal('show');
        });
    });


</script>
{% endblock %}