{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - ПОЛЬЗОВАТЕЛИ{% endblock %}
{% block body %}
<h2>Поиск User</h2> 
<form action="/admin/user/search" method="post">
    <fieldset>
        <fieldset>
            {% for element in form %}
            <div class="control-group">
                {{ element.label(['class': 'control-label']) }}
                <div class="controls">{{ element }}</div>
            </div>
            {% endfor %}
            <div class="control-group">
                {{ submit_button("Search", "class": "btn btn-primary") }}
            </div>
        </fieldset>
</form>
<div><a href="/admin/user/add">Add user</a></div>
<div class="admin-main-wrap user-list">
    <h1>Список пользователей</h1>
    <a href="#" class="admin-add userAdd">Добавить пользователя</a>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Отправить сообщение</div>
                <div>Заблокировать</div>
                <div>Удалить</div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li><span>ФИО</span></li>
                <li><span>Телефон</span></li>
                <li><span>Заявители</span></li>
                <li><span>Жалобы</span></li>
                <li><span>Подписка до</span></li>
                <li><span>Тариф</span></li>
            </ul>
            {% for user in page.items %}
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div>{{user.firstname}} {{user.middlename}} {{user.lastname}}</li>
                <li>456-900-90-00</li>
                <li>35</li>
                <li>29</li>
                <li>22.01.2016</li>
                <li><div class="good-bad extended"></div></li>
            </ul>
            {% endfor %}
        </div>
    </div>
    <div class="admin-table-footer">
        <a href="#">Еще <span>20 пользователей</span></a>
        <a href="#">Показать всех пользователей (<span>34 456</span>)</a>
    </div>
    <div class="admin-pagination-box">
        <a href="#" id="admin-pag-prev">Предыдущие</a>
        <ul>
            <li><a href="#">1</a></li>
            <li><span class="active-pag-page">2</span></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><span>...</span></li>
            <li><a href="#">23</a></li>
        </ul>
        <a href="#" id="admin-pag-next">Следующие</a>
    </div>
</div>
{% for user in page.items %}
{% if loop.first %}
<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>email</th>
        <th>Статус</th>
        <th>Дата регистрации</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% endif %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.email}}</td>
        <td>{{ user.status}}</td>
        <td>{{ user.date_registration}}</td>
        <td><a href="/admin/user/edit/{{ user.id }}">Редактировать</a></td>

        <td><a href="/admin/user/del/{{ user.id }}">Удалить</a></td>
    </tr>
    {% if loop.last %}
    </tbody>
    <tbody>
    <tr> 
        <td colspan="7">
            <div>
              <a href="/admin/user/index">Первая</a>
                <a href="/admin/user/index?page={{ page.before }}">Предыдущая</a>
                <a href="/admin/user/index?page={{ page.next }}">Следующая</a>
                <a href="/admin/user/index?page={{ page.last }}">Последняя</a>
                <span class="help-inline">{{ page.current }} из {{ page.total_pages }}</span>
            </div>
        </td>
    </tr>
    </tbody>
</table>
{% endif %}
{% else %}
В базе нет user
{% endfor %}
{% endblock %}