{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАТЬ АДМИНИСТРАТОРА{% endblock %}
{% block body %}
<div class="admin-main-wrap admin-page">
    <div class="bread-crumbs-holder">
        <a href="/admin/admins/index">Вернуться к списку администраторов</a>
    </div>
    <div class="admin-change-access">
        <span>Добавление нового администратора</span>
        <!--div class="change-access">Изменить доступ</div-->
    </div>
    {{flashSession.output()}}
    <div class="block-user-editing">
        <form action="/admin/admins/create" method="POST" enctype="multipart/form-data">
            <div class="left-block-editing">
                <span>Данные администратора</span>
                <label for="fAdmin">
                    <p>Фамилия</p>
                    {{text_field('surname', 'value':params['surname'], 'id':'fAdmin')}}
                </label>
                <label for="iAdmin">
                    <p>Имя</p>
                    {{text_field('name', 'value':params['name'], 'id':'iAdmin')}}
                </label>
                <label for="oAdmin">
                    <p>Отчество</p>
                    {{text_field('patronymic', 'value':params['patronymic'], 'id':'oAdmin')}}
                </label>
                <label for="telFaxAdmin">
                    <p>Контактный факс, телефон</p>
                    {{ numeric_field('phone', 'value':params['phone'], 'id':'telFaxAdmin')}}
                </label>
                <label for="adminEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':'', 'id':'adminEmail')}}
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="adminPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('password', 'value':'', 'id':'adminPass')}}
                </label>
                <label for="adminAvatar">
                    <div class="avatar-wrapper">
                        <img src="" alt=""><!--todo: maby we need default image-->
                    </div>
                    <p class="changeAvatar">Изменить аватар</p>
                    {{file_field('avatar', 'value':params['avatar'], 'id':'adminAvatar', 'onchange':"readAvatarURL(this, '#edit-avatar')")}}
                </label>
            </div>
            <div class="delete-or-save">
                <button>Сохранить изменения</button>
            </div>
        </form>
    </div>
</div>
{{ partial("layouts/statuschange")}}
<script>
    $(document).ready(function() {
        setTimeout(function(){
            $("#adminPass").val("");
            $('#adminEmail').val("");
        }, 200);
    });
</script>
{% endblock %}