<form action="/admin/admins/create" method="post">
    <fieldset>



            {% for element in form %}
            <div class="control-group">
                {{ element.label(['class': 'control-label']) }}
                <div class="controls">{{ element }}</div>
            </div>
            {% endfor %}

            <div class="control-group">
                {{ submit_button("Создать", "class": "btn btn-primary") }}
            </div>

        </fieldset>
</form>