{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАТЬ АДМИНА{% endblock %}
{% block body %}
<div class="admin-main-wrap admin-page">
    <div class="bread-crumbs-holder">
        <a href="/admin/admins/index">Вернуться к списку администраторов</a>
    </div>
    <h1>Ларина Екатерина Прокоповна</h1>
    <div class="admin-change-access">
        <span>Редактирование пользователей</span>
        <div class="change-access">Изменить доступ</div>
    </div>
    <div class="block-user-editing">
        <form action="/admin/admins/save" method="POST" enctype="multipart/form-data">
            {{hidden_field('id', 'value':admin.id)}}
            <div class="left-block-editing">
                <span>Данные администратора</span>
                <label for="fAdmin">
                    <p>Фамилия</p>
                    {{text_field('lastname', 'value':admin.surname, 'id':'fAdmin')}}
                </label>
                <label for="iAdmin">
                    <p>Имя</p>
                    {{text_field('lastname', 'value':admin.name, 'id':'iAdmin')}}
                </label>
                <label for="oAdmin">
                    <p>Отчество</p>
                    {{text_field('lastname', 'value':admin.patronymic, 'id':'oAdmin')}}
                </label>
                <label for="telFaxAdmin">
                    <p>Контактный факс, телефон</p>
                    {{ numeric_field('phone', 'value':admin.phone, 'id':'telFaxUser')}}
                    <input type="number" id="telFaxAdmin" value="{{admin.phone}}">
                </label>
                <label for="adminEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':admin.email, 'id':'userEmail')}}
                    <input type="email" id="adminEmail" value="{{admin.email}}">
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="adminPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('email', 'value':admin.email, 'id':'userEmail')}}
                    <input type="password" id="adminPass" value="">
                </label>
                <label for="adminAvatar">
                    <div class="avatar-wrapper">
                        <img src="/images/{{admin.avatar}}" alt="">
                    </div>
                    <p class="changeAvatar">Изменить аватар</p>
                    <input type="file" id="adminAvatar">
                </label>
            </div>
            <div class="delete-or-save">
                <button>Удалить администратора</button>
                <button>Сохранить изменения</button>
            </div>
        </form>
    </div>
</div>


<form enctype="multipart/form-data" action="/admin/admins/save" method="post">
    <fieldset>

        <fieldset>

            {% for element in form %}
            <div class="control-group">
                {{ element.label(['class': 'control-label']) }}
                <div class="controls">{{ element }}</div>
            </div>
            {% endfor %}

            <div class="control-group">
                {{ submit_button("Сохранить", "class": "btn btn-primary") }}
            </div>

        </fieldset>
</form>
<script>
    $( document ).ready(function() {
        $( "#password" ).val('');
    });
</script>
{% endblock %}