{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - РЕДАКТИРОВАТЬ АДМИНИСТРАТОРА{% endblock %}
{% block body %}
<div class="admin-main-wrap admin-page">
    <div class="bread-crumbs-holder">
        <a href="/admin/admins/index">Вернуться к списку администраторов</a>
    </div>
    <h1>{{admin.surname}} {{admin.name}} {{admin.patronymic}}</h1>
    {% if user_id == 1 %}
    <div class="admin-change-access">
        <span>Редактирование пользователей</span>
        <div class="change-access j-change-access">Изменить доступ</div>
    </div>
    {% endif %}
    {{flashSession.output()}}
    <div class="block-user-editing">
        <form action="/admin/admins/save" method="POST" enctype="multipart/form-data">
            {{hidden_field('id', 'value':admin.id)}}
            <div class="left-block-editing">
                <span>Данные администратора</span>
                <label for="fAdmin">
                    <p>Фамилия</p>
                    {{text_field('surname', 'value':admin.surname, 'id':'fAdmin')}}
                </label>
                <label for="iAdmin">
                    <p>Имя</p>
                    {{text_field('name', 'value':admin.name, 'id':'iAdmin')}}
                </label>
                <label for="oAdmin">
                    <p>Отчество</p>
                    {{text_field('patronymic', 'value':admin.patronymic, 'id':'oAdmin')}}
                </label>
                <label for="telFaxAdmin">
                    <p>Контактный факс, телефон</p>
                    {{ numeric_field('phone', 'value':admin.phone, 'id':'telFaxAdmin')}}
                </label>
                <label for="adminEmail">
                    <p>E-mail</p>
                    {{text_field('email', 'value':admin.email, 'id':'adminEmail')}}
                </label>
            </div>
            <div class="right-block-editing">
                <span>Сменить пароль</span>
                <label for="adminPass">
                    <p>Задайте новый пароль</p>
                    {{password_field('password', 'value':'', 'id':'adminPass')}}
                </label>
                <label for="adminAvatar">
                    <div class="avatar-wrapper">
                        <img id="edit-avatar" src="/files/avatars/{{admin.avatar}}" alt="">
                    </div>
                    <p class="changeAvatar">Изменить аватар</p>
                    {{file_field('avatar', 'value':'', 'id':'adminAvatar', 'onchange':"readAvatarURL(this, '#edit-avatar')")}}
                </label>
            </div>
            <div class="delete-or-save">
                {% if user_id == 1 AND admin.id != user_id %}
                    <button class="delete" onclick="$('#delete_admin').val('{{admin.id}}');">Удалить администратора</button>
                {% endif %}
                <button>Сохранить изменения</button>                 
            </div>
            {{hidden_field('delete_admin', 'value':'')}}
        </form>
    </div>
</div>
{{ partial("layouts/statuschange")}}
<script>
    $( document ).ready(function() {
        $( "#password" ).val('');
        var params_ = window.location.search.replace("?", "").split("=");
        if (params_.length) {
            if (params_[0] == "ask_admin_rights" && params_[1] == "1") {
                $('.change-access').click();
            }
        }
    });
</script>
{% endblock %}