{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - АДМИНИСТРАТОРЫ{% endblock %}
{% block body %}
<div class="admin-main-wrap admin-list">
    <h1>Список администраторов</h1>
    <a href="#" class="admin-add">Добавить администратора</a>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Отправить сообщение</div>
                <div>Заблокировать</div>
                <div>Удалить</div>
            </div>
        </div>
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li></li>
                <li><span>Аватар</span></li>
                <li><span>Фио</span></li>
                <li><span>E-mail</span></li>
                <li><span>Доступ</span></li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Андреев Александр Александрович</li>
                <li>deckcrew@email.ua</li>
                <li>Редактирование пользователей</li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Аседова Елизавета Виталиевна</li>
                <li>engcrew@email.ua</li>
                <li>Чтение пользователей</li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Гаранян Ованес Суренович</li>
                <li>admin@moryak.com</li>
                <li>Чтение жалоб</li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Валинуров Денис Юрьевич</li>
                <li>sapsan@stream.com.ua</li>
                <li>Редактирование жалоб</li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Горинова Юлия Юрьевна</li>
                <li>crewing@mdship.biz</li>
                <li>Юрист</li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Иванов Павел Александрович</li>
                <li>crew@akmartransport.c...</li>
                <li>Редактирование данных УФАС</li>
            </ul>
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li><img src="images/admin-picture.png" alt=""></li>
                <li>Ермохин Макар Андреевич</li>
                <li>azulmar@te.net.ua </li>
                <li>Редактирование доводов</li>
            </ul>
        </div>
    </div>
    <div class="admin-table-footer">
        <a href="#">Еще <span>20 администраторов</span></a>
        <a href="#">Показать всех администраторов (<span>34</span>)</a>
    </div>
    <div class="admin-pagination-box">
        <a href="#" id="admin-pag-prev">Предыдущие</a>
        <ul>
            <li><a href="#">1</a></li>
            <li><span class="active-pag-page">2</span></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><span>...</span></li>
            <li><a href="#">23</a></li>
        </ul>
        <a href="#" id="admin-pag-next">Следующие</a>
    </div>
</div>


<h2>Поиск admins</h2>
<form action="/admin/admins/search" method="post">
    <fieldset>

<fieldset>

    {% for element in form %}
    <div class="control-group">
        {{ element.label(['class': 'control-label']) }}
        <div class="controls">{{ element }}</div>
    </div>
    {% endfor %}

    <div class="control-group">
        {{ submit_button("Search", "class": "btn btn-primary") }}
    </div>

</fieldset>
</form>




<div><a href="/admin/admins/add">Add admin</a></div>
{% endblock %}