{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - АДМИНИСТРАТОРЫ{% endblock %}
{% block body %}



<h2>Поиск admins</h2>
<form action="/admin/admins/search" method="post">
    <fieldset>

<fieldset>

    {% for element in form %}
    <div class="control-group">
        {{ element.label(['class': 'control-label']) }}
        <div class="controls">{{ element }}</div>
    </div>
    {% endfor %}

    <div class="control-group">
        {{ submit_button("Search", "class": "btn btn-primary") }}
    </div>

</fieldset>
</form>




<div><a href="/admin/admins/add">Add admin</a></div>
{% endblock %}