{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - АДМИНИСТРАТОРЫ{% endblock %}
{% block body %}
{{flashSession.output()}}
<div class="admin-main-wrap admin-list">
    <h1>Список администраторов</h1>
    <a href="/admin/admins/add" class="admin-add">Добавить администратора</a>
    <div class="admin-lt-holder">
        <div class="admin-lt-head">
            <div class="select-all">
                <div></div>Выбрать все
            </div>
            <div class="lt-head-btns">
                <div>Отправить сообщение</div>
                <div>Заблокировать</div>
                <a href="#"><div data-toggle="modal" data-target=".confirm-deletion-admin-lg">Удалить</div></a>
            </div>
        </div>
        <div class="modal fade confirm-deletion-admin-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Удалить админа?</h4>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" onclick="delete_admins()" class="btn btn-primary">Удалить</button>
              </div>
            </div>
          </div>
        </div>
        <div class="admin-lt-content" id="sort-table">
            <ul class="lt-content-top">
                <li></li>
                <li><span>Аватар</span></li>
                <li sort-field="sort-fio"><span class="sortable">Фио</span></li>
                <li sort-field="sort-email"><span class="sortable">E-mail</span></li>
                <li sort-field="sort-access"><span class="sortable">Доступ</span></li>
            </ul>
            {% for user in page.items %}
            {% set permissions = user.getPermissions() %}
            <ul class="lt-content-main" sort-fio="{{user.surname}} {{user.name}}" sort-email="{{user.email}}" sort-access="{{permissions}}" detail-url="{{url('admin/admins/edit/' ~ user.id)}}">
                <li><div class="lt-psevdo-check">{{hidden_field('admin-id', 'value':user.id)}}</div></li>
                <li>{% if user.avatar!='' %}<img src="/files/avatars/{{user.avatar}}" alt="">{% endif %}</li>
                <li>{{user.surname}} {{user.name}}</li>
                <li>{{user.email}}</li>
                <li>{{permissions}}</li>
            </ul>
            {% endfor %}
        </div>
    </div>
    {% if page.total_items > item_per_page %}
        <div class="admin-table-footer">
            {% if page.current * item_per_page < page.total_items %}
                {% set cnt = page.total_items - (page.current * item_per_page) %}
                <a href="#" onclick="$('#next_items').submit()">Еще <span>{{ cnt > item_per_page ? 20 : cnt}} администраторов</span></a><!--todo: -->
                {% else %}
                    <div></div>
            {% endif %}
            <a href="#">Показать всех администраторов (<span>{{page.total_items}}</span>)</a><!--todo: -->
        </div>
        <form id="next_items" method="post">
            {{hidden_field('next-portions-items', 'value':20)}}
        </form>
    {% endif %}
    <div class="admin-pagination-box">
        {% if page.current>1 %}{{ link_to("admin/admins/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("admin/admins/index?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}{{ link_to("admin/admins/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
    </div>
</div>
{% endblock %}