{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Жалобы{% endblock %}
{% block body %}
<div class="admin-main-wrap complaints-list">
    <h1>Список жалоб</h1>
    <div class="admin-lt-holder">
        <div class="admin-lt-content">
            <ul class="lt-content-top">
                <li></li>
                <li><span>Тайтл</span></li>
                <li><span>Наименование закупки</span></li>
                <li><span>Закупка №</span></li>
                <li><span>Дата</span></li>
                <li><span>На</span></li>
                <li><span>Статус</span></li>
            </ul>
            {% for complaint in page.items %}
            <ul class="lt-content-main">
                <li><div class="lt-psevdo-check"></div></li>
                <li>{{ truncate(complaint.complaint_name, 0, 5) }}</li>
                <li>{{ truncate(complaint.purchases_name,0,10) }}</li>
                <li>{{ complaint.auction_id }}</li>
                <li>{{ date('Y.m.d', complaint.date|strtotime) }}</li>
                <li>{{ truncate(complaint.purchases_made, 0, 10) }}</li>
                <li>
                    {% if complaint.status == 'draft' %}
                    <span class="jl-status jl-chernov">Черновик</span>
                    {% elseif complaint.status == 'justified' %}
                    <span class="jl-status jl-done">Обоснована</span>
                    {% elseif complaint.status == 'unfounded' %}
                    <span class="jl-status jl-notdone">Необоснована</span>
                    {% elseif complaint.status == 'under_consideration' %}
                    <span class="jl-status jl-rassmotr">На рассмотрении</span>
                    {% elseif complaint.status == 'submitted' %}
                    <span class="jl-status jl-podana">Подана</span>
                    {% elseif complaint.status == 'recalled' %}
                    <span class="jl-status jl-fail">Отозвана</span>
                    {% elseif complaint.status == 'archive' %}
                    <span class="jl-status jl-archive">Архив</span>
                    {% endif %}
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
    <div class="admin-table-footer">
        <a href="#">Еще <span>20 жалоб</span></a>
        <a href="#">Показать все жалобы(<span>{{page.total_items}}</span>)</a>
    </div>
    <div class="admin-pagination-box">
        {% if page.current>1 %}{{ link_to("admin/complaints/index?page=" ~ page.before, 'Предыдущие', 'id' : 'admin-pag-prev') }}{% endif %}
        <ul>
            {% for page_item in paginator_builder %}
            <li>
                {% if page_item['type'] == 'page' %}
                {{ link_to("admin/complaints/index?page=" ~ page_item['num'], page_item['num']) }}
                {% elseif page_item['type'] == 'delimer' %}
                <span>...</span>
                {% elseif page_item['type'] == 'current' %}
                <span class="active-pag-page">{{page_item['num']}}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% if page.total_pages > page.current %}{{ link_to("admin/complaints/index?page=" ~ page.next, 'Следующие', 'id' : 'admin-pag-next') }}{% endif %}
    </div>
</div>
{% endblock %}
