{% extends "base-template.phtml" %}
{% block title %}ФАС ОНЛАЙН - Жалобы{% endblock %}
{% block body %}
    <!-- ****************** complaints preview ***************** -->
    <div class="admin-main-wrap complaints-preview-wrap">
        <div class="bread-crumbs-holder">
            <a href="/admin/complaints/index">Вернуться на страницу жалоб</a>
        </div>
        <h1>Просмотр жалобы</h1>
        <div class="notification-number-box notif-unreasonably"> <!-- if notification is rightly - remoove class "notif-unreasonably" -->
            <p>Номер извещения №
                <span>{{complaint.auction_id}}</span>
                <span class="rightly-wrongly">Необоснованна</span>
            </p>
        </div>
        <div class="edit-notification-box">
            <a href="#" class="edit-notif-active">Редактировать</a>
            <a href="#">Копировать</a>
            <a href="#">Отозвать</a>
            <a href="#">В архив</a>
            <a href="#">Удалить</a>
        </div>
        <div class="details-complaint">
            <div class="deploy-complaint"><span>Показать подробно</span></div>
            <div class="complaints-content">
                <h2>{{complaint.complaint_name}}</h2>
                <div class="complaints-doc">
                    <p><span></span><span></span>Решение по извещению 127563728493872.dov (125 Кб)</p>
                    <p><span></span><span></span>Доказательства.pdf (34 Кб)</p><!--todo:-->
                </div>
                <div class="complaints-main mCustomScrollbar">
                    <h3>{{complaint.purchases_name}}</h3>
                    {{complaint.complaint_text}}
                </div>
            </div>
        </div>
        <div class="complaints-lawyer-quest">
            <h3>Вопросы юристу</h3>
            {% set questions = complaint.getComplaintQuestion() %}
            {% for question in questions %}
            <div class="compl-quest-cont">
                {% set answers = complaint.getComplaintQuestionAnswer(question.id) %}
                {% if answers.count() == 0 %}
                    <form action="#" method="POST">
                        <p>— {{question.text}}</p>
                        <label for="" class="hidden-textarea">
                            <span>Новое сообщение</span>
                            <div></div>
                            <textarea name="lawyer-answer"></textarea>
                        </label>
                        <div class="opacity-btn"></div>
                        <button>Ответить</button>
                    </form>
                {% else %}
                    <p>— {{question.text}}</p>
                    {% set answers = complaint.getComplaintQuestionAnswer(question.id) %}
                    {% for answer in answers %}
                        <div class="clarifying-issue">
                        {{answer.text}}
                        </div>
                        <div class="legal-advisor">
                            {% set answer_owner = complaint.getAnswerOwner(answer.admin_id) %}
                            {% if answer_owner['photo'] %}
                                <div><img src="/files/avatars/{{answer_owner['photo']}}" alt=""></div>
                            {% endif %}
                            <p>{{answer_owner['user']}}</p>
                            <span>Ваш юридический консультант</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- ******************************************************* -->
{% endblock %}
